# Generated by Django 6.0.5 on 2026-05-29 21:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturing', '0068_remove_erpimportpatternfieldmapping_pattern_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('planned_quantity', models.IntegerField(default=1)),
                ('good_quantity', models.IntegerField(default=0)),
                ('scrap_quantity', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', max_length=20)),
                ('scheduled_start', models.DateTimeField(blank=True, null=True)),
                ('scheduled_end', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='manufacturing.productmodel')),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='manufacturing.productionline')),
            ],
            options={
                'db_table': 'execution_work_order',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['production_line', 'status'], name='exec_wo_line_status_idx'), models.Index(fields=['status', 'scheduled_start'], name='exec_wo_status_start_idx')],
            },
        ),
    ]
