# Generated by Django 6.0.5 on 2026-06-28 05:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0010_safetymedicalcase_affected_person_and_more'),
        ('execution', '0001_initial'),
        ('manufacturing', '0076_alter_audit_audit_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GembaWalkSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_name', models.CharField(blank=True, default='', max_length=50)),
                ('walk_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PLANNED', max_length=20)),
                ('observer', models.CharField(blank=True, default='', max_length=255)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_gemba_sessions', to=settings.AUTH_USER_MODEL)),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gemba_sessions', to='manufacturing.productionline')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gemba_sessions', to='manufacturing.plant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_gemba_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'execution_gemba_walk_session',
                'ordering': ['-walk_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GembaObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(blank=True, default='', max_length=100)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('area', models.CharField(max_length=255)),
                ('focus', models.CharField(blank=True, default='', max_length=255)),
                ('category', models.CharField(choices=[('PRODUCTIVITY', 'Productivity'), ('QUALITY', 'Quality'), ('SAFETY', 'Safety'), ('FIVE_S', '5S'), ('MAINTENANCE', 'Maintenance'), ('MATERIAL', 'Material'), ('MORALE', 'Morale'), ('OTHER', 'Other')], max_length=30)),
                ('severity', models.CharField(choices=[('INFO', 'Info'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='INFO', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20)),
                ('linked_resource_text', models.CharField(blank=True, default='', max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_REVIEW', 'In Review'), ('ACTION_REQUIRED', 'Action Required'), ('CONVERTED_TO_ACTION', 'Converted to Action'), ('CONVERTED_TO_ISSUE', 'Converted to Issue'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], db_index=True, default='OPEN', max_length=25)),
                ('resolution_note', models.TextField(blank=True, default='')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_gemba_observations', to=settings.AUTH_USER_MODEL)),
                ('created_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gemba_observations', to='check.action')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_gemba_observations', to=settings.AUTH_USER_MODEL)),
                ('created_issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gemba_observations', to='check.problem')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gemba_observations', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_gemba_observations', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_gemba_observations', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='execution.gembawalksession')),
            ],
            options={
                'db_table': 'execution_gemba_observation',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GembaObservationActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('ASSIGNED', 'Assigned'), ('STATUS_CHANGED', 'Status Changed'), ('CONVERTED_TO_ACTION', 'Converted to Action'), ('CONVERTED_TO_ISSUE', 'Converted to Issue'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('REOPENED', 'Reopened')], default='CREATED', max_length=30)),
                ('message', models.TextField(blank=True, default='')),
                ('old_status', models.CharField(blank=True, max_length=25, null=True)),
                ('new_status', models.CharField(blank=True, max_length=25, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gemba_activities', to=settings.AUTH_USER_MODEL)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='execution.gembaobservation')),
            ],
            options={
                'db_table': 'execution_gemba_observation_activity',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['observation'], name='exec_gemba_act_obs_idx'), models.Index(fields=['event_type'], name='exec_gemba_act_type_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='gembawalksession',
            index=models.Index(fields=['line', 'status'], name='exec_gemba_sess_line_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='gembawalksession',
            index=models.Index(fields=['walk_date', 'shift_name'], name='exec_gemba_sess_date_idx'),
        ),
        migrations.AddIndex(
            model_name='gembaobservation',
            index=models.Index(fields=['session', 'status'], name='exec_gemba_obs_ssn_stat_idx'),
        ),
        migrations.AddIndex(
            model_name='gembaobservation',
            index=models.Index(fields=['status', 'severity'], name='exec_gemba_obs_stat_sev_idx'),
        ),
        migrations.AddIndex(
            model_name='gembaobservation',
            index=models.Index(fields=['owner', 'due_date'], name='exec_gemba_obs_owner_due_idx'),
        ),
        migrations.AddIndex(
            model_name='gembaobservation',
            index=models.Index(fields=['created_issue'], name='exec_gemba_obs_issue_idx'),
        ),
        migrations.AddIndex(
            model_name='gembaobservation',
            index=models.Index(fields=['created_action'], name='exec_gemba_obs_action_idx'),
        ),
    ]
