# Generated by Django 6.0.5 on 2026-06-28

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0002_gembawalksession_gembaobservation_and_more'),
    ]

    operations = [
        # Add new fields to GembaObservation
        migrations.AddField(
            model_name='gembaobservation',
            name='location_path',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='gembaobservation',
            name='location_label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='gembaobservation',
            name='verification_note',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='gembaobservation',
            name='verified_by',
            field=models.ForeignKey(
                blank=True, null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='verified_gemba_observations',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='gembaobservation',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        # Update status choices to include VERIFIED, REOPENED
        migrations.AlterField(
            model_name='gembaobservation',
            name='status',
            field=models.CharField(
                choices=[
                    ('OPEN', 'Open'),
                    ('IN_REVIEW', 'In Review'),
                    ('ACTION_REQUIRED', 'Action Required'),
                    ('CONVERTED_TO_ACTION', 'Converted to Action'),
                    ('CONVERTED_TO_ISSUE', 'Converted to Issue'),
                    ('RESOLVED', 'Resolved'),
                    ('VERIFIED', 'Verified'),
                    ('CLOSED', 'Closed'),
                    ('REOPENED', 'Reopened'),
                    ('CANCELLED', 'Cancelled'),
                ],
                db_index=True,
                default='OPEN',
                max_length=25,
            ),
        ),
        # Update event type choices
        migrations.AlterField(
            model_name='gembaobservationactivity',
            name='event_type',
            field=models.CharField(
                choices=[
                    ('CREATED', 'Created'),
                    ('UPDATED', 'Updated'),
                    ('ASSIGNED', 'Assigned'),
                    ('DUE_DATE_SET', 'Due Date Set'),
                    ('STATUS_CHANGED', 'Status Changed'),
                    ('CONVERTED_TO_ACTION', 'Converted to Action'),
                    ('CONVERTED_TO_ISSUE', 'Converted to Issue'),
                    ('RESOLVED', 'Resolved'),
                    ('VERIFIED', 'Verified'),
                    ('CLOSED', 'Closed'),
                    ('REOPENED', 'Reopened'),
                    ('CANCELLED', 'Cancelled'),
                ],
                default='CREATED',
                max_length=30,
            ),
        ),
        # Add index for verified_by
        migrations.AddIndex(
            model_name='gembaobservation',
            index=models.Index(fields=['verified_by'], name='exec_gemba_obs_verified_idx'),
        ),
    ]
