# Generated by Django 6.0.5 on 2026-06-28 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0003_gemba_observation_verification_location'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='gembaobservation',
            name='exec_gemba_obs_verified_idx',
        ),
    ]
