# Generated by Django 6.0.5 on 2026-06-30 04:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0004_remove_gembaobservation_exec_gemba_obs_verified_idx'),
        ('manufacturing', '0076_alter_audit_audit_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VsmChart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('chart_type', models.CharField(choices=[('CURRENT_STATE', 'Current State'), ('FUTURE_STATE', 'Future State'), ('HISTORICAL', 'Historical')], default='CURRENT_STATE', max_length=20)),
                ('source_mode', models.CharField(choices=[('MANUAL', 'Manual'), ('LINKED', 'Linked to Production Line')], default='MANUAL', max_length=20)),
                ('supplier_name', models.CharField(blank=True, default='Raw Material Supply', max_length=255)),
                ('customer_name', models.CharField(blank=True, default='Finished Goods Customer', max_length=255)),
                ('production_control_title', models.CharField(blank=True, default='Production Control', max_length=255)),
                ('control_method', models.CharField(blank=True, default='Kanban / Pull', max_length=255)),
                ('schedule_frequency', models.CharField(blank=True, default='Daily', max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vsm_charts', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vsm_charts', to='manufacturing.department')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vsm_charts', to='manufacturing.plant')),
                ('production_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vsm_charts', to='manufacturing.productionline')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_vsm_charts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'execution_vsm_chart',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='VsmChartInformationFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_type', models.CharField(max_length=50)),
                ('from_id', models.CharField(blank=True, default='', max_length=255)),
                ('to_type', models.CharField(max_length=50)),
                ('to_id', models.CharField(blank=True, default='', max_length=255)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('frequency', models.CharField(blank=True, default='', max_length=255)),
                ('flow_style', models.CharField(choices=[('MANUAL', 'Manual'), ('ELECTRONIC', 'Electronic'), ('KANBAN', 'Kanban')], default='MANUAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='information_flows', to='execution.vsmchart')),
            ],
            options={
                'db_table': 'execution_vsm_chart_info_flow',
            },
        ),
        migrations.CreateModel(
            name='VsmChartInventory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.IntegerField()),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('quantity', models.IntegerField(default=0)),
                ('wait_time_value', models.FloatField(blank=True, null=True)),
                ('wait_time_unit', models.CharField(blank=True, default='days', max_length=20)),
                ('severity', models.CharField(choices=[('NORMAL', 'Normal'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], default='NORMAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='execution.vsmchart')),
            ],
            options={
                'db_table': 'execution_vsm_chart_inventory',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='VsmChartMaterialFlow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_type', models.CharField(max_length=50)),
                ('from_id', models.CharField(blank=True, default='', max_length=255)),
                ('to_type', models.CharField(max_length=50)),
                ('to_id', models.CharField(blank=True, default='', max_length=255)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('flow_type', models.CharField(choices=[('PUSH', 'Push'), ('PULL', 'Pull'), ('KANBAN', 'Kanban'), ('FIFO', 'FIFO'), ('SUPERMARKET', 'Supermarket')], default='PUSH', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_flows', to='execution.vsmchart')),
            ],
            options={
                'db_table': 'execution_vsm_chart_mat_flow',
            },
        ),
        migrations.CreateModel(
            name='VsmChartProcess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.IntegerField()),
                ('name', models.CharField(max_length=255)),
                ('department_name', models.CharField(blank=True, default='', max_length=255)),
                ('resource_group_name', models.CharField(blank=True, default='', max_length=255)),
                ('operator_count', models.IntegerField(default=1)),
                ('cycle_time_value', models.FloatField(blank=True, null=True)),
                ('cycle_time_unit', models.CharField(blank=True, default='sec', max_length=20)),
                ('changeover_time_value', models.FloatField(blank=True, null=True)),
                ('changeover_time_unit', models.CharField(blank=True, default='sec', max_length=20)),
                ('uptime_percent', models.FloatField(blank=True, null=True)),
                ('yield_percent', models.FloatField(blank=True, null=True)),
                ('wip', models.IntegerField(blank=True, null=True)),
                ('is_bottleneck', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='execution.vsmchart')),
                ('linked_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.department')),
                ('linked_resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.resource')),
                ('linked_resource_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='manufacturing.resourcegroup')),
            ],
            options={
                'db_table': 'execution_vsm_chart_process',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='VsmChartTimelineSegment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.IntegerField()),
                ('wait_time_value', models.FloatField(blank=True, null=True)),
                ('wait_time_unit', models.CharField(blank=True, default='days', max_length=20)),
                ('process_time_value', models.FloatField(blank=True, null=True)),
                ('process_time_unit', models.CharField(blank=True, default='sec', max_length=20)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_segments', to='execution.vsmchart')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timeline_segments', to='execution.vsmchartprocess')),
            ],
            options={
                'db_table': 'execution_vsm_chart_timeline',
                'ordering': ['sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='vsmchart',
            index=models.Index(fields=['production_line', 'status'], name='exec_vsm_line_status_idx'),
        ),
        migrations.AddIndex(
            model_name='vsmchart',
            index=models.Index(fields=['status', 'chart_type'], name='exec_vsm_status_type_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vsmchartprocess',
            unique_together={('chart', 'sequence')},
        ),
    ]
