# Generated by Django 5.1 on 2026-06-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("execution", "0005_add_vsm_chart_models"),
    ]

    operations = [
        migrations.AddField(
            model_name="vsmchartprocess",
            name="shifts_per_day",
            field=models.IntegerField(default=1),
        ),
    ]
