# Generated by Django 6.0.5 on 2026-06-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0006_vsmchartprocess_shifts_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='vsmchart',
            name='available_minutes_per_shift',
            field=models.FloatField(blank=True, default=450.0, help_text='Available working minutes per shift (default 450 = 8h - breaks)', null=True),
        ),
        migrations.AddField(
            model_name='vsmchart',
            name='chart_shifts_per_day',
            field=models.IntegerField(blank=True, default=1, help_text='Number of shifts per day for takt calculation', null=True),
        ),
        migrations.AddField(
            model_name='vsmchart',
            name='customer_demand_rate',
            field=models.FloatField(blank=True, help_text='Customer demand in units per day', null=True),
        ),
    ]
