# Generated by Django 6.0.5 on 2026-06-30 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0007_vsmchart_available_minutes_per_shift_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vsmchartmaterialflow',
            name='delivery_frequency',
            field=models.CharField(blank=True, default='', help_text='Delivery frequency label (e.g. Daily, Weekly, 2x/week)', max_length=100),
        ),
        migrations.AlterField(
            model_name='vsmchart',
            name='customer_name',
            field=models.CharField(blank=True, default='FG Customer', max_length=255),
        ),
        migrations.AlterField(
            model_name='vsmchart',
            name='supplier_name',
            field=models.CharField(blank=True, default='RM Supply', max_length=255),
        ),
    ]
