# Generated by Django 6.0.5 on 2026-06-30 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0008_vsmchartmaterialflow_delivery_frequency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vsmchartprocess',
            name='is_pacemaker',
            field=models.BooleanField(default=False, help_text='The pacemaker process — the one process scheduled directly by Production Control'),
        ),
        migrations.AddField(
            model_name='vsmchartprocess',
            name='target_cycle_time_value',
            field=models.FloatField(blank=True, help_text='Target cycle time for future state — used when chart_type=FUTURE_STATE', null=True),
        ),
        migrations.AddField(
            model_name='vsmchartprocess',
            name='target_wip',
            field=models.IntegerField(blank=True, help_text='Target WIP for future state — used when chart_type=FUTURE_STATE', null=True),
        ),
    ]
