# Generated by Django 6.0.5 on 2026-07-01 14:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0009_add_vsm_pacemaker_future_state_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='vsmchart',
            name='customer_demand_period',
            field=models.CharField(blank=True, default='day', help_text='Demand period: day, week, month', max_length=20),
        ),
        migrations.AddField(
            model_name='vsmchart',
            name='customer_demand_unit',
            field=models.CharField(blank=True, default='units', help_text='Demand unit: units, pieces, kg, etc.', max_length=50),
        ),
        migrations.AlterField(
            model_name='vsmchartmaterialflow',
            name='flow_type',
            field=models.CharField(choices=[('PUSH', 'Push'), ('PULL', 'Pull'), ('KANBAN', 'Kanban'), ('FIFO', 'FIFO'), ('SUPERMARKET', 'Supermarket'), ('SHIPMENT', 'Shipment')], default='PUSH', max_length=20),
        ),
        migrations.CreateModel(
            name='VsmImprovementOpportunity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('opportunity_type', models.CharField(choices=[('HIGH_WIP', 'High WIP'), ('CT_ABOVE_TAKT', 'Cycle Time Above Takt'), ('LONG_CHANGEOVER', 'Long Changeover'), ('LOW_UPTIME', 'Low Uptime'), ('QUALITY_LOSS', 'Quality Loss'), ('BOTTLENECK', 'Bottleneck'), ('FLOW_BREAK', 'Flow Break')], max_length=30)),
                ('severity', models.CharField(choices=[('MINOR', 'Minor'), ('MAJOR', 'Major'), ('CRITICAL', 'Critical')], max_length=20)),
                ('label', models.CharField(max_length=255)),
                ('message', models.TextField(blank=True, default='')),
                ('acknowledged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='improvement_opportunities', to='execution.vsmchart')),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='improvement_opportunities', to='execution.vsmchartinventory')),
                ('process', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='improvement_opportunities', to='execution.vsmchartprocess')),
            ],
            options={
                'db_table': 'execution_vsm_improvement_opp',
                'ordering': ['-severity', 'created_at'],
            },
        ),
    ]
