# Generated by Django 6.0.5 on 2026-07-01 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0010_vsmchart_customer_demand_period_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vsmchartinformationflow',
            name='controlled_process_id',
            field=models.CharField(blank=True, default='', help_text='The process ID that this flow controls/schedules', max_length=255),
        ),
        migrations.AddField(
            model_name='vsmchartinformationflow',
            name='method',
            field=models.CharField(blank=True, default='', help_text='Method description — e.g. EDI, ERP email, Paper dispatch list, Kanban card', max_length=255),
        ),
        migrations.AddField(
            model_name='vsmchartinformationflow',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vsmchartinformationflow',
            name='transmission_type',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('ELECTRONIC', 'Electronic'), ('EDI', 'EDI'), ('SYSTEM', 'System'), ('KANBAN', 'Kanban'), ('UNKNOWN', 'Unknown')], default='MANUAL', help_text='Transmission type — MANUAL, ELECTRONIC, EDI, SYSTEM, KANBAN, UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='vsmchartinformationflow',
            name='trigger_type',
            field=models.CharField(blank=True, choices=[('CUSTOMER_ORDER', 'Customer order'), ('FORECAST', 'Forecast'), ('PRODUCTION_SCHEDULE', 'Production schedule'), ('RELEASE_SCHEDULE', 'Release schedule'), ('KANBAN_SIGNAL', 'Kanban signal'), ('PULL_SIGNAL', 'Pull signal'), ('SUPERMARKET_REPLENISHMENT', 'Supermarket replenishment'), ('FIFO_REPLENISHMENT', 'FIFO replenishment'), ('MANUAL_INSTRUCTION', 'Manual instruction'), ('UNKNOWN', 'Unknown')], default='', help_text='What triggers this information flow — e.g. CUSTOMER_ORDER, PRODUCTION_SCHEDULE, KANBAN_SIGNAL', max_length=30),
        ),
    ]
