# Generated by Django 6.0.5 on 2026-07-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0011_vsmchartinformationflow_controlled_process_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vsmchartmaterialflow',
            name='batch_size',
            field=models.IntegerField(blank=True, help_text='Number of units per trip', null=True),
        ),
        migrations.AddField(
            model_name='vsmchartmaterialflow',
            name='distance',
            field=models.FloatField(blank=True, help_text='Travel distance for this material flow', null=True),
        ),
        migrations.AddField(
            model_name='vsmchartmaterialflow',
            name='distance_unit',
            field=models.CharField(blank=True, default='m', help_text='Distance unit: m, ft, km, mi', max_length=20),
        ),
        migrations.AddField(
            model_name='vsmchartmaterialflow',
            name='equipment_label',
            field=models.CharField(blank=True, default='', help_text='Custom equipment label override', max_length=100),
        ),
        migrations.AddField(
            model_name='vsmchartmaterialflow',
            name='equipment_type',
            field=models.CharField(choices=[('NONE', 'None'), ('MANUAL_CARRY', 'Manual carry'), ('HAND_CART', 'Hand cart'), ('PALLET_JACK', 'Pallet jack'), ('FORKLIFT', 'Forklift'), ('TUGGER', 'Tugger'), ('CONVEYOR', 'Conveyor'), ('AGV', 'AGV'), ('TRUCK', 'Truck'), ('OTHER', 'Other'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='Material handling equipment type', max_length=30),
        ),
        migrations.AddField(
            model_name='vsmchartmaterialflow',
            name='handling_time',
            field=models.FloatField(blank=True, help_text='Time required for material handling per trip', null=True),
        ),
        migrations.AddField(
            model_name='vsmchartmaterialflow',
            name='handling_time_unit',
            field=models.CharField(blank=True, default='min', help_text='Handling time unit: min, sec, hr', max_length=20),
        ),
        migrations.AddField(
            model_name='vsmchartmaterialflow',
            name='is_internal_transport',
            field=models.BooleanField(default=False, help_text='True if this is an internal plant transport (not supplier/customer shipment)'),
        ),
        migrations.AddField(
            model_name='vsmchartmaterialflow',
            name='is_transportation_waste',
            field=models.BooleanField(default=False, help_text='True if this movement is classified as transportation waste'),
        ),
        migrations.AddField(
            model_name='vsmchartmaterialflow',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='vsmchartmaterialflow',
            name='transport_cost_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='Transport cost level: LOW, MEDIUM, HIGH, UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='vsmchartmaterialflow',
            name='transport_severity',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', help_text='Transport severity: NORMAL, WARNING, CRITICAL, UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='vsmchartmaterialflow',
            name='trip_frequency',
            field=models.CharField(blank=True, default='', help_text='Trip frequency (e.g. Every 2h, Daily, As needed)', max_length=100),
        ),
        migrations.AddField(
            model_name='vsmchartprocess',
            name='process_type',
            field=models.CharField(choices=[('MANUFACTURING', 'Manufacturing'), ('INSPECTION', 'Inspection'), ('LOGISTICS', 'Logistics'), ('STORAGE', 'Storage'), ('TRANSPORT', 'Transport'), ('PACKAGING', 'Packaging'), ('SUPPORT', 'Support'), ('UNKNOWN', 'Unknown')], default='MANUFACTURING', help_text='Process classification: MANUFACTURING, INSPECTION, LOGISTICS, etc.', max_length=30),
        ),
        migrations.AddField(
            model_name='vsmchartprocess',
            name='value_add_type',
            field=models.CharField(choices=[('VALUE_ADD', 'Value Add'), ('NON_VALUE_ADD_REQUIRED', 'Non-Value Add Required'), ('NON_VALUE_ADD_WASTE', 'Non-Value Add Waste'), ('UNKNOWN', 'Unknown')], default='VALUE_ADD', help_text='Value-add classification: VALUE_ADD, NON_VALUE_ADD_REQUIRED, NON_VALUE_ADD_WASTE', max_length=30),
        ),
    ]
