# Generated by Django 6.0.5 on 2026-07-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0012_vsm_material_handling_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='vsmchart',
            name='break_time_per_shift',
            field=models.FloatField(blank=True, default=0.0, help_text='Break time in minutes per shift', null=True),
        ),
        migrations.AddField(
            model_name='vsmchart',
            name='planned_downtime_per_shift',
            field=models.FloatField(blank=True, default=0.0, help_text='Planned downtime in minutes per shift', null=True),
        ),
        migrations.AddField(
            model_name='vsmchart',
            name='working_days_per_week',
            field=models.IntegerField(blank=True, default=5, help_text='Number of working days per week', null=True),
        ),
    ]
