# Generated by Django 6.0.5 on 2026-07-02 04:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('execution', '0013_vsm_demand_takt_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='VsmDemandTakt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_demand_rate', models.FloatField(blank=True, help_text='Customer demand in units per period', null=True)),
                ('customer_demand_unit', models.CharField(blank=True, default='units', max_length=50)),
                ('customer_demand_period', models.CharField(blank=True, default='day', max_length=20)),
                ('available_minutes_per_shift', models.FloatField(blank=True, default=576.0, help_text='Available working minutes per shift', null=True)),
                ('break_time_per_shift', models.FloatField(blank=True, default=36.0, help_text='Break time in minutes per shift', null=True)),
                ('planned_downtime_per_shift', models.FloatField(blank=True, default=30.0, help_text='Planned downtime in minutes per shift', null=True)),
                ('chart_shifts_per_day', models.IntegerField(blank=True, default=1, null=True)),
                ('working_days_per_week', models.IntegerField(blank=True, default=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chart', models.OneToOneField(help_text='The VSM chart this demand/takt record belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='demand_takt', to='execution.vsmchart')),
            ],
            options={
                'verbose_name': 'VSM Demand & Takt',
                'db_table': 'execution_vsm_demand_takt',
            },
        ),
    ]
