"""Domain constants for the execution app."""

WORK_ORDER_OPEN = "OPEN"
WORK_ORDER_IN_PROGRESS = "IN_PROGRESS"
WORK_ORDER_DONE = "DONE"

# ── Gemba Walk Session ──
GEMBA_SESSION_PLANNED = "PLANNED"
GEMBA_SESSION_IN_PROGRESS = "IN_PROGRESS"
GEMBA_SESSION_COMPLETED = "COMPLETED"
GEMBA_SESSION_CANCELLED = "CANCELLED"

GEMBA_SESSION_STATUS_CHOICES = [
    (GEMBA_SESSION_PLANNED, "Planned"),
    (GEMBA_SESSION_IN_PROGRESS, "In Progress"),
    (GEMBA_SESSION_COMPLETED, "Completed"),
    (GEMBA_SESSION_CANCELLED, "Cancelled"),
]

# ── Gemba Observation ──
GEMBA_CATEGORY_PRODUCTIVITY = "PRODUCTIVITY"
GEMBA_CATEGORY_QUALITY = "QUALITY"
GEMBA_CATEGORY_SAFETY = "SAFETY"
GEMBA_CATEGORY_FIVE_S = "FIVE_S"
GEMBA_CATEGORY_MAINTENANCE = "MAINTENANCE"
GEMBA_CATEGORY_MATERIAL = "MATERIAL"
GEMBA_CATEGORY_MORALE = "MORALE"
GEMBA_CATEGORY_OTHER = "OTHER"

GEMBA_CATEGORY_CHOICES = [
    (GEMBA_CATEGORY_PRODUCTIVITY, "Productivity"),
    (GEMBA_CATEGORY_QUALITY, "Quality"),
    (GEMBA_CATEGORY_SAFETY, "Safety"),
    (GEMBA_CATEGORY_FIVE_S, "5S"),
    (GEMBA_CATEGORY_MAINTENANCE, "Maintenance"),
    (GEMBA_CATEGORY_MATERIAL, "Material"),
    (GEMBA_CATEGORY_MORALE, "Morale"),
    (GEMBA_CATEGORY_OTHER, "Other"),
]

GEMBA_SEVERITY_INFO = "INFO"
GEMBA_SEVERITY_LOW = "LOW"
GEMBA_SEVERITY_MEDIUM = "MEDIUM"
GEMBA_SEVERITY_HIGH = "HIGH"
GEMBA_SEVERITY_CRITICAL = "CRITICAL"

GEMBA_SEVERITY_CHOICES = [
    (GEMBA_SEVERITY_INFO, "Info"),
    (GEMBA_SEVERITY_LOW, "Low"),
    (GEMBA_SEVERITY_MEDIUM, "Medium"),
    (GEMBA_SEVERITY_HIGH, "High"),
    (GEMBA_SEVERITY_CRITICAL, "Critical"),
]

GEMBA_PRIORITY_LOW = "LOW"
GEMBA_PRIORITY_MEDIUM = "MEDIUM"
GEMBA_PRIORITY_HIGH = "HIGH"
GEMBA_PRIORITY_URGENT = "URGENT"

GEMBA_PRIORITY_CHOICES = [
    (GEMBA_PRIORITY_LOW, "Low"),
    (GEMBA_PRIORITY_MEDIUM, "Medium"),
    (GEMBA_PRIORITY_HIGH, "High"),
    (GEMBA_PRIORITY_URGENT, "Urgent"),
]

GEMBA_OBSERVATION_STATUS_OPEN = "OPEN"
GEMBA_OBSERVATION_STATUS_IN_REVIEW = "IN_REVIEW"
GEMBA_OBSERVATION_STATUS_ACTION_REQUIRED = "ACTION_REQUIRED"
GEMBA_OBSERVATION_STATUS_CONVERTED_TO_ACTION = "CONVERTED_TO_ACTION"
GEMBA_OBSERVATION_STATUS_CONVERTED_TO_ISSUE = "CONVERTED_TO_ISSUE"
GEMBA_OBSERVATION_STATUS_RESOLVED = "RESOLVED"
GEMBA_OBSERVATION_STATUS_VERIFIED = "VERIFIED"
GEMBA_OBSERVATION_STATUS_CLOSED = "CLOSED"
GEMBA_OBSERVATION_STATUS_REOPENED = "REOPENED"
GEMBA_OBSERVATION_STATUS_CANCELLED = "CANCELLED"

GEMBA_OBSERVATION_STATUS_CHOICES = [
    (GEMBA_OBSERVATION_STATUS_OPEN, "Open"),
    (GEMBA_OBSERVATION_STATUS_IN_REVIEW, "In Review"),
    (GEMBA_OBSERVATION_STATUS_ACTION_REQUIRED, "Action Required"),
    (GEMBA_OBSERVATION_STATUS_CONVERTED_TO_ACTION, "Converted to Action"),
    (GEMBA_OBSERVATION_STATUS_CONVERTED_TO_ISSUE, "Converted to Issue"),
    (GEMBA_OBSERVATION_STATUS_RESOLVED, "Resolved"),
    (GEMBA_OBSERVATION_STATUS_VERIFIED, "Verified"),
    (GEMBA_OBSERVATION_STATUS_CLOSED, "Closed"),
    (GEMBA_OBSERVATION_STATUS_REOPENED, "Reopened"),
    (GEMBA_OBSERVATION_STATUS_CANCELLED, "Cancelled"),
]

# ── Gemba Activity Events ──
GEMBA_EVENT_CREATED = "CREATED"
GEMBA_EVENT_UPDATED = "UPDATED"
GEMBA_EVENT_ASSIGNED = "ASSIGNED"
GEMBA_EVENT_DUE_DATE_SET = "DUE_DATE_SET"
GEMBA_EVENT_STATUS_CHANGED = "STATUS_CHANGED"
GEMBA_EVENT_CONVERTED_TO_ACTION = "CONVERTED_TO_ACTION"
GEMBA_EVENT_CONVERTED_TO_ISSUE = "CONVERTED_TO_ISSUE"
GEMBA_EVENT_RESOLVED = "RESOLVED"
GEMBA_EVENT_VERIFIED = "VERIFIED"
GEMBA_EVENT_CLOSED = "CLOSED"
GEMBA_EVENT_REOPENED = "REOPENED"
GEMBA_EVENT_CANCELLED = "CANCELLED"

GEMBA_EVENT_TYPE_CHOICES = [
    (GEMBA_EVENT_CREATED, "Created"),
    (GEMBA_EVENT_UPDATED, "Updated"),
    (GEMBA_EVENT_ASSIGNED, "Assigned"),
    (GEMBA_EVENT_DUE_DATE_SET, "Due Date Set"),
    (GEMBA_EVENT_STATUS_CHANGED, "Status Changed"),
    (GEMBA_EVENT_CONVERTED_TO_ACTION, "Converted to Action"),
    (GEMBA_EVENT_CONVERTED_TO_ISSUE, "Converted to Issue"),
    (GEMBA_EVENT_RESOLVED, "Resolved"),
    (GEMBA_EVENT_VERIFIED, "Verified"),
    (GEMBA_EVENT_CLOSED, "Closed"),
    (GEMBA_EVENT_REOPENED, "Reopened"),
    (GEMBA_EVENT_CANCELLED, "Cancelled"),
]
