export const theme = {
  page: "bg-background text-foreground",
  header: "bg-muted border-b border-border",
  subHeader: "bg-card border-b border-border",
  actionBar: "bg-toolbar border-b border-border",
  bulkBar: "bg-toolbar border-b border-border",
  card: "bg-card text-card-foreground border border-border/50 shadow-sm shadow-foreground/5",
  cardHover: "hover:bg-table-row-hover",
  row: "bg-table-row",
  rowSelected: "ring-1 ring-selection-border/35 border-selection-border/50 bg-table-selected",
  input: "bg-card border border-border text-foreground placeholder:text-muted-foreground focus:border-border-strong focus:outline-none focus:ring-2 focus:ring-ring/20",
  modal: "bg-popover text-popover-foreground border border-border shadow-xl",
  dropdown: "bg-popover text-popover-foreground border border-border shadow-xl",
  textPrimary: "text-foreground",
  textSecondary: "text-secondary-foreground",
  textMuted: "text-muted-foreground",
  textDisabled: "text-muted-foreground",
  icon: "text-muted-foreground",
  iconStrong: "text-foreground",
  iconAccent: "text-primary",
  buttonPrimary: "text-primary-foreground bg-primary hover:bg-accent shadow-sm",
  buttonSecondary: "text-secondary-foreground hover:bg-secondary",
  buttonGhost: "text-muted-foreground hover:text-foreground hover:bg-muted",
  buttonDanger: "text-danger hover:bg-danger/10",
  buttonDangerSolid: "text-danger-foreground bg-danger hover:bg-danger/90",
  buttonSuccessSolid: "text-success-foreground bg-success hover:bg-success/90 shadow-sm",
  buttonWarningSoft: "text-warning hover:bg-warning/10",
  buttonCriticalSoft: "text-danger hover:bg-danger/10",
  buttonDetails: "h-9 px-3 rounded inline-flex items-center text-xs font-medium text-muted-foreground hover:bg-muted transition-colors",
  buttonIcon: "w-9 h-9 rounded inline-flex items-center justify-center text-muted-foreground hover:bg-muted transition-colors",
  link: "text-primary hover:text-accent",
  interactiveRow: "hover:bg-table-row-hover",
  interactiveRowStrong: "hover:bg-muted",
  focusRing: "focus:outline-none focus:ring-2 focus:ring-ring/20",
  focusRingNeutral: "focus:outline-none focus:ring-2 focus:ring-ring/20",
  focusRingCritical: "focus:outline-none focus:ring-2 focus:ring-danger/20",
  focusRingWarning: "focus:outline-none focus:ring-2 focus:ring-warning/20",
  focusRingSuccess: "focus:outline-none focus:ring-2 focus:ring-success/20",
  overlay: "bg-foreground/45",
  kbd: "border border-border bg-muted text-muted-foreground",
  chip: "bg-badge-neutral text-badge-neutral-foreground border border-border/70",
  tabActive: "bg-primary text-primary-foreground",
  tabInactive: "text-muted-foreground hover:text-foreground hover:bg-muted",
  navActive: "text-primary font-semibold",
  navInactive: "text-muted-foreground",
  codeBadge: "bg-muted text-muted-foreground",
  dividerDot: "bg-border",
  listMeta: "text-muted-foreground",
  loadTrack: "bg-muted",
  checkbox: "border-input text-primary",
  iconSubtle: "text-muted-foreground",
  iconBoxSubtle: "bg-muted text-muted-foreground",
  iconBoxEmerald: "bg-success/10 text-success",
  iconBoxActive: "bg-success/10 text-success",
  iconBoxBrand: "bg-primary/10 text-primary",
  iconBoxBlue: "bg-info/15 text-info",
  iconBoxAmber: "bg-warning/15 text-warning",
  iconBoxViolet: "bg-accent/15 text-accent",
  iconBoxSky: "bg-info/15 text-info",
  iconBoxTeal: "bg-info/15 text-info",
  infoBanner: "border border-info/25 bg-info/10 text-info",
  errorBanner: "border border-danger/25 bg-danger/10 text-danger",
  dangerPanel: "border border-danger/20 bg-danger/5",
  warningChip: "border border-warning/25 bg-warning/10 text-warning",
  sectionDivider: "border-b border-border/70",
  typePlant: "bg-primary/15 text-primary",
  typeDepartment: "bg-accent/15 text-accent",
  typeGroup: "bg-danger/15 text-danger",
  typeResource: "bg-muted text-muted-foreground",
  typeTable: "bg-info/15 text-info",
  panelCritical: "border border-danger/20 border-l-danger/60 bg-danger/5",
  panelWarning: "border border-warning/25 bg-warning/10",
  panelNeutral: "border border-border/60 bg-card",
  textCritical: "text-danger",
  textWarning: "text-warning",
  textSuccess: "text-success",
  badgeActive: "bg-success/10 text-success border border-success/20",
  badgeInactive: "bg-badge-neutral text-badge-neutral-foreground border border-border/60",
  badgeWarning: "bg-warning/10 text-warning border border-warning/25",
  badgeCritical: "bg-danger/10 text-danger border border-danger/20",
  badgeNeutral: "bg-badge-neutral text-badge-neutral-foreground border border-border/70",
  entityIconPlant: "text-entity-plant",
  entityIconLine: "text-entity-line",
  entityIconDept: "text-entity-department",
  entityIconGroup: "text-entity-resource-group",
  entityIconResource: "text-entity-resource",
  entityIconWarehouse: "text-entity-warehouse",
  entityIconProductMaster: "text-entity-product-master",
  entityIconSettings: "text-entity-settings",
  entityIconProfile: "text-entity-profile",
  entityIconRouting: "text-entity-routing",

  toolbarBg: "bg-toolbar/85",
  subCard: "bg-muted/45",
  label: "text-[10px] font-medium text-muted-foreground uppercase tracking-wide",
  labelError: "text-[10px] text-danger",
  toastSuccess: "bg-success/10 text-success border-success/20",
  toastError: "bg-danger/15 text-danger border-danger/30",
  statCard: "border border-border/70 bg-card hover:bg-muted/55",
  statCardDisabled: "border border-border/70 bg-muted/35 text-muted-foreground",
  statIcon: "bg-muted text-muted-foreground",
  tableHeader: "px-2 py-0.5 border-b border-border/70 bg-table-header text-[10px] font-semibold text-muted-foreground uppercase tracking-wide",
  tableRow: "px-2 py-1 border-b border-border/40 hover:bg-table-row-hover",
  mapPlaceholder: "flex items-center justify-center h-full bg-muted text-muted-foreground",
  overviewBadge: "bg-badge-neutral text-badge-neutral-foreground",
  statusActive: "bg-status-active text-status-active",
  statusInactive: "bg-badge-neutral text-badge-neutral-foreground",
  dividerVertical: "w-px bg-border/70",
  cardSection: "border border-border/50 bg-card shadow-sm shadow-foreground/5",
  fieldErrorBorder: "border-danger",
  selectButton: "border border-border/70 px-2 py-0.5 rounded bg-card",
  plantCode: "rounded px-1.5 py-0.5 text-[10px] font-mono font-medium bg-muted text-muted-foreground",
  entityIconBg: "bg-muted",
  surfaceBg: "bg-card",
  textInverse: "text-muted-foreground hover:text-foreground",

  toolbarBtn: "inline-flex h-8 items-center gap-2 px-2 py-1 text-xs font-medium text-muted-foreground select-none transition-all duration-150 bg-transparent hover:bg-accent/10 active:bg-accent/20 disabled:pointer-events-none disabled:opacity-50",
  toolbarBtnPrimary: "inline-flex h-8 items-center gap-2 px-2 py-1 text-xs font-semibold select-none transition-all duration-150 bg-primary text-primary-foreground hover:bg-accent active:brightness-90 disabled:pointer-events-none disabled:opacity-40",
  toolbarBtnSuccess: "inline-flex h-8 items-center gap-2 px-2 py-1 text-xs font-semibold select-none transition-all duration-150 bg-success text-success-foreground hover:bg-success/90 active:brightness-90 disabled:pointer-events-none disabled:opacity-40",
};
