"""Domain constants for the maintenance app."""

APPROVED_TARGET_TYPES = ["PLANT", "PRODUCTION_LINE", "DEPARTMENT", "RESOURCE_GROUP", "RESOURCE"]

# ── Work Order Types ──
WORK_ORDER_TYPE_PREVENTIVE = "PREVENTIVE"
WORK_ORDER_TYPE_CORRECTIVE = "CORRECTIVE"
WORK_ORDER_TYPE_BREAKDOWN = "BREAKDOWN"
WORK_ORDER_TYPE_INSPECTION = "INSPECTION"
WORK_ORDER_TYPE_CALIBRATION = "CALIBRATION"
WORK_ORDER_TYPE_IMPROVEMENT = "IMPROVEMENT"
WORK_ORDER_TYPE_SAFETY = "SAFETY"
WORK_ORDER_TYPE_TOOLING = "TOOLING"
WORK_ORDER_TYPE_OTHER = "OTHER"

WORK_ORDER_TYPE_CHOICES = [
    (WORK_ORDER_TYPE_CORRECTIVE, "Corrective"),
    (WORK_ORDER_TYPE_PREVENTIVE, "Preventive"),
    (WORK_ORDER_TYPE_BREAKDOWN, "Breakdown"),
    (WORK_ORDER_TYPE_INSPECTION, "Inspection"),
    (WORK_ORDER_TYPE_CALIBRATION, "Calibration"),
    (WORK_ORDER_TYPE_IMPROVEMENT, "Improvement"),
    (WORK_ORDER_TYPE_SAFETY, "Safety"),
    (WORK_ORDER_TYPE_TOOLING, "Tooling"),
    (WORK_ORDER_TYPE_OTHER, "Other"),
]

# ── Work Order Statuses ──
WORK_ORDER_STATUS_DRAFT = "DRAFT"
WORK_ORDER_STATUS_OPEN = "OPEN"
WORK_ORDER_STATUS_ASSIGNED = "ASSIGNED"
WORK_ORDER_STATUS_IN_PROGRESS = "IN_PROGRESS"
WORK_ORDER_STATUS_WAITING_PARTS = "WAITING_PARTS"
WORK_ORDER_STATUS_WAITING_APPROVAL = "WAITING_APPROVAL"
WORK_ORDER_STATUS_COMPLETED = "COMPLETED"
WORK_ORDER_STATUS_CANCELLED = "CANCELLED"
WORK_ORDER_STATUS_ARCHIVED = "ARCHIVED"

WORK_ORDER_STATUS_CHOICES = [
    (WORK_ORDER_STATUS_DRAFT, "Draft"),
    (WORK_ORDER_STATUS_OPEN, "Open"),
    (WORK_ORDER_STATUS_ASSIGNED, "Assigned"),
    (WORK_ORDER_STATUS_IN_PROGRESS, "In Progress"),
    (WORK_ORDER_STATUS_WAITING_PARTS, "Waiting Parts"),
    (WORK_ORDER_STATUS_WAITING_APPROVAL, "Waiting Approval"),
    (WORK_ORDER_STATUS_COMPLETED, "Completed"),
    (WORK_ORDER_STATUS_CANCELLED, "Cancelled"),
    (WORK_ORDER_STATUS_ARCHIVED, "Archived"),
]

WORK_ORDER_ACTIVE_STATUSES = [
    WORK_ORDER_STATUS_DRAFT,
    WORK_ORDER_STATUS_OPEN,
    WORK_ORDER_STATUS_ASSIGNED,
    WORK_ORDER_STATUS_IN_PROGRESS,
    WORK_ORDER_STATUS_WAITING_PARTS,
    WORK_ORDER_STATUS_WAITING_APPROVAL,
]

# ── Work Order Priority ──
WORK_ORDER_PRIORITY_LOW = "LOW"
WORK_ORDER_PRIORITY_MEDIUM = "MEDIUM"
WORK_ORDER_PRIORITY_HIGH = "HIGH"
WORK_ORDER_PRIORITY_CRITICAL = "CRITICAL"

WORK_ORDER_PRIORITY_CHOICES = [
    (WORK_ORDER_PRIORITY_LOW, "Low"),
    (WORK_ORDER_PRIORITY_MEDIUM, "Medium"),
    (WORK_ORDER_PRIORITY_HIGH, "High"),
    (WORK_ORDER_PRIORITY_CRITICAL, "Critical"),
]

# ── Preventive Maintenance ──
PM_FREQUENCY_DAILY = "DAILY"
PM_FREQUENCY_WEEKLY = "WEEKLY"
PM_FREQUENCY_MONTHLY = "MONTHLY"
PM_FREQUENCY_QUARTERLY = "QUARTERLY"
PM_FREQUENCY_YEARLY = "YEARLY"
PM_FREQUENCY_USAGE_BASED = "USAGE_BASED"

PM_FREQUENCY_CHOICES = [
    (PM_FREQUENCY_DAILY, "Daily"),
    (PM_FREQUENCY_WEEKLY, "Weekly"),
    (PM_FREQUENCY_MONTHLY, "Monthly"),
    (PM_FREQUENCY_QUARTERLY, "Quarterly"),
    (PM_FREQUENCY_YEARLY, "Yearly"),
    (PM_FREQUENCY_USAGE_BASED, "Usage Based"),
]

PM_STATUS_ACTIVE = "ACTIVE"
PM_STATUS_PAUSED = "PAUSED"
PM_STATUS_ARCHIVED = "ARCHIVED"

PM_STATUS_CHOICES = [
    (PM_STATUS_ACTIVE, "Active"),
    (PM_STATUS_PAUSED, "Paused"),
    (PM_STATUS_ARCHIVED, "Archived"),
]

# ── Breakdown ──
BREAKDOWN_SEVERITY_LOW = "LOW"
BREAKDOWN_SEVERITY_MEDIUM = "MEDIUM"
BREAKDOWN_SEVERITY_HIGH = "HIGH"
BREAKDOWN_SEVERITY_CRITICAL = "CRITICAL"

BREAKDOWN_SEVERITY_CHOICES = [
    (BREAKDOWN_SEVERITY_LOW, "Low"),
    (BREAKDOWN_SEVERITY_MEDIUM, "Medium"),
    (BREAKDOWN_SEVERITY_HIGH, "High"),
    (BREAKDOWN_SEVERITY_CRITICAL, "Critical"),
]

BREAKDOWN_STATUS_REPORTED = "REPORTED"
BREAKDOWN_STATUS_UNDER_REPAIR = "UNDER_REPAIR"
BREAKDOWN_STATUS_REPAIRED = "REPAIRED"
BREAKDOWN_STATUS_CLOSED = "CLOSED"
BREAKDOWN_STATUS_CANCELLED = "CANCELLED"

BREAKDOWN_STATUS_CHOICES = [
    (BREAKDOWN_STATUS_REPORTED, "Reported"),
    (BREAKDOWN_STATUS_UNDER_REPAIR, "Under Repair"),
    (BREAKDOWN_STATUS_REPAIRED, "Repaired"),
    (BREAKDOWN_STATUS_CLOSED, "Closed"),
    (BREAKDOWN_STATUS_CANCELLED, "Cancelled"),
]

# ── Spare Part ──
SPARE_PART_STATUS_ACTIVE = "ACTIVE"
SPARE_PART_STATUS_INACTIVE = "INACTIVE"
SPARE_PART_STATUS_OBSOLETE = "OBSOLETE"

SPARE_PART_STATUS_CHOICES = [
    (SPARE_PART_STATUS_ACTIVE, "Active"),
    (SPARE_PART_STATUS_INACTIVE, "Inactive"),
    (SPARE_PART_STATUS_OBSOLETE, "Obsolete"),
]
