f = open("D:/02_Work/localai/lmd/frontend/src/pages/improve/SuggestionsPage.tsx").read()
f = f.replace('className="px-4"', 'className="px-4 py-3"')
f = f.replace('className="flex-1"', 'className="flex-1 py-3"')
open("D:/02_Work/localai/lmd/frontend/src/pages/improve/SuggestionsPage.tsx", "w").write(f)
print("Done")
print("Braces:", f.count("{") == f.count("}"))
print("Parens:", f.count("(") == f.count(")"))
