# Generated by Django 6.0.5 on 2026-06-02 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('target_type', models.CharField(max_length=100)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('UNDER_REPAIR', 'Under Repair'), ('REPAIRED', 'Repaired'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='REPORTED', max_length=30)),
                ('reported_by', models.CharField(blank=True, default='', max_length=255)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('repair_started_at', models.DateTimeField(blank=True, null=True)),
                ('repair_completed_at', models.DateTimeField(blank=True, null=True)),
                ('downtime_minutes', models.IntegerField(blank=True, null=True)),
                ('root_cause', models.TextField(blank=True, default='')),
                ('repair_summary', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PreventiveMaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(blank=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('target_type', models.CharField(max_length=100)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly'), ('USAGE_BASED', 'Usage Based')], max_length=30)),
                ('interval_value', models.IntegerField(blank=True, help_text='Number of days/cycles between PM executions', null=True)),
                ('next_due_date', models.DateField(blank=True, null=True)),
                ('last_completed_date', models.DateField(blank=True, null=True)),
                ('assigned_to', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PAUSED', 'Paused'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=30)),
                ('checklist_json', models.JSONField(blank=True, help_text='JSON array of checklist items', null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part_number', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('uom', models.CharField(blank=True, default='', max_length=50)),
                ('min_quantity', models.IntegerField(default=0)),
                ('quantity_on_hand', models.IntegerField(default=0)),
                ('storage_location', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('OBSOLETE', 'Obsolete')], default='ACTIVE', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceWorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(blank=True, max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('work_order_type', models.CharField(choices=[('PREVENTIVE', 'Preventive'), ('CORRECTIVE', 'Corrective'), ('BREAKDOWN', 'Breakdown'), ('INSPECTION', 'Inspection'), ('OTHER', 'Other')], max_length=30)),
                ('target_type', models.CharField(max_length=100)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=30)),
                ('requested_by', models.CharField(blank=True, default='', max_length=255)),
                ('assigned_to', models.CharField(blank=True, default='', max_length=255)),
                ('planned_start_date', models.DateTimeField(blank=True, null=True)),
                ('planned_end_date', models.DateTimeField(blank=True, null=True)),
                ('actual_start_date', models.DateTimeField(blank=True, null=True)),
                ('actual_end_date', models.DateTimeField(blank=True, null=True)),
                ('downtime_minutes', models.IntegerField(blank=True, null=True)),
                ('completion_notes', models.TextField(blank=True, default='')),
                ('linked_breakdown', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='maintenance.breakdown')),
                ('linked_pm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='maintenance.preventivemaintenanceplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='breakdown',
            name='linked_work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='originating_breakdowns', to='maintenance.maintenanceworkorder'),
        ),
        migrations.CreateModel(
            name='SparePartUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.IntegerField()),
                ('used_by', models.CharField(blank=True, default='', max_length=255)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usages', to='maintenance.sparepart')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spare_part_usages', to='maintenance.maintenanceworkorder')),
            ],
            options={
                'ordering': ['-used_at'],
            },
        ),
    ]
