# Generated by Django 6.0.5 on 2026-06-07 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_maintenanceworkorder_linked_mer'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceworkorder',
            name='attachments',
            field=models.JSONField(blank=True, help_text='JSON array of attachment metadata', null=True),
        ),
        migrations.AddField(
            model_name='maintenanceworkorder',
            name='corrective_action',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='maintenanceworkorder',
            name='date_opened',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceworkorder',
            name='department_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceworkorder',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceworkorder',
            name='failure_mode',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='maintenanceworkorder',
            name='labor_estimate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceworkorder',
            name='plant_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceworkorder',
            name='production_line_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceworkorder',
            name='resource_group_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceworkorder',
            name='resource_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceworkorder',
            name='root_cause',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='maintenanceworkorder',
            name='safety_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='maintenanceworkorder',
            name='spare_parts_required',
            field=models.JSONField(blank=True, help_text='JSON array of required spare parts', null=True),
        ),
        migrations.AddField(
            model_name='maintenanceworkorder',
            name='verification_result',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='maintenanceworkorder',
            name='work_instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='maintenanceworkorder',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('ASSIGNED', 'Assigned'), ('IN_PROGRESS', 'In Progress'), ('WAITING_PARTS', 'Waiting Parts'), ('WAITING_APPROVAL', 'Waiting Approval'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=30),
        ),
        migrations.AlterField(
            model_name='maintenanceworkorder',
            name='target_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='maintenanceworkorder',
            name='work_order_type',
            field=models.CharField(choices=[('CORRECTIVE', 'Corrective'), ('PREVENTIVE', 'Preventive'), ('BREAKDOWN', 'Breakdown'), ('INSPECTION', 'Inspection'), ('CALIBRATION', 'Calibration'), ('IMPROVEMENT', 'Improvement'), ('SAFETY', 'Safety'), ('TOOLING', 'Tooling'), ('OTHER', 'Other')], max_length=30),
        ),
    ]
