# Generated by Django 6.0.5 on 2026-06-07 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_maintenanceworkorder_attachments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventivemaintenanceplan',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='preventivemaintenanceplan',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20),
        ),
    ]
