# Generated by Django 6.0.5 on 2026-06-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_preventivemaintenanceplan_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='manufacturer',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='supplier',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
