# Generated by Django 6.0.4 on 2026-06-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_sparepart_manufacturer_sparepart_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakdown',
            name='assigned_to',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='breakdown',
            name='completion_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='breakdown',
            name='confirmed_root_cause',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='breakdown',
            name='corrective_action',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='breakdown',
            name='downtime_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breakdown',
            name='downtime_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breakdown',
            name='failure_mode',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='breakdown',
            name='is_equipment_down',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='breakdown',
            name='parts_required',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='breakdown',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='breakdown',
            name='production_impact',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='breakdown',
            name='repair_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='breakdown',
            name='safety_impact',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='breakdown',
            name='suspected_cause',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='breakdown',
            name='temporary_containment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='breakdown',
            name='verification_result',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='maintenanceworkorder',
            name='actual_labor_hours',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='maintenanceworkorder',
            name='parts_used_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='maintenanceworkorder',
            name='required_tools',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='maintenanceworkorder',
            name='work_performed',
            field=models.TextField(blank=True, default=''),
        ),
    ]
