from django.core.management.base import BaseCommand
from manufacturing.models.config_option import ConfigOption

OPTIONS = {
    "industry_type": [
        ("automotive", "Automotive"),
        ("aerospace", "Aerospace"),
        ("electronics", "Electronics & Semiconductors"),
        ("medical_devices", "Medical Devices"),
        ("food_manufacturing", "Food & Beverage"),
        ("chemical", "Chemical Processing"),
        ("pharmaceutical", "Pharmaceutical"),
        ("machinery", "Machinery & Equipment"),
        ("metalworking", "Metal Fabrication"),
        ("plastics", "Plastics & Rubber"),
        ("textile", "Textile & Apparel"),
        ("paper", "Pulp & Paper"),
        ("energy", "Energy & Utilities"),
        ("logistics", "Logistics & Distribution"),
        ("defense", "Aerospace & Defense"),
        ("consumer_goods", "Consumer Packaged Goods"),
    ],
    "manufacturing_type": [
        ("discrete", "Discrete Manufacturing"),
        ("process", "Process Manufacturing"),
        ("assembly", "Assembly"),
        ("mixed_model", "Mixed Model Manufacturing"),
        ("job_shop", "Job Shop"),
        ("repetitive", "Repetitive Manufacturing"),
        ("batch", "Batch Processing"),
        ("continuous", "Continuous Flow"),
        ("make_to_order", "Make to Order (MTO)"),
        ("make_to_stock", "Make to Stock (MTS)"),
        ("engineer_to_order", "Engineer to Order (ETO)"),
        ("assemble_to_order", "Assemble to Order (ATO)"),
    ],
    "shift_model": [
        ("1_shift", "1 Shift (Day — 8hr)"),
        ("2_shift", "2 Shift (Morn/Aftn — 16hr)"),
        ("3_shift", "3 Shift (Continuous — 24hr)"),
        ("24_7", "24/7 Rotating (Panama)"),
        ("24_7_dupont", "24/7 DuPont (12hr Rotating)"),
        ("continental", "Continental (12hr Shift)"),
        ("flexible", "Flexible / Custom"),
        ("split", "Split Shift"),
        ("weekend", "Weekend Shift (Fri-Sun)"),
    ],
    "units": [
        ("metric", "Metric (mm, kg, °C)"),
        ("imperial", "Imperial (in, lb, °F)"),
        ("both", "Dual (Metric / Imperial)"),
    ],
    "lean_methodology": [
        ("lean", "Lean Manufacturing"),
        ("tps", "TPS (Toyota Production System)"),
        ("six_sigma", "Six Sigma (DMAIC)"),
        ("lean_six_sigma", "Lean Six Sigma"),
        ("kaizen", "Kaizen (Continuous Improvement)"),
        ("kaizen_blitz", "Kaizen Blitz / Rapid Improvement"),
        ("theory_of_constraints", "Theory of Constraints (TOC)"),
        ("just_in_time", "Just-in-Time (JIT)"),
        ("kanban", "Kanban / Pull System"),
        ("heijunka", "Heijunka (Production Leveling)"),
        ("jidoka", "Jidoka (Autonomation)"),
        ("poka_yoke", "Poka-Yoke (Mistake Proofing)"),
        ("tpm", "Total Productive Maintenance (TPM)"),
        ("sm_ed", "SMED (Single-Minute Exchange of Dies)"),
        ("vsm", "Value Stream Mapping (VSM)"),
        ("5s", "5S (Sort, Set, Shine, Standardize, Sustain)"),
        ("agile", "Agile Manufacturing"),
        ("demand_flow", "Demand Flow Technology"),
    ],
    "language": [
        ("en", "English"),
        ("es", "Spanish"),
        ("fr", "French"),
        ("de", "German"),
        ("it", "Italian"),
        ("ja", "Japanese"),
        ("zh", "Chinese (Simplified)"),
        ("zh_tw", "Chinese (Traditional)"),
        ("ko", "Korean"),
        ("pt", "Portuguese"),
        ("pl", "Polish"),
        ("cs", "Czech"),
        ("tr", "Turkish"),
        ("nl", "Dutch"),
        ("sv", "Swedish"),
        ("vi", "Vietnamese"),
        ("th", "Thai"),
    ],
    "timezone": [
        ("UTC", "UTC (Coordinated Universal Time)"),
        ("America/New_York", "Eastern (EST/EDT) — New York"),
        ("America/Chicago", "Central (CST/CDT) — Chicago"),
        ("America/Denver", "Mountain (MST/MDT) — Denver"),
        ("America/Los_Angeles", "Pacific (PST/PDT) — Los Angeles"),
        ("America/Detroit", "Eastern (EST) — Detroit / Michigan"),
        ("America/Mexico_City", "Central — Mexico City"),
        ("America/Monterrey", "Central — Monterrey"),
        ("America/Tijuana", "Pacific — Tijuana"),
        ("America/Toronto", "Eastern — Toronto"),
        ("America/Sao_Paulo", "Brasilia — São Paulo"),
        ("Europe/London", "GMT/BST — London"),
        ("Europe/Berlin", "CET/CEST — Berlin"),
        ("Europe/Paris", "CET/CEST — Paris"),
        ("Europe/Madrid", "CET/CEST — Madrid"),
        ("Europe/Rome", "CET/CEST — Rome"),
        ("Europe/Prague", "CET/CEST — Prague"),
        ("Europe/Warsaw", "CET/CEST — Warsaw"),
        ("Europe/Istanbul", "TRT — Istanbul"),
        ("Asia/Tokyo", "JST — Tokyo"),
        ("Asia/Shanghai", "CST — Shanghai"),
        ("Asia/Seoul", "KST — Seoul"),
        ("Asia/Bangkok", "ICT — Bangkok"),
        ("Asia/Ho_Chi_Minh", "ICT — Ho Chi Minh"),
        ("Asia/Dubai", "GST — Dubai"),
        ("Asia/Kolkata", "IST — India"),
        ("Australia/Sydney", "AEDT/AEST — Sydney"),
    ],
    "calendar": [
        ("standard_5day", "Standard 5-Day Week (Mon-Fri)"),
        ("standard_6day", "Standard 6-Day Week (Mon-Sat)"),
        ("4day_10hr", "4-Day / 10-Hour Work Week"),
        ("continental", "Continental Shift Pattern"),
        ("continental_12hr", "Continental 12-Hour Rotating"),
        ("panama", "Panama Schedule (2-2-3)"),
        ("dupont_12hr", "DuPont 12-Hour Rotating"),
        ("weekend_double", "Weekend Double (Fri-Sat-Sun)"),
        ("custom", "Custom Calendar"),
    ],
}


class Command(BaseCommand):
    help = "Seed organization configuration options"

    def handle(self, *args, **options):
        created = 0
        for category, items in OPTIONS.items():
            for order, (value, label) in enumerate(items):
                obj, is_new = ConfigOption.objects.get_or_create(
                    category=category, value=value,
                    defaults={"label": label, "sort_order": order},
                )
                if is_new:
                    created += 1
        self.stdout.write(self.style.SUCCESS(f"Seeded {created} new config options"))
