from django.core.management.base import BaseCommand
from manufacturing.models.reference_item import ReferenceItem

SEED_DATA = {
    "production_calendar": [
        ("STD5", "Standard 5-Day", "Monday to Friday, 8-hour work days. 40-hour standard work week with weekends off.", 10),
        ("STD6", "Standard 6-Day", "Monday to Saturday, 8-hour work days. 48-hour work week for high-demand periods.", 20),
        ("4X10", "4-Day / 10-Hour", "Four 10-hour days (Mon-Thu) with three-day weekends. Common compressed work week.", 30),
        ("CONT", "Continental", "Continental 12-hour rotating shift calendar. 7-day coverage with 2-2-3 rotation pattern.", 40),
        ("DUP12", "DuPont 12-Hour", "DuPont 12-hour rotating shift schedule. 4 crews, 12-hour shifts, 7-day coverage cycle.", 50),
        ("24-7", "24/7 Continuous", "Round-the-clock continuous operations. 365-day calendar with rotating shift crews.", 60),
        ("PANAMA", "Panama Schedule", "2-2-3 rotating Panama schedule. 12-hour shifts with 2 days on, 2 off, 3 on rotation.", 70),
        ("SEASON", "Seasonal Calendar", "Flexible work calendar for seasonal production peaks. Adjusts hours based on demand.", 80),
        ("HOLIDAY", "Holiday Reduced", "Reduced operations calendar for holiday periods. Minimum staffing for essential processes.", 90),
        ("SHUTDOWN", "Shutdown Calendar", "Plant shutdown calendar for annual maintenance, retooling, and facility upgrades.", 100),
    ],
    "shift_pattern": [
        ("1SH-D", "1 Shift (Day)", "Single day shift, 8 hours. Standard 06:00-14:00 or 07:00-15:00 schedule.", 10),
        ("1SH-N", "1 Shift (Night)", "Single night shift, 8 hours. Typically 22:00-06:00 schedule.", 15),
        ("2SH-MA", "2 Shift (Morn/Aftn)", "Morning and afternoon shifts. Two shifts covering 06:00-22:00.", 20),
        ("2SH-MN", "2 Shift (Day/Night)", "Day and night shifts. Two 12-hour shifts covering 24 hours.", 25),
        ("3SH-C", "3 Shift (Continuous)", "Three 8-hour shifts providing continuous 24-hour coverage with rotation.", 30),
        ("247-PAN", "24/7 Panama", "2-2-3 rotating Panama schedule. 12-hour shifts with crew rotation.", 40),
        ("247-DUP", "24/7 DuPont", "12-hour DuPont rotating schedule. 4 crews rotating through day/night shifts.", 50),
        ("SPLIT", "Split Shift", "Split shift pattern with break between segments. Common in service operations.", 55),
        ("FLEX", "Flexible / Custom", "Flexible start/end times. Core hours 09:00-15:00 with flexible arrival/departure.", 60),
        ("WEEKEND", "Weekend Shift", "Weekend-only shift (Fri-Sun or Sat-Sun). Premium pay, 12-hour or 8-hour options.", 70),
        ("3SH-ROT", "3 Shift Rotating", "Three rotating 8-hour shifts with weekly rotation. Common in process industries.", 75),
        ("12HR-BLOCK", "12-Hour Block", "Block schedule: 3-4 days on, 3-4 days off. 12-hour shifts, alternating crews.", 80),
    ],
    "language": [
        ("en", "English", "English language for interfaces, documentation, and communication.", 10),
        ("es", "Spanish", "Spanish language for Latin American operations and bilingual workforces.", 20),
        ("fr", "French", "French language for European, Canadian, and African operations.", 30),
        ("de", "German", "German language for DACH region operations and technical documentation.", 40),
        ("it", "Italian", "Italian language for operations and technical documentation.", 45),
        ("ja", "Japanese", "Japanese language for Toyota Production System reference and Japan operations.", 50),
        ("zh", "Chinese (Simplified)", "Simplified Chinese for China-based manufacturing operations.", 60),
        ("ko", "Korean", "Korean language for Korea-based operations and technical documentation.", 65),
        ("pt", "Portuguese", "Portuguese language for Brazilian and Portuguese operations.", 70),
        ("nl", "Dutch", "Dutch language for Netherlands-based operations.", 72),
        ("sv", "Swedish", "Swedish language for Scandinavian operations.", 74),
        ("pl", "Polish", "Polish language for Central European operations.", 76),
        ("cs", "Czech", "Czech language for Central European operations.", 78),
        ("tr", "Turkish", "Turkish language for Turkey-based operations.", 80),
        ("th", "Thai", "Thai language for Southeast Asian operations.", 82),
        ("vi", "Vietnamese", "Vietnamese language for Southeast Asian operations.", 84),
        ("ar", "Arabic", "Arabic language for Middle East and North African operations.", 86),
    ],
    "timezone": [
        ("UTC", "UTC", "Coordinated Universal Time. Base reference for all timezone calculations.", 5),
        ("GMT", "GMT/BST", "United Kingdom timezone. GMT in winter, BST (UTC+1) in summer.", 10),
        ("CET", "CET/CEST", "Central European Time. CET (UTC+1) winter, CEST (UTC+2) summer.", 15),
        ("EET", "EET/EEST", "Eastern European Time. EET (UTC+2) winter, EEST (UTC+3) summer.", 18),
        ("MSK", "MSK", "Moscow Time (UTC+3). No daylight saving.", 19),
        ("GST", "GST", "Gulf Standard Time (UTC+4). UAE, Oman. No daylight saving.", 20),
        ("PKT", "PKT", "Pakistan Standard Time (UTC+5).", 21),
        ("IST", "IST", "India Standard Time (UTC+5:30). No daylight saving.", 22),
        ("BNG", "BST/BGT", "Bangladesh Standard Time (UTC+6).", 23),
        ("ICT", "ICT", "Indochina Time (UTC+7). Thailand, Vietnam, Cambodia.", 24),
        ("CST", "CST (China)", "China Standard Time (UTC+8). Single timezone for all of China.", 25),
        ("JST", "JST", "Japan Standard Time (UTC+9). No daylight saving.", 26),
        ("KST", "KST", "Korea Standard Time (UTC+9).", 27),
        ("EST", "Eastern (EST/EDT)", "Eastern US timezone. EST (UTC-5) winter, EDT (UTC-4) summer.", 30),
        ("CST", "Central (CST/CDT)", "Central US timezone. CST (UTC-6) winter, CDT (UTC-5) summer.", 35),
        ("MST", "Mountain (MST/MDT)", "Mountain US timezone. MST (UTC-7) winter, MDT (UTC-6) summer.", 40),
        ("PST", "Pacific (PST/PDT)", "Pacific US timezone. PST (UTC-8) winter, PDT (UTC-7) summer.", 45),
        ("AKST", "Alaska (AKST/AKDT)", "Alaska timezone. AKST (UTC-9) winter, AKDT (UTC-8) summer.", 50),
        ("HAST", "Hawaii (HAST/HADT)", "Hawaii timezone. HAST (UTC-10) winter, HADT (UTC-9) summer.", 55),
        ("BRT", "Brasilia (BRT/BRST)", "Brasilia Time. BRT (UTC-3) winter, BRST (UTC-2) summer.", 60),
        ("ART", "Argentina (ART)", "Argentina Time (UTC-3). No daylight saving.", 62),
        ("CLT", "Chile (CLT/CLST)", "Chile Standard Time. CLT (UTC-4) winter, CLST (UTC-3) summer.", 64),
        ("NST", "Newfoundland (NST/NDT)", "Newfoundland Time. NST (UTC-3:30) winter, NDT (UTC-2:30) summer.", 66),
        ("AST", "Atlantic (AST/ADT)", "Atlantic Canada timezone. AST (UTC-4) winter, ADT (UTC-3) summer.", 68),
        ("AEST", "AEST/AEDT", "Australian Eastern Time. AEST (UTC+10) winter, AEDT (UTC+11) summer.", 70),
        ("ACST", "ACST/ACDT", "Australian Central Time. ACST (UTC+9:30) winter, ACDT (UTC+10:30) summer.", 72),
        ("AWST", "AWST", "Australian Western Standard Time (UTC+8). No daylight saving.", 74),
        ("NZST", "NZST/NZDT", "New Zealand Time. NZST (UTC+12) winter, NZDT (UTC+13) summer.", 76),
        ("FJT", "FJT", "Fiji Time (UTC+12). Occasionally observes daylight saving.", 78),
    ],
    "manufacturing_type": [
        ("DISC", "Discrete Manufacturing", "Individual unit production of distinct items. Cars, appliances, electronics assembly.", 10),
        ("PROC", "Process Manufacturing", "Continuous or batch production of materials. Chemicals, food, beverages, pharmaceuticals.", 20),
        ("ASSY", "Assembly", "Component assembly operations combining multiple parts into finished products.", 25),
        ("MIXED", "Mixed Model", "Multiple product variants produced on the same production line with quick changeover.", 30),
        ("MTO", "Make to Order", "Production triggered by confirmed customer orders. Minimal finished goods inventory.", 40),
        ("MTS", "Make to Stock", "Production for inventory replenishment based on demand forecasts.", 45),
        ("ETO", "Engineer to Order", "Custom engineered products designed and manufactured to customer specifications.", 50),
        ("CTO", "Configure to Order", "Standard product with customer-selected options configured at time of order.", 55),
        ("JOB", "Job Shop", "Low volume, high variety production. Job shops produce custom parts in small batches.", 60),
        ("BATCH", "Batch Processing", "Production in discrete batches or lots. Common in food, pharmaceutical, and chemical industries.", 65),
        ("CELL", "Cellular Manufacturing", "Lean cell layout grouping dissimilar machines for family-of-parts production.", 70),
        ("FLOW", "One-Piece Flow", "Continuous flow manufacturing. Single piece flow with zero work-in-process between operations.", 75),
        ("REP", "Repetitive Manufacturing", "High-volume, dedicated production of identical or similar products on dedicated lines.", 80),
        ("FLEX", "Flexible Manufacturing", "Computer-controlled manufacturing system capable of producing a variety of parts with minimal changeover.", 85),
    ],
    "work_center_type": [
        ("MANUAL", "Manual Workstation", "Operator-based manual work. Hand assembly, manual machining, or manual inspection station.", 10),
        ("SEMI", "Semi-Automatic", "Operator-assisted automatic work. Machine loads/unloads with operator oversight.", 20),
        ("AUTO", "Automatic Cell", "Fully automatic production cell. Robotic loading, machining, and unloading with minimal operator intervention.", 30),
        ("ASSY", "Assembly Line", "Progressive assembly line with sequential workstations. Conveyor or palletized transport.", 40),
        ("CELL", "Manufacturing Cell", "U-shaped or L-shaped cell grouping multiple process steps for one-piece flow.", 45),
        ("LINE", "Transfer Line", "Automated transfer line with sequential machining stations. High volume, dedicated part families.", 50),
        ("TEST", "Testing Station", "Quality testing and validation station. Functional test, leak test, or performance verification.", 55),
        ("INSP", "Inspection Station", "Dedicated quality inspection station. Dimensional, visual, or NDT inspection.", 57),
        ("WELD", "Welding Cell", "Dedicated welding workstation with robotic or manual welding equipment.", 60),
        ("PAINT", "Painting / Coating", "Painting, powder coating, or surface treatment workstation. Includes spray booth or dip tank.", 65),
        ("FINI", "Finishing Station", "Final finishing operations: deburring, polishing, grinding, surface treatment.", 70),
        ("PACK", "Packaging Station", "Final packaging workstation. Boxing, wrapping, palletizing, and labeling.", 75),
        ("CLEAN", "Clean Room", "Controlled environment workstation for sensitive assembly or processing.", 80),
        ("FURN", "Furnace / Oven", "Heat treatment workstation. Furnace, oven, or kiln for thermal processing.", 85),
        ("PLATE", "Plating Line", "Electroplating or chemical treatment line. Surface finishing operations.", 90),
    ],
    "machine_type": [
        ("CNC", "CNC Machine", "Computer Numerical Control machine. Multi-axis machining center for precision milling and drilling.", 10),
        ("LATHE", "Lathe", "Engine lathe or CNC turning center for cylindrical part machining.", 15),
        ("MILL", "Milling Machine", "Manual or CNC milling machine for flat surface and slot machining.", 16),
        ("PRESS", "Press", "Hydraulic or mechanical press for stamping, forming, bending, and assembly operations.", 20),
        ("ROBO", "Robot", "Industrial robot arm for material handling, welding, assembly, or palletizing.", 30),
        ("CONV", "Conveyor", "Conveyor system for material transport between workstations or production lines.", 40),
        ("INJECT", "Injection Molder", "Plastic injection molding machine for producing plastic parts and components.", 50),
        ("WELD", "Welder", "Welding equipment including MIG, TIG, spot, and laser welding systems.", 60),
        ("LASER", "Laser Cutter", "Laser cutting machine for precision cutting of sheet metal and plate.", 63),
        ("PLASMA", "Plasma Cutter", "Plasma cutting machine for thick plate steel and structural cutting.", 64),
        ("WTRJET", "Water Jet", "Water jet cutting machine for cold cutting of various materials without heat-affected zone.", 65),
        ("OVEN", "Oven / Furnace", "Industrial oven or furnace for heat treatment, drying, or curing processes.", 70),
        ("PUMP", "Pump", "Fluid or air pump system for process fluid handling, coolant, or hydraulic systems.", 80),
        ("CMM", "CMM", "Coordinate Measuring Machine for precision dimensional inspection of parts.", 82),
        ("EDM", "EDM Machine", "Electrical Discharge Machine for precision machining of hard metals and complex shapes.", 84),
        ("GRIND", "Grinder", "Surface grinder, cylindrical grinder, or centerless grinder for precision finishing.", 86),
        ("SAW", "Saw", "Band saw, circular saw, or cut-off saw for material cutting and sizing.", 88),
        ("SCALE", "Scale / Weigh Station", "Industrial weighing scale or check-weigher for weight verification.", 90),
        ("MOLD", "Molding Machine", "General molding equipment including compression, blow, and rotational molding.", 92),
        ("EXTRU", "Extruder", "Plastic or metal extrusion machine for continuous profile production.", 94),
        ("MIXER", "Mixer / Blender", "Industrial mixer, blender, or agitator for material blending and compounding.", 96),
        ("DRYER", "Dryer", "Industrial drying equipment for moisture removal from products or materials.", 97),
        ("CHILL", "Chiller", "Industrial chiller for process cooling or temperature control.", 98),
        ("COMP", "Compressor", "Air compressor for pneumatic systems, tools, and process air supply.", 99),
        ("BOIL", "Boiler", "Industrial boiler for steam generation and process heating.", 100),
        ("AGV", "AGV", "Automated Guided Vehicle for autonomous material transport and delivery.", 105),
        ("ASRS", "AS/RS", "Automated Storage and Retrieval System for high-density automated warehousing.", 110),
        ("PACKR", "Packaging Robot", "Robotic packaging system for case packing, palletizing, and stretch wrapping.", 115),
    ],
    "operation_code": [
        ("RECV", "Receiving", "Incoming material receipt, verification, and documentation.", 5),
        ("STORE", "Storage / Put-away", "Material put-away to designated storage locations.", 8),
        ("PICK", "Picking", "Order picking and kitting of materials for production.", 10),
        ("KITT", "Kitting", "Assembly of component kits for production orders.", 12),
        ("CUT", "Cutting", "Material cutting operation to rough size or shape.", 15),
        ("SAW", "Saw Cutting", "Operation using saw equipment for material sizing and cutting.", 16),
        ("TURN", "Turning", "Lathe turning operation for cylindrical features.", 20),
        ("DRILL", "Drilling", "Drilling operation for hole creation and tapping preparation.", 25),
        ("TAP", "Tapping", "Internal thread cutting operation following drilling.", 26),
        ("REAM", "Reaming", "Precision hole finishing operation for tight tolerances.", 27),
        ("BORE", "Boring", "Internal diameter machining operation for precision hole finishing.", 28),
        ("MILL", "Milling", "Milling operation for flat surfaces, slots, pockets, and contours.", 30),
        ("GRIND", "Grinding", "Surface grinding or cylindrical grinding operation for precision finishing.", 35),
        ("HONE", "Honing", "Precision surface finishing operation for ultra-smooth surfaces.", 36),
        ("LAP", "Lapping", "Ultra-precision flat surface finishing operation.", 37),
        ("DEBUR", "Deburring", "Deburring and edge finishing operation to remove sharp edges.", 38),
        ("HEAT", "Heat Treatment", "Heat treatment operation including annealing, quenching, and tempering.", 40),
        ("ANNEAL", "Annealing", "Controlled heating and cooling to soften material and relieve stress.", 41),
        ("PLATE", "Plating / Coating", "Surface plating, coating, or anodizing operation.", 45),
        ("PAINT", "Painting", "Painting, powder coating, or surface finishing operation.", 50),
        ("WELD", "Welding", "Welding operation for joining metal components.", 55),
        ("ASSY", "Assembly", "Assembly operation combining multiple components.", 60),
        ("PRESS", "Press Fit", "Press fitting operation for interference-fit assembly.", 62),
        ("WIRE", "Wire Harness", "Wire harness assembly and routing operation.", 63),
        ("TEST", "Functional Test", "Functional testing operation to verify product performance.", 65),
        ("LEAK", "Leak Test", "Leak testing operation for sealed components and assemblies.", 66),
        ("CAL", "Calibration", "Instrument calibration and verification operation.", 67),
        ("INSP", "Inspection", "Quality inspection and dimensional verification operation.", 70),
        ("CMM", "CMM Inspection", "Coordinate Measuring Machine inspection for precision verification.", 71),
        ("SORT", "Sorting", "Sorting and segregation operation for quality containment.", 75),
        ("MARK", "Marking / Labeling", "Part marking, labeling, and identification operation.", 78),
        ("PACK", "Packaging", "Final packaging, boxing, and labeling operation.", 80),
        ("PALLT", "Palletizing", "Palletizing and stretch wrapping for shipment preparation.", 82),
        ("SHIP", "Shipping", "Final shipping preparation and outbound documentation.", 85),
        ("REWORK", "Rework", "Rework operation to bring non-conforming product to specification.", 90),
        ("REPAIR", "Repair", "Repair operation for damaged or returned products.", 92),
        ("SCRAP", "Scrap Disposal", "Scrap material segregation, processing, and disposal operation.", 95),
        ("CLEAN", "Cleaning", "Parts cleaning operation before or after processing.", 96),
    ],
    "routing_type": [
        ("DIRECT", "Direct Route", "Linear material flow through sequential operations without branches or rework.", 10),
        ("SPLIT", "Split Route", "Route splits into parallel paths. Multiple downstream operations from a single upstream.", 20),
        ("MERGE", "Merge Route", "Multiple inputs converge into a single downstream operation. Common in assembly.", 30),
        ("RECIRC", "Recirculation", "Material recirculates for rework or additional processing. Returns to earlier operation.", 40),
        ("BYPASS", "Bypass Route", "Alternative path bypassing one or more operations. Used for optional or alternate processes.", 50),
        ("PARAL", "Parallel Processing", "Two or more parallel paths running simultaneously. Increases throughput capacity.", 55),
        ("FLEX", "Flexible Routing", "Multiple possible paths depending on product variant, equipment availability, or demand.", 60),
        ("REVERSE", "Reverse Flow", "Reverse material flow for rework, disassembly, or material recovery operations.", 65),
        ("SCRAP", "Scrap Routing", "Routing for non-conforming material to scrap, rework, or sorting stations.", 70),
        ("LOOP", "Loop Routing", "Circular material flow through a loop of operations. Parts continue until all operations complete.", 75),
    ],
    "material_category": [
        ("RAW", "Raw Material", "Unprocessed raw materials received from suppliers. Base material for production.", 10),
        ("RMC", "Raw Material - Coil", "Raw material in coil form. Steel, aluminum, or wire coils for stamping or forming.", 12),
        ("RMR", "Raw Material - Rod/Bar", "Raw material in rod or bar form. For machining and turning operations.", 14),
        ("RMS", "Raw Material - Sheet", "Raw material in sheet or plate form. For fabrication and stamping.", 16),
        ("SEMI", "Semi-Finished", "Partially processed material awaiting further operations.", 18),
        ("SUB", "Sub-Assembly", "Partially assembled components that will be incorporated into final assemblies.", 20),
        ("WIP", "Work in Process", "In-process inventory between manufacturing operations. Active production material.", 30),
        ("FIN", "Finished Good", "Completed products ready for shipment to customers.", 40),
        ("PACK", "Packaging", "Packaging materials including boxes, pallets, wraps, and dunnage.", 50),
        ("SUP", "Supply / Consumable", "Consumable supplies and indirect materials used in production.", 55),
        ("SPARE", "Spare Part", "Maintenance spare parts for production equipment.", 60),
        ("MRO", "MRO Supply", "Maintenance, Repair, and Operations supplies and consumables.", 62),
        ("CHEM", "Chemical", "Chemicals, solvents, lubricants, and process fluids.", 64),
        ("RET", "Returned Material", "Customer returns or internally returned materials awaiting disposition.", 70),
        ("SCRP", "Scrap / Waste", "Scrap material, waste, or byproducts from production processes.", 75),
        ("QUAR", "Quarantine", "Material under quality hold awaiting inspection disposition.", 80),
    ],
    "inventory_type": [
        ("RAW", "Raw Material Stock", "Unprocessed material inventory held for production consumption.", 10),
        ("WIP", "Work in Process", "In-process inventory between operations. Includes material being actively worked.", 20),
        ("FIN", "Finished Goods", "Completed products awaiting shipment to customers.", 30),
        ("CYCLE", "Cycle Stock", "Regular inventory held to meet expected demand between replenishment cycles.", 35),
        ("SAFE", "Safety Stock", "Buffer stock maintained to protect against demand variability and supply uncertainty.", 40),
        ("BATCH", "Batch / Lot Stock", "Inventory held in discrete batches or lots with traceability requirements.", 42),
        ("PIPELINE", "Pipeline / In-Transit", "Inventory in transit between locations. Not yet available for use or sale.", 45),
        ("SEASON", "Seasonal Stock", "Inventory built in advance for anticipated seasonal demand peaks.", 50),
        ("DECOUP", "Decoupling Stock", "Buffer inventory between dependent processes to allow independent operation.", 52),
        ("CONS", "Consignment Stock", "Inventory held at customer location but owned by supplier until consumed.", 55),
        ("DAM", "Damaged / Quarantine", "Non-conforming material segregated for quality disposition.", 60),
        ("OBS", "Obsolete Stock", "Obsolete inventory no longer required for production or sales.", 65),
        ("RETURN", "Returned Goods", "Customer returns awaiting inspection, restock, or disposal.", 70),
    ],
    "kanban_type": [
        ("PROD", "Production Kanban", "Authorizes the production of a specific quantity of parts. Signals upstream process to produce.", 10),
        ("WITHDRAW", "Withdrawal Kanban", "Authorizes the movement of parts from upstream to downstream process. Triggers material handling.", 20),
        ("SIGNAL", "Signal Kanban", "Triggers production at a predetermined reorder point. Used for batch or large-part production.", 30),
        ("TRIAL", "Trial Kanban", "Temporary kanban used during new product introduction or process changes.", 35),
        ("BATCH", "Batch Kanban", "Kanban that authorizes production of a batch quantity. Used where one-piece flow is not feasible.", 40),
        ("EXP", "Express Kanban", "Emergency or rush kanban for urgent production or material movement needs.", 45),
        ("SUPPLIER", "Supplier Kanban", "External kanban sent to suppliers to trigger delivery. Part of external pull system.", 50),
        ("CONTRACT", "Contract Kanban", "Kanban used between companies in a supply chain. Defines contractual delivery quantities.", 55),
        ("ONE_O", "One-for-One", "One-for-one replacement kanban. Each unit consumed triggers exactly one unit of production.", 57),
        ("WIP", "WIP Kanban", "Work-in-process kanban to control inventory between adjacent processes.", 60),
        ("EMERGENCY", "Emergency Kanban", "Special kanban for emergency or unplanned production needs. Overrides normal pull signals.", 65),
    ],
    "container_type": [
        ("TOTE", "Tote Box", "Standard plastic tote box for small-to-medium parts. Stackable with lid options.", 10),
        ("BIN", "Bin", "Small parts bin for organized component storage. Common on workstations and shelving.", 15),
        ("BSKT", "Basket", "Wire or plastic basket for parts handling. Good for heat treatment or washing processes.", 18),
        ("PALLET", "Pallet", "Standard shipping pallet (48x40 or EUR). For bulk material transport and storage.", 20),
        ("RACK", "Rack", "Purpose-built material handling rack for specialized part geometries.", 25),
        ("BOX", "Corrugated Box", "Cardboard or corrugated box for lightweight parts and finished goods.", 28),
        ("CRATE", "Wooden Crate", "Heavy-duty wooden crate for large or heavy parts and equipment.", 30),
        ("DRUM", "Drum", "55-gallon or 30-gallon drum for liquids, powders, and bulk materials.", 35),
        ("IBC", "IBC Tote", "Intermediate Bulk Container for liquids and bulk materials. 275-330 gallon capacity.", 40),
        ("CART", "Rolling Cart", "Rolling cart for in-process material movement between workstations.", 45),
        ("HOPPER", "Hopper", "Hopper or tote for bulk material dispensing. Used for consumables and small parts.", 50),
        ("SILO", "Silo", "Outdoor or indoor silo for bulk raw material storage. Grains, plastic pellets, powders.", 55),
        ("TANK", "Tank", "Storage tank for liquids, chemicals, and bulk fluids.", 60),
        ("GONDOLA", "Gondola", "Large metal gondola for heavy bulk parts and scrap material.", 65),
        ("DUNNAGE", "Dunnage Tray", "Custom-molded dunnage tray for protecting sensitive parts during transport.", 70),
    ],
    "unit_type": [
        ("PC", "Piece / Each", "Individual unit count for discrete parts and assemblies.", 10),
        ("PR", "Pair", "Matched pair or set of two items.", 11),
        ("DZ", "Dozen", "Quantity of twelve pieces or units.", 12),
        ("BOX", "Box", "Containerized quantity count. One box = variable piece count per specification.", 13),
        ("KG", "Kilogram", "Metric weight unit for bulk materials and components.", 20),
        ("G", "Gram", "Metric weight for small quantities.", 21),
        ("LB", "Pound", "Imperial weight unit for bulk materials in US-based operations.", 25),
        ("OZ", "Ounce", "Imperial weight unit for small quantities.", 26),
        ("M", "Meter", "SI length unit for linear materials.", 30),
        ("CM", "Centimeter", "SI small length unit.", 31),
        ("FT", "Foot", "Imperial length unit.", 35),
        ("IN", "Inch", "Imperial small length unit.", 36),
        ("L", "Liter", "Metric volume unit for liquids.", 40),
        ("ML", "Milliliter", "Metric small volume unit.", 41),
        ("GAL", "Gallon", "US gallon volume unit for liquids.", 45),
        ("QT", "Quart", "US quart volume unit.", 46),
        ("SQ_M", "Square Meter", "Metric area unit for sheet materials and surface area.", 50),
        ("SQ_FT", "Square Foot", "Imperial area unit.", 51),
        ("CU_M", "Cubic Meter", "Metric volume unit for bulk materials and shipping volume.", 55),
        ("CU_FT", "Cubic Foot", "Imperial volume unit.", 56),
        ("ROLL", "Roll", "Roll count for coiled or rolled materials (film, paper, fabric).", 60),
        ("SHEET", "Sheet", "Sheet count for sheet materials (metal, wood, paper).", 61),
        ("PALL", "Pallet", "Pallet count for palletized shipments.", 62),
        ("HR", "Hour", "Time unit for labor tracking and machine hours.", 70),
        ("MIN", "Minute", "Time unit for cycle times and operation duration.", 71),
        ("DAY", "Day", "Day unit for production scheduling and planning.", 72),
        ("BATCH", "Batch", "Batch or lot unit for process manufacturing.", 75),
        ("SET", "Set", "Complete set of items required for an assembly or process.", 80),
    ],
    "downtime_code": [
        ("SETUP", "Setup / Changeover", "Time spent changing between production runs. SMED target for reduction.", 10),
        ("STARTUP", "Startup / Warm-up", "Equipment startup and warm-up time at beginning of shift or after maintenance.", 12),
        ("SHUTDN", "Shutdown", "End-of-shift or end-of-run equipment shutdown and cleaning.", 14),
        ("BREAK", "Break / Lunch", "Scheduled employee breaks including lunch periods.", 20),
        ("MEET", "Meeting / Training", "Scheduled meetings, stand-up huddles, or training sessions.", 25),
        ("MAINT", "Planned Maintenance", "Scheduled preventive maintenance activities. TPM pillar activity.", 30),
        ("PM", "Predictive Maintenance", "Condition-based maintenance triggered by monitoring data. Vibration, thermal, or oil analysis.", 32),
        ("BREAKDOWN", "Equipment Breakdown", "Unscheduled equipment failure requiring repair. Major OEE loss category.", 40),
        ("NO_MAT", "Material Shortage", "Waiting for raw materials, components, or supplies. Upstream supply disruption.", 45),
        ("NO_OP", "No Operator", "Operator not available. Absenteeism, training, or reassignment.", 50),
        ("NO_TOOL", "Tool / Fixture Issue", "Waiting for tools, fixtures, or gages. Tool breakage or unavailability.", 52),
        ("NO_PROG", "No Program", "Waiting for CNC program, setup instructions, or work order.", 54),
        ("QUALITY", "Quality Issue", "Stoppage due to quality problem, defect containment, or process adjustment.", 60),
        ("TRIAL", "Trial / Testing", "Process trials, first-piece inspection, or production sampling.", 62),
        ("CLEAN", "Cleaning / 5S", "Scheduled cleaning time. 5S activity including sweeping, organizing, and waste removal.", 65),
        ("ENG", "Engineering Change", "Downtime for engineering changes, process modifications, or product changeover.", 70),
        ("UTILITY", "Utility Outage", "Loss of power, compressed air, water, gas, or other utilities.", 75),
        ("ENVIRO", "Environmental", "Downtime due to environmental conditions or HSE requirements.", 78),
        ("IT", "IT / System Downtime", "Loss of MES, ERP, or other production-critical IT systems.", 80),
        ("WAIT", "Waiting", "General waiting time: for instructions, material, equipment, or personnel.", 85),
        ("NO_WORK", "No Work Scheduled", "No production work scheduled for this work center during this period.", 90),
        ("OTHER", "Other / Unclassified", "Downtime not fitting any other category. Investigate and reclassify root cause.", 99),
    ],
    "defect_code": [
        ("DIM", "Dimension Out of Spec", "Part dimension outside specified tolerance limits. Requires dimensional analysis.", 10),
        ("SURF", "Surface Defect", "Surface finish, appearance, or texture defect. Roughness, scratches, or marks.", 15),
        ("SCRATCH", "Scratch / Mar", "Visible scratch, scuff, or mar on part surface. Cosmetic or functional concern.", 16),
        ("BURR", "Burr / Flash", "Excess material remaining after machining or molding. Sharp edges or protruding flash.", 17),
        ("CRACK", "Crack / Fracture", "Visible crack or fracture in material. Structural integrity concern.", 20),
        ("POROS", "Porosity", "Internal or surface porosity in castings, welds, or molded parts.", 25),
        ("VOID", "Internal Void", "Internal cavity or void within material. Detected by NDT or sectioning.", 26),
        ("WARP", "Warpage / Deformation", "Part warped, twisted, or deformed beyond specification.", 30),
        ("DELAM", "Delamination", "Layer separation in laminated, coated, or composite materials.", 32),
        ("CONTAM", "Contamination", "Foreign material contamination on part surface or embedded in material.", 35),
        ("OXIDE", "Oxidation / Rust", "Surface oxidation, rust, or corrosion on metal parts. Handling or storage issue.", 37),
        ("MISSING", "Missing Operation", "Required manufacturing operation not performed. Incomplete processing.", 40),
        ("THREAD", "Thread Defect", "Thread damage, incomplete threads, or out-of-spec thread dimensions.", 42),
        ("MARK", "Marking Defect", "Missing, illegible, or incorrect part marking, labeling, or barcode.", 44),
        ("HEAT", "Heat Treat Defect", "Improper heat treatment resulting in incorrect hardness or material properties.", 46),
        ("WELD", "Weld Defect", "Weld discontinuity including incomplete fusion, undercut, porosity, or spatter.", 48),
        ("PAINT", "Paint / Coating Defect", "Paint runs, sags, orange peel, insufficient coverage, or color mismatch.", 50),
        ("MOLD", "Molding Defect", "Short shot, flash, sink marks, or warp in molded parts.", 52),
        ("ASSY", "Assembly Error", "Incorrect assembly: wrong parts, wrong orientation, missing components, or incorrect torque.", 55),
        ("FUNCTION", "Functional Failure", "Product fails functional test. Performance, electrical, or mechanical failure.", 60),
        ("LEAK", "Leak / Seal Failure", "Fluid or gas leak in sealed components or assemblies.", 62),
        ("CAL", "Calibration Error", "Out-of-calibration or incorrect measurement. Requires recalibration.", 65),
        ("MIX", "Material Mix-up", "Wrong material used in production. Material identification or traceability failure.", 70),
        ("SORT", "Sorting Error", "Material sorted incorrectly. Wrong grade, size, or classification.", 72),
        ("PACK", "Packaging Defect", "Damaged, incorrect, or insufficient packaging. Shipping damage preventable.", 75),
    ],
    "scrap_reason": [
        ("MATL", "Material Defect", "Raw material defect discovered during processing. Incoming quality issue.", 10),
        ("PROC", "Processing Error", "Incorrect processing, machining error, or operator mistake resulting in scrap.", 15),
        ("HANDL", "Handling Damage", "Part damaged during handling, transport, or storage within the facility.", 20),
        ("PROTO", "Prototype / Test", "Prototype parts, test samples, or first-article verification pieces.", 25),
        ("ENGCHG", "Engineering Change", "Parts obsoleted by engineering change order or product design change.", 30),
        ("OBS", "Obsolete", "Inventory declared obsolete due to product discontinuation or specification change.", 35),
        ("EXPIRED", "Shelf Life Expired", "Material that has exceeded its shelf life or expiration date.", 37),
        ("CONTAM", "Contamination", "Material contaminated during processing or storage. Unusable for production.", 40),
        ("OVERAGE", "Production Overage", "Intentional overage parts produced beyond order quantity for sampling or setup.", 45),
        ("DAMAGE", "Physical Damage", "Part physically damaged beyond repair. Drop, crush, or impact damage.", 50),
        ("QUALITY", "Quality Reject", "Part fails quality inspection and cannot be reworked. Permanent rejection.", 55),
        ("TEST", "Destructive Test", "Parts consumed during destructive testing, metallurgical analysis, or lab testing.", 60),
        ("STARTUP", "Startup / Ramp Scrap", "Scrap generated during equipment startup, warm-up, or production ramp.", 62),
        ("SETUP", "Setup Scrap", "Scrap generated during changeover or setup activities before process stabilization.", 65),
        ("SAMPLE", "Sample / Retention", "Retention samples, quality records, or customer-requested samples.", 68),
        ("EXCESS", "Excess Inventory", "Inventory written off due to excess or overstock condition.", 70),
        ("THEFT", "Theft / Loss", "Material lost due to theft, misplacement, or inventory discrepancy.", 75),
        ("NATURAL", "Natural Waste", "Inherent process waste: trim waste, gate scrap, startup tails, and end cuts.", 80),
    ],
    "kaizen_category": [
        ("SAFETY", "Safety Improvement", "Improvement targeting employee safety, hazard reduction, or ergonomic risk elimination.", 10),
        ("5S", "5S / Workplace Organization", "Sort, Set in Order, Shine, Standardize, Sustain. Workplace organization and visual management.", 15),
        ("QUALITY", "Quality Improvement", "Improvement targeting product quality, defect reduction, or process capability.", 20),
        ("COST", "Cost Reduction", "Improvement targeting cost reduction through waste elimination and efficiency gains.", 25),
        ("PROD", "Productivity Improvement", "Improvement targeting productivity, output increase, or throughput enhancement.", 30),
        ("MOTION", "Motion / Ergonomics", "Reducing unnecessary motion or ergonomic risk. Workstation layout and process redesign.", 35),
        ("WASTE", "Waste Elimination", "Elimination of any form of waste (Muda): transport, inventory, motion, waiting, overprocessing, overproduction, defects.", 40),
        ("FLOW", "Flow Improvement", "Improvement to material or information flow. Value stream mapping and continuous flow.", 45),
        ("TPM", "Total Productive Maintenance", "Autonomous maintenance, planned maintenance, and overall equipment effectiveness improvement.", 50),
        ("SMED", "Quick Changeover", "Single-Minute Exchange of Die. Setup time reduction through internal/external separation.", 55),
        ("STAND", "Standardization", "Work standardization, standard operating procedures, and best practice documentation.", 60),
        ("KANBAN", "Pull System / Kanban", "Pull system implementation, kanban loop design, and inventory level optimization.", 65),
        ("HEIJUN", "Heijunka / Leveling", "Production leveling and load smoothing. Mixed-model sequencing and demand balancing.", 70),
        ("JIDOKA", "Jidoka / Autonomation", "Built-in quality through automation with human intelligence. Andon and poka-yoke systems.", 75),
        ("ENERGY", "Energy Reduction", "Energy consumption reduction through efficient equipment and processes.", 78),
        ("ENVIRO", "Environmental", "Environmental impact reduction. Waste reduction, recycling, and emissions reduction.", 80),
        ("MURA", "Mura Reduction", "Reduction of unevenness and variability in production schedules and workload.", 82),
        ("MURI", "Muri Reduction", "Reduction of overburden on operators and equipment. Workload balancing.", 84),
        ("VSM", "Value Stream Mapping", "Current and future state value stream mapping to identify and eliminate waste.", 85),
        ("DIGITAL", "Digitalization", "Digital transformation of manual processes. Automation of data collection and analysis.", 90),
    ],
    "skill_type": [
        ("OPER", "Machine Operator", "Qualified machine operator. Proficient in machine operation, loading/unloading, and inspection.", 10),
        ("SENIOR", "Senior Operator", "Experienced operator capable of training others and handling complex operations.", 12),
        ("SETUP", "Setup Specialist", "Changeover and setup specialist. Skilled in SMED and quick changeover techniques.", 15),
        ("TECH", "Maintenance Technician", "Maintenance technician skilled in mechanical, electrical, and pneumatic repair.", 20),
        ("ELEC", "Electrician", "Licensed electrician for electrical systems, controls, and PLC troubleshooting.", 22),
        ("MECH", "Mechanic", "Industrial mechanic for mechanical systems, hydraulics, and pneumatics.", 23),
        ("CNC", "CNC Programmer", "CNC programmer skilled in G-code, CAM programming, and machine setup.", 25),
        ("ROB", "Robotics Specialist", "Robotics programmer and technician for industrial robot systems.", 27),
        ("PLC", "PLC Programmer", "PLC and automation programmer for control systems and SCADA integration.", 28),
        ("WELD", "Welder Certified", "Certified welder for MIG, TIG, and arc welding operations. Holds current certification.", 30),
        ("INSP", "Quality Inspector", "Quality inspector skilled in dimensional inspection, CMM operation, and GD&T.", 35),
        ("CMM", "CMM Operator", "CMM programmer and operator for precision dimensional inspection.", 36),
        ("NDT", "NDT Technician", "Non-destructive testing technician. Certified in UT, MT, PT, or RT methods.", 37),
        ("LAB", "Lab Technician", "Metallurgical or materials lab technician for material analysis and testing.", 38),
        ("ENG", "Manufacturing Engineer", "Manufacturing engineer for process design, optimization, and continuous improvement.", 40),
        ("QUAL", "Quality Engineer", "Quality engineer for SPC, process capability, APQP, and PPAP.", 42),
        ("LEAN", "Lean Specialist", "Lean manufacturing specialist trained in TPS, Kaizen, VSM, and Six Sigma.", 45),
        ("TPM", "TPM Coordinator", "TPM coordinator for autonomous maintenance, planned maintenance, and OEE improvement.", 47),
        ("5S", "5S Coordinator", "5S workplace organization coordinator and auditor.", 48),
        ("SAFE", "Safety Specialist", "HSE specialist for safety programs, risk assessment, and regulatory compliance.", 50),
        ("LOG", "Logistics Specialist", "Materials and logistics specialist for supply chain, warehousing, and material flow.", 52),
        ("MATL", "Material Handler", "Material handler for forklift, crane, and material transport equipment operations.", 55),
        ("PROG", "CNC/PLC Programmer", "Combined CNC and PLC programmer for integrated manufacturing systems.", 60),
        ("HYD", "Hydraulics Specialist", "Specialist in hydraulic systems design, troubleshooting, and repair.", 62),
        ("PNEU", "Pneumatics Specialist", "Specialist in pneumatic systems and controls.", 63),
    ],
    "role": [
        ("OP", "Operator", "Line operator performing production work. Runs equipment, inspects output, maintains 5S.", 10),
        ("SOP", "Senior Operator", "Senior operator with advanced skills. Trains new operators and handles complex production tasks.", 12),
        ("MATL", "Material Handler", "Material handler managing material movement, replenishment, and logistics.", 14),
        ("TL", "Team Lead", "Team lead coordinating a small production team. First escalation point for issues.", 20),
        ("CL", "Cell Lead", "Manufacturing cell lead responsible for cell performance, quality, and continuous improvement.", 22),
        ("SUP", "Supervisor", "Shift supervisor managing production shift. Safety, quality, delivery, and cost accountability.", 30),
        ("COORD", "Production Coordinator", "Production coordinator managing scheduling, material availability, and production execution.", 32),
        ("MGR", "Plant Manager", "Plant or department manager with full P&L accountability for manufacturing operations.", 40),
        ("DIR", "Operations Director", "Director of operations overseeing multiple plants or a large manufacturing facility.", 45),
        ("TECH", "Maintenance Technician", "Maintenance technician responsible for equipment reliability and repair.", 50),
        ("MAINT", "Maintenance Planner", "Maintenance planner scheduling preventive and predictive maintenance activities.", 52),
        ("ENG", "Manufacturing Engineer", "Manufacturing engineer supporting production with process improvements and technical support.", 55),
        ("QC", "Quality Inspector", "Quality control inspector performing product inspections and process audits.", 60),
        ("QE", "Quality Engineer", "Quality engineer managing quality systems, SPC, CAPA, and continuous improvement.", 62),
        ("LEAN", "Lean / CI Specialist", "Lean and continuous improvement specialist driving Kaizen, VSM, and waste reduction.", 65),
        ("SCHED", "Production Scheduler", "Production scheduler creating and maintaining production schedules and material plans.", 67),
        ("PUR", "Purchasing Agent", "Purchasing agent responsible for supplier management and material procurement.", 70),
        ("LOG", "Logistics Coordinator", "Logistics coordinator managing shipping, receiving, and material flow.", 72),
        ("HSE", "HSE Specialist", "Health, Safety, and Environmental specialist ensuring regulatory compliance.", 75),
        ("HR", "HR Business Partner", "Human resources partner supporting talent management and employee relations.", 78),
        ("IT", "IT / Systems Support", "IT systems support for MES, ERP, and manufacturing technology systems.", 80),
        ("VP", "VP of Operations", "Vice President of Operations overseeing manufacturing strategy and execution.", 85),
    ],
    "shift_team": [
        ("A", "Team A (Day)", "Day shift primary team. Typically 06:00-14:00 or 07:00-15:00.", 10),
        ("B", "Team B (Afternoon)", "Afternoon shift team. Typically 14:00-22:00 or 15:00-23:00.", 20),
        ("C", "Team C (Night)", "Night shift team. Typically 22:00-06:00 or 23:00-07:00.", 30),
        ("D", "Team D (Rotating)", "Rotating shift relief team covering days off for Teams A, B, and C.", 35),
        ("GOLD", "Gold Team", "First 12-hour shift team in block schedule. Day/night rotation.", 40),
        ("BLUE", "Blue Team", "Second 12-hour shift team in block schedule. Opposite rotation to Gold.", 42),
        ("RED", "Red Team", "Third shift team in 3-crew 12-hour rotation systems.", 44),
        ("WKD", "Weekend Team", "Weekend shift team covering Saturday and Sunday operations.", 50),
        ("FLOAT", "Float / Relief Team", "Floating relief team covering PTO, training, and temporary assignments.", 55),
        ("SWING", "Swing Team", "Swing shift team covering the gap between day and night shifts.", 60),
    ],
}


class Command(BaseCommand):
    help = "Seed reference items for all manufacturing reference tables"

    def handle(self, *args, **options):
        created = 0
        for table_type, items in SEED_DATA.items():
            for code, name, desc, sort_order in items:
                obj, is_new = ReferenceItem.objects.get_or_create(
                    table_type=table_type, code=code,
                    defaults={"name": name, "description": desc, "sort_order": sort_order, "is_active": True},
                )
                if is_new:
                    created += 1
        self.stdout.write(self.style.SUCCESS(f"Seeded {created} new reference items"))
