from django.core.management.base import BaseCommand
from manufacturing.models import ReferenceCategory, ReferenceValue


CATEGORIES = {
    "status": {
        "name": "Entity Status",
        "description": "Active/Inactive/Archived status values for all entities",
        "values": [
            {"code": "ACTIVE", "name": "Active", "sort_order": 1, "metadata": {"color": "emerald"}},
            {"code": "INACTIVE", "name": "Inactive", "sort_order": 2, "metadata": {"color": "slate"}},
            {"code": "ARCHIVED", "name": "Archived", "sort_order": 3, "metadata": {"color": "gray"}},
        ],
    },
    "country": {
        "name": "Country",
        "description": "Countries for entity addresses",
        "values": [
            {"code": "US", "name": "United States", "sort_order": 1},
            {"code": "MX", "name": "Mexico", "sort_order": 2},
            {"code": "CA", "name": "Canada", "sort_order": 3},
        ],
    },
    "timezone": {
        "name": "Timezone",
        "description": "IANA timezone identifiers",
        "values": [
            {"code": "America/Anchorage", "name": "(UTC-09:00) America/Anchorage", "sort_order": 1},
            {"code": "America/Los_Angeles", "name": "(UTC-08:00) America/Los_Angeles", "sort_order": 2},
            {"code": "America/Phoenix", "name": "(UTC-07:00) America/Phoenix", "sort_order": 3},
            {"code": "America/Denver", "name": "(UTC-07:00) America/Denver", "sort_order": 4},
            {"code": "America/Chicago", "name": "(UTC-06:00) America/Chicago", "sort_order": 5},
            {"code": "America/Mexico_City", "name": "(UTC-06:00) America/Mexico_City", "sort_order": 6},
            {"code": "America/Monterrey", "name": "(UTC-06:00) America/Monterrey", "sort_order": 7},
            {"code": "America/Tijuana", "name": "(UTC-08:00) America/Tijuana", "sort_order": 8},
            {"code": "America/New_York", "name": "(UTC-05:00) America/New_York", "sort_order": 9},
            {"code": "America/Detroit", "name": "(UTC-05:00) America/Detroit", "sort_order": 10},
            {"code": "America/Cancun", "name": "(UTC-05:00) America/Cancun", "sort_order": 11},
            {"code": "America/Chihuahua", "name": "(UTC-06:00) America/Chihuahua", "sort_order": 12},
            {"code": "America/Hermosillo", "name": "(UTC-07:00) America/Hermosillo", "sort_order": 13},
            {"code": "America/Mazatlan", "name": "(UTC-07:00) America/Mazatlan", "sort_order": 14},
            {"code": "Europe/London", "name": "(UTC+00:00) Europe/London", "sort_order": 15},
            {"code": "Europe/Berlin", "name": "(UTC+01:00) Europe/Berlin", "sort_order": 16},
            {"code": "Europe/Bucharest", "name": "(UTC+02:00) Europe/Bucharest", "sort_order": 17},
            {"code": "Asia/Dubai", "name": "(UTC+04:00) Asia/Dubai", "sort_order": 18},
            {"code": "Asia/Shanghai", "name": "(UTC+08:00) Asia/Shanghai", "sort_order": 19},
            {"code": "Asia/Tokyo", "name": "(UTC+09:00) Asia/Tokyo", "sort_order": 20},
            {"code": "Australia/Sydney", "name": "(UTC+11:00) Australia/Sydney", "sort_order": 21},
            {"code": "Pacific/Honolulu", "name": "(UTC-10:00) Pacific/Honolulu", "sort_order": 22},
            {"code": "Etc/UTC", "name": "(UTC+00:00) UTC", "sort_order": 23},
        ],
    },
    "language": {
        "name": "Language / Locale",
        "description": "Languages and locales",
        "values": [
            {"code": "en", "name": "English", "sort_order": 1},
            {"code": "en_US", "name": "English (US)", "sort_order": 2},
            {"code": "en_GB", "name": "English (UK)", "sort_order": 3},
            {"code": "es", "name": "Spanish", "sort_order": 4},
            {"code": "es_MX", "name": "Spanish (Mexico)", "sort_order": 5},
            {"code": "fr", "name": "French", "sort_order": 6},
            {"code": "fr_CA", "name": "French (Canada)", "sort_order": 7},
            {"code": "ro", "name": "Romanian", "sort_order": 8},
            {"code": "de", "name": "German", "sort_order": 9},
            {"code": "zh", "name": "Chinese", "sort_order": 10},
            {"code": "ja", "name": "Japanese", "sort_order": 11},
        ],
    },
    "language_locale": {
        "name": "Language / Locale",
        "description": "Alias for language category",
        "values": [],
    },
    "state": {
        "name": "State / Province",
        "description": "States and provinces for entity addresses",
        "values": [
            {"code": "CA", "name": "California", "sort_order": 1, "metadata": {"country": "US"}},
            {"code": "TX", "name": "Texas", "sort_order": 2, "metadata": {"country": "US"}},
            {"code": "IL", "name": "Illinois", "sort_order": 3, "metadata": {"country": "US"}},
            {"code": "MI", "name": "Michigan", "sort_order": 4, "metadata": {"country": "US"}},
            {"code": "OH", "name": "Ohio", "sort_order": 5, "metadata": {"country": "US"}},
            {"code": "IN", "name": "Indiana", "sort_order": 6, "metadata": {"country": "US"}},
            {"code": "NY", "name": "New York", "sort_order": 7, "metadata": {"country": "US"}},
            {"code": "AZ", "name": "Arizona", "sort_order": 8, "metadata": {"country": "US"}},
            {"code": "WA", "name": "Washington", "sort_order": 9, "metadata": {"country": "US"}},
            {"code": "OR", "name": "Oregon", "sort_order": 10, "metadata": {"country": "US"}},
            {"code": "GA", "name": "Georgia", "sort_order": 11, "metadata": {"country": "US"}},
            {"code": "NC", "name": "North Carolina", "sort_order": 12, "metadata": {"country": "US"}},
            {"code": "TN", "name": "Tennessee", "sort_order": 13, "metadata": {"country": "US"}},
            {"code": "PA", "name": "Pennsylvania", "sort_order": 14, "metadata": {"country": "US"}},
            {"code": "FL", "name": "Florida", "sort_order": 15, "metadata": {"country": "US"}},
            {"code": "MO", "name": "Missouri", "sort_order": 16, "metadata": {"country": "US"}},
            {"code": "WI", "name": "Wisconsin", "sort_order": 17, "metadata": {"country": "US"}},
            {"code": "MN", "name": "Minnesota", "sort_order": 18, "metadata": {"country": "US"}},
            {"code": "CO", "name": "Colorado", "sort_order": 19, "metadata": {"country": "US"}},
            {"code": "AL", "name": "Alabama", "sort_order": 20, "metadata": {"country": "US"}},
            {"code": "SC", "name": "South Carolina", "sort_order": 21, "metadata": {"country": "US"}},
            {"code": "KY", "name": "Kentucky", "sort_order": 22, "metadata": {"country": "US"}},
            {"code": "IA", "name": "Iowa", "sort_order": 23, "metadata": {"country": "US"}},
            {"code": "NJ", "name": "New Jersey", "sort_order": 24, "metadata": {"country": "US"}},
            {"code": "VA", "name": "Virginia", "sort_order": 25, "metadata": {"country": "US"}},
            {"code": "OK", "name": "Oklahoma", "sort_order": 26, "metadata": {"country": "US"}},
            {"code": "AR", "name": "Arkansas", "sort_order": 27, "metadata": {"country": "US"}},
            {"code": "MS", "name": "Mississippi", "sort_order": 28, "metadata": {"country": "US"}},
            {"code": "KS", "name": "Kansas", "sort_order": 29, "metadata": {"country": "US"}},
            {"code": "NE", "name": "Nebraska", "sort_order": 30, "metadata": {"country": "US"}},
            {"code": "UT", "name": "Utah", "sort_order": 31, "metadata": {"country": "US"}},
            {"code": "NV", "name": "Nevada", "sort_order": 32, "metadata": {"country": "US"}},
            {"code": "NM", "name": "New Mexico", "sort_order": 33, "metadata": {"country": "US"}},
            {"code": "CT", "name": "Connecticut", "sort_order": 34, "metadata": {"country": "US"}},
            {"code": "MA", "name": "Massachusetts", "sort_order": 35, "metadata": {"country": "US"}},
            {"code": "MD", "name": "Maryland", "sort_order": 36, "metadata": {"country": "US"}},
            {"code": "LA", "name": "Louisiana", "sort_order": 37, "metadata": {"country": "US"}},
            {"code": "NH", "name": "New Hampshire", "sort_order": 38, "metadata": {"country": "US"}},
            {"code": "ME", "name": "Maine", "sort_order": 39, "metadata": {"country": "US"}},
            {"code": "RI", "name": "Rhode Island", "sort_order": 40, "metadata": {"country": "US"}},
            {"code": "VT", "name": "Vermont", "sort_order": 41, "metadata": {"country": "US"}},
            {"code": "DE", "name": "Delaware", "sort_order": 42, "metadata": {"country": "US"}},
            {"code": "WV", "name": "West Virginia", "sort_order": 43, "metadata": {"country": "US"}},
            {"code": "WY", "name": "Wyoming", "sort_order": 44, "metadata": {"country": "US"}},
            {"code": "ID", "name": "Idaho", "sort_order": 45, "metadata": {"country": "US"}},
            {"code": "MT", "name": "Montana", "sort_order": 46, "metadata": {"country": "US"}},
            {"code": "SD", "name": "South Dakota", "sort_order": 47, "metadata": {"country": "US"}},
            {"code": "ND", "name": "North Dakota", "sort_order": 48, "metadata": {"country": "US"}},
            {"code": "AK", "name": "Alaska", "sort_order": 49, "metadata": {"country": "US"}},
            {"code": "HI", "name": "Hawaii", "sort_order": 50, "metadata": {"country": "US"}},
            {"code": "BC", "name": "British Columbia", "sort_order": 51, "metadata": {"country": "CA"}},
            {"code": "ON", "name": "Ontario", "sort_order": 52, "metadata": {"country": "CA"}},
            {"code": "QC", "name": "Quebec", "sort_order": 53, "metadata": {"country": "CA"}},
            {"code": "AB", "name": "Alberta", "sort_order": 54, "metadata": {"country": "CA"}},
            {"code": "NS", "name": "Nova Scotia", "sort_order": 55, "metadata": {"country": "CA"}},
            {"code": "NL", "name": "Newfoundland and Labrador", "sort_order": 56, "metadata": {"country": "CA"}},
            {"code": "MB", "name": "Manitoba", "sort_order": 57, "metadata": {"country": "CA"}},
            {"code": "SK", "name": "Saskatchewan", "sort_order": 58, "metadata": {"country": "CA"}},
            {"code": "NB", "name": "New Brunswick", "sort_order": 59, "metadata": {"country": "CA"}},
            {"code": "PE", "name": "Prince Edward Island", "sort_order": 60, "metadata": {"country": "CA"}},
            {"code": "NT", "name": "Northwest Territories", "sort_order": 61, "metadata": {"country": "CA"}},
            {"code": "YT", "name": "Yukon", "sort_order": 62, "metadata": {"country": "CA"}},
            {"code": "NU", "name": "Nunavut", "sort_order": 63, "metadata": {"country": "CA"}},
            {"code": "aguascalientes", "name": "Aguascalientes", "sort_order": 64, "metadata": {"country": "MX"}},
            {"code": "baja_california", "name": "Baja California", "sort_order": 65, "metadata": {"country": "MX"}},
            {"code": "baja_california_sur", "name": "Baja California Sur", "sort_order": 66, "metadata": {"country": "MX"}},
            {"code": "campeche", "name": "Campeche", "sort_order": 67, "metadata": {"country": "MX"}},
            {"code": "chiapas", "name": "Chiapas", "sort_order": 68, "metadata": {"country": "MX"}},
            {"code": "chihuahua", "name": "Chihuahua", "sort_order": 69, "metadata": {"country": "MX"}},
            {"code": "coahuila", "name": "Coahuila", "sort_order": 70, "metadata": {"country": "MX"}},
            {"code": "colima", "name": "Colima", "sort_order": 71, "metadata": {"country": "MX"}},
            {"code": "durango", "name": "Durango", "sort_order": 72, "metadata": {"country": "MX"}},
            {"code": "guanajuato", "name": "Guanajuato", "sort_order": 73, "metadata": {"country": "MX"}},
            {"code": "guerrero", "name": "Guerrero", "sort_order": 74, "metadata": {"country": "MX"}},
            {"code": "hidalgo", "name": "Hidalgo", "sort_order": 75, "metadata": {"country": "MX"}},
            {"code": "jalisco", "name": "Jalisco", "sort_order": 76, "metadata": {"country": "MX"}},
            {"code": "mexico_state", "name": "Mexico State", "sort_order": 77, "metadata": {"country": "MX"}},
            {"code": "mexico_city", "name": "Mexico City", "sort_order": 78, "metadata": {"country": "MX"}},
            {"code": "michoacan", "name": "Michoacan", "sort_order": 79, "metadata": {"country": "MX"}},
            {"code": "morelos", "name": "Morelos", "sort_order": 80, "metadata": {"country": "MX"}},
            {"code": "nayarit", "name": "Nayarit", "sort_order": 81, "metadata": {"country": "MX"}},
            {"code": "nuevo_leon", "name": "Nuevo Leon", "sort_order": 82, "metadata": {"country": "MX"}},
            {"code": "oaxaca", "name": "Oaxaca", "sort_order": 83, "metadata": {"country": "MX"}},
            {"code": "puebla", "name": "Puebla", "sort_order": 84, "metadata": {"country": "MX"}},
            {"code": "queretaro", "name": "Queretaro", "sort_order": 85, "metadata": {"country": "MX"}},
            {"code": "quintana_roo", "name": "Quintana Roo", "sort_order": 86, "metadata": {"country": "MX"}},
            {"code": "san_luis_potosi", "name": "San Luis Potosi", "sort_order": 87, "metadata": {"country": "MX"}},
            {"code": "sinaloa", "name": "Sinaloa", "sort_order": 88, "metadata": {"country": "MX"}},
            {"code": "sonora", "name": "Sonora", "sort_order": 89, "metadata": {"country": "MX"}},
            {"code": "tabasco", "name": "Tabasco", "sort_order": 90, "metadata": {"country": "MX"}},
            {"code": "tamaulipas", "name": "Tamaulipas", "sort_order": 91, "metadata": {"country": "MX"}},
            {"code": "tlaxcala", "name": "Tlaxcala", "sort_order": 92, "metadata": {"country": "MX"}},
            {"code": "veracruz", "name": "Veracruz", "sort_order": 93, "metadata": {"country": "MX"}},
            {"code": "yucatan", "name": "Yucatan", "sort_order": 94, "metadata": {"country": "MX"}},
            {"code": "zacatecas", "name": "Zacatecas", "sort_order": 95, "metadata": {"country": "MX"}},
        ],
    },
    "plant_type": {
        "name": "Plant Type",
        "description": "Type/category of manufacturing plant",
        "values": [
            {"code": "manufacturing", "name": "Manufacturing", "sort_order": 1, "metadata": {"color": "blue"}},
            {"code": "assembly", "name": "Assembly", "sort_order": 2, "metadata": {"color": "indigo"}},
            {"code": "warehouse", "name": "Warehouse", "sort_order": 3, "metadata": {"color": "amber"}},
            {"code": "fabrication", "name": "Fabrication", "sort_order": 4, "metadata": {"color": "violet"}},
            {"code": "distribution", "name": "Distribution Center", "sort_order": 5, "metadata": {"color": "cyan"}},
        ],
    },
    "line_type": {
        "name": "Line Type",
        "description": "Production line type/category",
        "values": [
            {"code": "assembly_line", "name": "Assembly Line", "sort_order": 1, "metadata": {"color": "blue"}},
            {"code": "fabrication_line", "name": "Fabrication Line", "sort_order": 2, "metadata": {"color": "violet"}},
            {"code": "machining_line", "name": "Machining Line", "sort_order": 3, "metadata": {"color": "slate"}},
            {"code": "painting_coating", "name": "Painting / Coating", "sort_order": 4, "metadata": {"color": "cyan"}},
            {"code": "packaging_line", "name": "Packaging Line", "sort_order": 5, "metadata": {"color": "amber"}},
            {"code": "testing_inspection", "name": "Testing / Inspection", "sort_order": 6, "metadata": {"color": "indigo"}},
            {"code": "sub_assembly_line", "name": "Sub-Assembly Line", "sort_order": 7, "metadata": {"color": "teal"}},
            {"code": "final_assembly", "name": "Final Assembly", "sort_order": 8, "metadata": {"color": "emerald"}},
            {"code": "mixed_model_line", "name": "Mixed-Model Line", "sort_order": 9, "metadata": {"color": "orange"}},
            {"code": "cellular_manufacturing", "name": "Cellular Manufacturing", "sort_order": 10, "metadata": {"color": "purple"}},
        ],
    },
    "calendar": {
        "name": "Calendar",
        "description": "Work calendar patterns",
        "values": [
            {"code": "standard_mo_fri", "name": "Standard (Mon-Fri)", "sort_order": 1},
            {"code": "extended_mo_sat", "name": "Extended (Mon-Sat)", "sort_order": 2},
            {"code": "continuous", "name": "Continuous (7 days)", "sort_order": 3},
            {"code": "compressed_4x10", "name": "Compressed 4x10", "sort_order": 4},
        ],
    },
    "shift_model": {
        "name": "Shift Model",
        "description": "Shift patterns and models",
        "values": [
            {"code": "1_shift_morning", "name": "1-shift (Morning)", "sort_order": 1},
            {"code": "1_shift_day", "name": "1-shift (Day)", "sort_order": 2},
            {"code": "1_shift_night", "name": "1-shift (Night)", "sort_order": 3},
            {"code": "2_shift_morn_aftn", "name": "2-shift (Morn/Aftn)", "sort_order": 4},
            {"code": "2_shift_day_night", "name": "2-shift (Day/Night)", "sort_order": 5},
            {"code": "3_shift_continuous", "name": "3-shift (Continuous)", "sort_order": 6},
            {"code": "3_shift_rotating", "name": "3-shift (Rotating)", "sort_order": 7},
            {"code": "247_panama", "name": "24/7 Panama", "sort_order": 8},
            {"code": "247_dupont", "name": "24/7 DuPont", "sort_order": 9},
            {"code": "12hr_block", "name": "12-Hour Block", "sort_order": 10},
            {"code": "night_only", "name": "Night Only", "sort_order": 11},
            {"code": "split", "name": "Split", "sort_order": 12},
            {"code": "flexible", "name": "Flexible / Custom", "sort_order": 13},
            {"code": "weekend", "name": "Weekend Shift", "sort_order": 14},
            {"code": "takt_sync", "name": "Takt-Synchronized Shift", "sort_order": 15},
            {"code": "lean_1_shift", "name": "Lean Single (1-Shift)", "sort_order": 16},
            {"code": "lean_2_shift", "name": "Lean Two-Shift", "sort_order": 17},
            {"code": "heijunka", "name": "Heijunka Leveled Shift", "sort_order": 18},
            {"code": "kaizen_event", "name": "Kaizen Event Shift", "sort_order": 19},
            {"code": "ucell_1_shift", "name": "U-Cell Single Shift", "sort_order": 20},
            {"code": "ucell_2_shift", "name": "U-Cell Two-Shift", "sort_order": 21},
            {"code": "jit_morning", "name": "JIT Morning Pulse", "sort_order": 22},
            {"code": "jit_afternoon", "name": "JIT Afternoon Pulse", "sort_order": 23},
            {"code": "smed_changeover", "name": "SMED / Changeover Shift", "sort_order": 24},
            {"code": "5s_tpm_morning", "name": "5S / TPM Morning Shift", "sort_order": 25},
            {"code": "andon_response", "name": "Andon Response Shift", "sort_order": 26},
            {"code": "yokoten", "name": "Yokoten / Best Practice", "sort_order": 27},
            {"code": "oee_day", "name": "OEE-Focused Day Shift", "sort_order": 28},
            {"code": "oee_night", "name": "OEE-Focused Night Shift", "sort_order": 29},
            {"code": "kanban_replenish", "name": "Kanban Replenishment Shift", "sort_order": 30},
            {"code": "wip_control", "name": "WIP Control Shift", "sort_order": 31},
        ],
    },
    "schedule": {
        "name": "Schedule",
        "description": "Named schedule patterns",
        "values": [
            {"code": "day_shift", "name": "Day Shift", "sort_order": 1},
            {"code": "morning_shift", "name": "Morning Shift", "sort_order": 2},
            {"code": "afternoon_shift", "name": "Afternoon Shift", "sort_order": 3},
            {"code": "night_shift", "name": "Night Shift", "sort_order": 4},
            {"code": "swing_shift", "name": "Swing Shift", "sort_order": 5},
        ],
    },
    "week_start_day": {
        "name": "Week Start Day",
        "description": "First day of the work week",
        "values": [
            {"code": "monday", "name": "Monday", "sort_order": 1},
            {"code": "sunday", "name": "Sunday", "sort_order": 2},
            {"code": "saturday", "name": "Saturday", "sort_order": 3},
        ],
    },
    "manufacturing_focus": {
        "name": "Manufacturing Focus",
        "description": "Manufacturing capabilities and focus areas",
        "values": [
            {"code": "liftgate_assembly", "name": "Liftgate Assembly", "sort_order": 1, "metadata": {"color": "blue"}},
            {"code": "machining", "name": "Machining", "sort_order": 2, "metadata": {"color": "slate"}},
            {"code": "welding", "name": "Welding", "sort_order": 3, "metadata": {"color": "amber"}},
            {"code": "painting", "name": "Painting", "sort_order": 4, "metadata": {"color": "violet"}},
            {"code": "harness", "name": "Harness", "sort_order": 5, "metadata": {"color": "cyan"}},
            {"code": "pipes", "name": "Pipes", "sort_order": 6, "metadata": {"color": "indigo"}},
            {"code": "assembly", "name": "Assembly", "sort_order": 7, "metadata": {"color": "emerald"}},
            {"code": "logistics", "name": "Logistics", "sort_order": 8, "metadata": {"color": "orange"}},
            {"code": "packaging", "name": "Packaging", "sort_order": 9, "metadata": {"color": "pink"}},
            {"code": "kitting", "name": "Kitting", "sort_order": 10, "metadata": {"color": "teal"}},
            {"code": "storage", "name": "Storage", "sort_order": 11, "metadata": {"color": "slate"}},
        ],
    },
    "industry_type": {
        "name": "Industry Type",
        "description": "Industry/business classification",
        "values": [
            {"code": "aerospace_defense", "name": "Aerospace & Defense", "sort_order": 1},
            {"code": "automotive", "name": "Automotive", "sort_order": 2},
            {"code": "automotive_tier1", "name": "Automotive Tier 1/2 Supplier", "sort_order": 3},
            {"code": "battery", "name": "Battery Manufacturing", "sort_order": 4},
            {"code": "biotech", "name": "Biotech / Life Sciences", "sort_order": 5},
            {"code": "chemical", "name": "Chemical Manufacturing", "sort_order": 6},
            {"code": "construction", "name": "Construction & Building", "sort_order": 7},
            {"code": "consumer_goods", "name": "Consumer Goods", "sort_order": 8},
            {"code": "defense", "name": "Defense Contracting", "sort_order": 9},
            {"code": "electronics", "name": "Electronics & Hi-Tech", "sort_order": 10},
            {"code": "energy", "name": "Energy & Utilities", "sort_order": 11},
            {"code": "food_beverage", "name": "Food & Beverage", "sort_order": 12},
            {"code": "foundry", "name": "Foundry & Forging", "sort_order": 13},
            {"code": "heavy_machinery", "name": "Industrial Machinery", "sort_order": 14},
            {"code": "logistics", "name": "Logistics & Distribution", "sort_order": 15},
            {"code": "marine", "name": "Marine & Shipbuilding", "sort_order": 16},
            {"code": "medical_devices", "name": "Medical Devices", "sort_order": 17},
            {"code": "metal_fab", "name": "Metal Fabrication", "sort_order": 18},
            {"code": "metals_mining", "name": "Metals & Mining", "sort_order": 19},
            {"code": "packaging", "name": "Packaging", "sort_order": 20},
            {"code": "pharma", "name": "Pharmaceutical", "sort_order": 21},
            {"code": "plastics_rubber", "name": "Plastics & Rubber", "sort_order": 22},
            {"code": "printing", "name": "Printing & Publishing", "sort_order": 23},
            {"code": "pulp_paper", "name": "Pulp & Paper", "sort_order": 24},
            {"code": "railway", "name": "Railway & Rolling Stock", "sort_order": 25},
            {"code": "semiconductor", "name": "Semiconductor", "sort_order": 26},
            {"code": "solar_renewable", "name": "Solar / Renewable Energy", "sort_order": 27},
            {"code": "textiles", "name": "Textiles & Apparel", "sort_order": 28},
            {"code": "tool_die", "name": "Tool & Die / Mold Making", "sort_order": 29},
            {"code": "wood_furniture", "name": "Wood & Furniture", "sort_order": 30},
        ],
    },
    "product_line": {
        "name": "Product Line",
        "description": "Product lines and categories",
        "values": [
            {"code": "liftgates", "name": "Liftgates", "sort_order": 1},
            {"code": "rail_liftgates", "name": "Rail Liftgates", "sort_order": 2},
            {"code": "tuckunder", "name": "TuckUnder", "sort_order": 3},
            {"code": "flipaway", "name": "FlipAway", "sort_order": 4},
            {"code": "accessories", "name": "Accessories", "sort_order": 5},
        ],
    },
    "production_family": {
        "name": "Product Family",
        "description": "Liftgate product families from Maxon Lift Corp.",
        "values": [
            {"code": "CHARGING", "name": "Charging Solutions", "sort_order": 1},
            {"code": "COLUMNLIFT", "name": "COLUMNLIFT™", "sort_order": 2},
            {"code": "CONVENTIONAL", "name": "Conventional", "sort_order": 3},
            {"code": "GAS_BOTTLE", "name": "Gas Bottle", "sort_order": 4},
            {"code": "LIGHT_DUTY", "name": "Light Duty", "sort_order": 5},
            {"code": "MAXLINK", "name": "MAX LINK® (OBD)", "sort_order": 6},
            {"code": "RAILIFT", "name": "RAILIFT™", "sort_order": 7},
            {"code": "SLIDELIFT", "name": "SLIDELIFT®", "sort_order": 8},
            {"code": "TUKAWAY", "name": "TUK-A-WAY®", "sort_order": 9},
        ],
    },
    "unit_of_measure": {
        "name": "Unit of Measure",
        "description": "Units for production line capacity",
        "values": [
            {"code": "units_per_shift", "name": "Units / Shift", "sort_order": 1},
            {"code": "units_per_hour", "name": "Units / Hour", "sort_order": 2},
            {"code": "hours", "name": "Hours", "sort_order": 3},
            {"code": "pieces", "name": "Pieces", "sort_order": 4},
        ],
    },
    "lean_methodology": {
        "name": "Lean Methodology",
        "description": "Lean manufacturing methodologies",
        "values": [
            {"code": "kaizen", "name": "Kaizen", "sort_order": 1, "metadata": {"color": "emerald"}},
            {"code": "kanban", "name": "Kanban", "sort_order": 2, "metadata": {"color": "blue"}},
            {"code": "5s", "name": "5S", "sort_order": 3, "metadata": {"color": "amber"}},
            {"code": "tpm", "name": "TPM", "sort_order": 4, "metadata": {"color": "violet"}},
            {"code": "six_sigma", "name": "Six Sigma", "sort_order": 5, "metadata": {"color": "cyan"}},
            {"code": "value_stream", "name": "Value Stream Mapping", "sort_order": 6, "metadata": {"color": "indigo"}},
            {"code": "jit", "name": "Just-In-Time", "sort_order": 7, "metadata": {"color": "rose"}},
            {"code": "poka_yoke", "name": "Poka-Yoke", "sort_order": 8, "metadata": {"color": "orange"}},
        ],
    },
    "department_type": {
        "name": "Department Type",
        "description": "Types of departments within a production structure",
        "values": [
            {"code": "production", "name": "Production", "sort_order": 1, "metadata": {"color": "blue"}},
            {"code": "quality", "name": "Quality", "sort_order": 2, "metadata": {"color": "emerald"}},
            {"code": "maintenance", "name": "Maintenance", "sort_order": 3, "metadata": {"color": "amber"}},
            {"code": "logistics", "name": "Logistics", "sort_order": 4, "metadata": {"color": "violet"}},
            {"code": "engineering", "name": "Engineering", "sort_order": 5, "metadata": {"color": "cyan"}},
            {"code": "warehouse", "name": "Warehouse", "sort_order": 6, "metadata": {"color": "indigo"}},
        ],
    },
    "resource_group_type": {
        "name": "Resource Group Type",
        "description": "Types/categories of resource groups",
        "values": [
            {"code": "production", "name": "Production", "sort_order": 1, "metadata": {"color": "blue"}},
            {"code": "support", "name": "Support", "sort_order": 2, "metadata": {"color": "emerald"}},
            {"code": "management", "name": "Management", "sort_order": 3, "metadata": {"color": "amber"}},
            {"code": "quality", "name": "Quality", "sort_order": 4, "metadata": {"color": "violet"}},
            {"code": "logistics", "name": "Logistics", "sort_order": 5, "metadata": {"color": "cyan"}},
        ],
    },
    "resource_type": {
        "name": "Resource Type",
        "description": "Types of resources (equipment, personnel, etc.)",
        "values": [
            {"code": "equipment", "name": "Equipment", "sort_order": 1, "metadata": {"color": "blue", "icon": "cog"}},
            {"code": "machine", "name": "Machine", "sort_order": 2, "metadata": {"color": "amber", "icon": "cpu"}},
            {"code": "tool", "name": "Tool", "sort_order": 3, "metadata": {"color": "emerald", "icon": "wrench"}},
            {"code": "personnel", "name": "Personnel", "sort_order": 4, "metadata": {"color": "violet", "icon": "users"}},
            {"code": "workstation", "name": "Workstation", "sort_order": 5, "metadata": {"color": "cyan", "icon": "component"}},
            {"code": "vehicle", "name": "Vehicle", "sort_order": 6, "metadata": {"color": "indigo", "icon": "truck"}},
        ],
    },
    "resource_capability": {
        "name": "Resource Capability",
        "description": "Capabilities and skills a resource can have",
        "values": [
            {"code": "welding", "name": "Welding", "sort_order": 1, "metadata": {"color": "amber"}},
            {"code": "assembly", "name": "Assembly", "sort_order": 2, "metadata": {"color": "blue"}},
            {"code": "painting", "name": "Painting", "sort_order": 3, "metadata": {"color": "violet"}},
            {"code": "inspection", "name": "Inspection", "sort_order": 4, "metadata": {"color": "emerald"}},
            {"code": "packaging", "name": "Packaging", "sort_order": 5, "metadata": {"color": "cyan"}},
            {"code": "forklift", "name": "Forklift Operation", "sort_order": 6, "metadata": {"color": "orange"}},
            {"code": "cnc", "name": "CNC Operation", "sort_order": 7, "metadata": {"color": "indigo"}},
            {"code": "quality_check", "name": "Quality Check", "sort_order": 8, "metadata": {"color": "rose"}},
        ],
    },
    "product_model": {
        "name": "Product Model",
        "description": "Liftgate models and products from Maxon Lift Corp.",
        "values": [
            {"code": "BMR", "name": "BMR Columnlift", "sort_order": 1, "metadata": {"family": "COLUMNLIFT"}},
            {"code": "BMR-CS", "name": "BMR-CS Columnlift Gas Bottle", "sort_order": 2, "metadata": {"family": "COLUMNLIFT"}},
            {"code": "C2-DMP", "name": "C2 Dump Through Liftgate", "sort_order": 3, "metadata": {"family": "LIGHT_DUTY"}},
            {"code": "C2-PU", "name": "C2 Pickup Liftgate", "sort_order": 4, "metadata": {"family": "LIGHT_DUTY"}},
            {"code": "C2-SB", "name": "C2 Service Body Liftgate", "sort_order": 5, "metadata": {"family": "LIGHT_DUTY"}},
            {"code": "C2-STK", "name": "C2 Stakebed & Van Body Liftgate", "sort_order": 6, "metadata": {"family": "LIGHT_DUTY"}},
            {"code": "DMD", "name": "DMD Medium-Duty Railift", "sort_order": 7, "metadata": {"family": "RAILIFT"}},
            {"code": "DMD-DIB", "name": "DMD with Dock Impact Bumpers", "sort_order": 8, "metadata": {"family": "RAILIFT"}},
            {"code": "DMD-TT", "name": "DMD Tool Truck Railift", "sort_order": 9, "metadata": {"family": "RAILIFT"}},
            {"code": "GPC-X1", "name": "GPC 17/22 X1 Conventional", "sort_order": 10, "metadata": {"family": "CONVENTIONAL"}},
            {"code": "GPC-X1-LDF", "name": "GPC X1-LDF Cargo Van Liftgate", "sort_order": 11, "metadata": {"family": "CONVENTIONAL"}},
            {"code": "GPC-X4", "name": "GPC 33/44 X4 Conventional", "sort_order": 12, "metadata": {"family": "CONVENTIONAL"}},
            {"code": "GPS", "name": "GPS High Capacity Slidelift", "sort_order": 13, "metadata": {"family": "SLIDELIFT"}},
            {"code": "GPSLR", "name": "GPSLR Level-Ride Slidelift", "sort_order": 14, "metadata": {"family": "SLIDELIFT"}},
            {"code": "GPSLRT", "name": "GPSLRT Level-Ride Tandem Slidelift", "sort_order": 15, "metadata": {"family": "SLIDELIFT"}},
            {"code": "GPST", "name": "GPST Tandem-Axle Slidelift", "sort_order": 16, "metadata": {"family": "SLIDELIFT"}},
            {"code": "GPT", "name": "GPT Heavy-Duty Tuk-A-Way", "sort_order": 17, "metadata": {"family": "TUKAWAY"}},
            {"code": "GPTLR", "name": "GPTLR Level-Ride Tuk-A-Way", "sort_order": 18, "metadata": {"family": "TUKAWAY"}},
            {"code": "GPTWR", "name": "GPTWR World's #1 Selling Liftgate", "sort_order": 19, "metadata": {"family": "TUKAWAY"}},
            {"code": "MAXLINK", "name": "MAX LINK® On Board Diagnostic", "sort_order": 20, "metadata": {"family": "MAXLINK"}},
            {"code": "MERLIN-SOL", "name": "Merlin Solar Charging (MAX SOL)", "sort_order": 21, "metadata": {"family": "CHARGING"}},
            {"code": "MLA", "name": "MLA Light Duty Liftgate", "sort_order": 22, "metadata": {"family": "LIGHT_DUTY"}},
            {"code": "MXT-25", "name": "MXT-25 Low Bedheight Tuk-A-Way", "sort_order": 23, "metadata": {"family": "TUKAWAY"}},
            {"code": "MXT-33", "name": "MXT-33 Low Bedheight Tuk-A-Way", "sort_order": 24, "metadata": {"family": "TUKAWAY"}},
            {"code": "PHIL-KIT1", "name": "Phillips Smart-Charge Kit 1", "sort_order": 25, "metadata": {"family": "CHARGING"}},
            {"code": "PHIL-KIT2", "name": "Phillips Smart-Charge Kit 2", "sort_order": 26, "metadata": {"family": "CHARGING"}},
            {"code": "PHIL-VCHK", "name": "Phillips V-Check", "sort_order": 27, "metadata": {"family": "CHARGING"}},
            {"code": "PURKEYS-DIR", "name": "Purkeys Direct™ Charging System", "sort_order": 28, "metadata": {"family": "CHARGING"}},
            {"code": "PURKEYS-SEL", "name": "Purkeys Select™ Charging System", "sort_order": 29, "metadata": {"family": "CHARGING"}},
            {"code": "PURKEYS-STS", "name": "Purkeys Status Battery Indicator", "sort_order": 30, "metadata": {"family": "CHARGING"}},
            {"code": "RA", "name": "RA Trailer Side Door Slidelift", "sort_order": 31, "metadata": {"family": "SLIDELIFT"}},
            {"code": "RC", "name": "RC Heavy-Duty Level-Ride Railift", "sort_order": 32, "metadata": {"family": "RAILIFT"}},
            {"code": "RC-CS", "name": "RC-CS Railift Gas Bottle", "sort_order": 33, "metadata": {"family": "RAILIFT"}},
            {"code": "RCT", "name": "RCT Railift with Dock-Ready Platform", "sort_order": 34, "metadata": {"family": "RAILIFT"}},
            {"code": "TE-20", "name": "TE-20 Tuk-A-Way", "sort_order": 35, "metadata": {"family": "TUKAWAY"}},
            {"code": "TE-25", "name": "TE-25/TE-30 Tuk-A-Way", "sort_order": 36, "metadata": {"family": "TUKAWAY"}},
            {"code": "TE-33", "name": "TE-33 Medium-Duty Tuk-A-Way", "sort_order": 37, "metadata": {"family": "TUKAWAY"}},
        ],
    },
    "container_type": {
        "name": "Container Type",
        "description": "Material handling container types used for storage, transport, and workstation organization",
        "values": [
            {"code": "TOTE", "name": "Tote Box", "description": "Standard plastic tote for small-to-medium parts, stackable with lid options", "usage_context": "Material handling, workstation storage", "sort_order": 10, "metadata": {"color": "blue"}},
            {"code": "BIN", "name": "Bin", "description": "Small parts bin for organized component storage on workstations and shelving", "usage_context": "Workstation organization, small parts storage", "sort_order": 15, "metadata": {"color": "emerald"}},
            {"code": "BSKT", "name": "Basket", "description": "Wire or plastic basket for parts handling, good for heat treatment or washing", "usage_context": "Parts handling, process transport", "sort_order": 18, "metadata": {"color": "amber"}},
            {"code": "PALLET", "name": "Pallet", "description": "Standard shipping pallet (48x40 or EUR) for bulk material transport and storage", "usage_context": "Bulk transport, warehouse storage", "sort_order": 20, "metadata": {"color": "orange"}},
            {"code": "RACK", "name": "Rack", "description": "Purpose-built material handling rack for specialized part geometries", "usage_context": "Material handling, specialty parts", "sort_order": 25, "metadata": {"color": "violet"}},
            {"code": "BOX", "name": "Corrugated Box", "description": "Cardboard or corrugated box for lightweight parts and finished goods", "usage_context": "Packaging, finished goods", "sort_order": 28, "metadata": {"color": "cyan"}},
            {"code": "CRATE", "name": "Wooden Crate", "description": "Heavy-duty wooden crate for large or heavy parts and equipment", "usage_context": "Heavy parts, equipment transport", "sort_order": 30, "metadata": {"color": "indigo"}},
            {"code": "DRUM", "name": "Drum", "description": "55-gallon or 30-gallon drum for liquids, powders, and bulk materials", "usage_context": "Liquids, bulk materials storage", "sort_order": 35, "metadata": {"color": "rose"}},
            {"code": "IBC", "name": "IBC Tote", "description": "Intermediate Bulk Container (275-330 gal) for liquids and bulk materials", "usage_context": "Bulk liquids, chemical storage", "sort_order": 40, "metadata": {"color": "slate"}},
            {"code": "CART", "name": "Rolling Cart", "description": "Rolling cart for in-process material movement between workstations", "usage_context": "In-process material movement", "sort_order": 45, "metadata": {"color": "blue"}},
            {"code": "HOPPER", "name": "Hopper", "description": "Hopper or tote for bulk material dispensing of consumables and small parts", "usage_context": "Bulk dispensing, consumables", "sort_order": 50, "metadata": {"color": "emerald"}},
            {"code": "SILO", "name": "Silo", "description": "Outdoor or indoor silo for bulk raw material storage of grains, pellets, powders", "usage_context": "Bulk raw material storage", "sort_order": 55, "metadata": {"color": "amber"}},
            {"code": "TANK", "name": "Tank", "description": "Storage tank for liquids, chemicals, and bulk fluids", "usage_context": "Liquid storage, chemical storage", "sort_order": 60, "metadata": {"color": "orange"}},
            {"code": "GONDOLA", "name": "Gondola", "description": "Large metal gondola for heavy bulk parts and scrap material", "usage_context": "Heavy bulk parts, scrap handling", "sort_order": 65, "metadata": {"color": "violet"}},
            {"code": "DUNNAGE", "name": "Dunnage Tray", "description": "Custom-molded dunnage tray for protecting sensitive parts during transport", "usage_context": "Sensitive parts, protective transport", "sort_order": 70, "metadata": {"color": "cyan"}},
        ],
    },
}


class Command(BaseCommand):
    help = "Seed all reference categories and values for the production structure"

    def handle(self, *args, **options):
        for cat_code, cat_data in CATEGORIES.items():
            cat, created = ReferenceCategory.objects.update_or_create(
                code=cat_code,
                defaults={
                    "name": cat_data["name"],
                    "description": cat_data["description"],
                },
            )
            if created:
                self.stdout.write(f"  Created category: {cat.name}")
            else:
                self.stdout.write(f"  Updated category: {cat.name}")

            if cat_code == "language_locale":
                source_cat = ReferenceCategory.objects.get(code="language")
                for rv in ReferenceValue.objects.filter(category=source_cat):
                    ReferenceValue.objects.update_or_create(
                        category=cat,
                        code=rv.code,
                        defaults={
                            "name": rv.name,
                            "sort_order": rv.sort_order,
                            "is_active": rv.is_active,
                            "metadata": rv.metadata,
                        },
                    )
                self.stdout.write(f"    Cloned {source_cat.values.count()} values from language")

            for val_data in cat_data["values"]:
                metadata = val_data.get("metadata", {})
                defaults: dict = {
                    "name": val_data["name"],
                    "sort_order": val_data.get("sort_order", 0),
                    "is_active": True,
                    "metadata": metadata,
                }
                if "description" in val_data:
                    defaults["description"] = val_data["description"]
                if "usage_context" in val_data:
                    defaults["usage_context"] = val_data["usage_context"]
                val, val_created = ReferenceValue.objects.update_or_create(
                    category=cat,
                    code=val_data["code"],
                    defaults=defaults,
                )
                if val_created:
                    self.stdout.write(f"    Created value: {val.name}")

        self.stdout.write(self.style.SUCCESS("References seeded successfully!"))
