# Generated by Django 6.0.4 on 2026-05-04 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Plant Code')),
                ('name', models.CharField(max_length=200, verbose_name='Plant Name')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('building', models.CharField(blank=True, default='', max_length=200)),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('timezone', models.CharField(blank=True, default='', max_length=100)),
                ('default_calendar_id', models.CharField(blank=True, max_length=50, null=True)),
                ('default_schedule_id', models.CharField(blank=True, max_length=50, null=True)),
                ('manager_name', models.CharField(blank=True, default='', max_length=200)),
                ('manager_email', models.EmailField(blank=True, default='', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('line_count', models.IntegerField(default=0)),
                ('department_count', models.IntegerField(default=0)),
                ('group_count', models.IntegerField(default=0)),
                ('resource_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Plant',
                'verbose_name_plural': 'Plants',
                'db_table': 'manufacturing_plant',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Table Name')),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('entry_count', models.IntegerField(default=0, verbose_name='Number of entries')),
            ],
            options={
                'verbose_name': 'Reference Table',
                'verbose_name_plural': 'Reference Tables',
                'db_table': 'manufacturing_reference_table',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Department Code')),
                ('name', models.CharField(max_length=200, verbose_name='Department Name')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('manager', models.CharField(blank=True, default='', max_length=200)),
                ('employees', models.IntegerField(default=0)),
                ('group_count', models.IntegerField(default=0)),
                ('resource_count', models.IntegerField(default=0)),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='manufacturing.plant')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'manufacturing_department',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Line Name')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('models_produced', models.TextField(blank=True, default='', help_text='Comma-separated list of models')),
                ('shift_pattern', models.CharField(blank=True, default='', max_length=100)),
                ('is_constraint', models.BooleanField(default=False)),
                ('department_count', models.IntegerField(default=0)),
                ('group_count', models.IntegerField(default=0)),
                ('resource_count', models.IntegerField(default=0)),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_lines', to='manufacturing.plant')),
            ],
            options={
                'verbose_name': 'Production Line',
                'verbose_name_plural': 'Production Lines',
                'db_table': 'manufacturing_production_line',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResourceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Group Name')),
                ('group_type', models.CharField(choices=[('Production', 'Production'), ('Support', 'Support'), ('Quality', 'Quality'), ('Logistics', 'Logistics'), ('Management', 'Management')], default='Production', max_length=50, verbose_name='Type')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('members', models.IntegerField(default=0)),
                ('leader', models.CharField(blank=True, default='', max_length=200)),
                ('resource_count', models.IntegerField(default=0)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_groups', to='manufacturing.department')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_groups', to='manufacturing.plant')),
            ],
            options={
                'verbose_name': 'Resource Group',
                'verbose_name_plural': 'Resource Groups',
                'db_table': 'manufacturing_resource_group',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Resource Name')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Resource Code')),
                ('resource_type', models.CharField(choices=[('Machine', 'Machine'), ('Workstation', 'Workstation'), ('Inspection Station', 'Inspection Station'), ('Material Handling', 'Material Handling'), ('Tool', 'Tool')], default='Machine', max_length=50, verbose_name='Type')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('op_status', models.CharField(choices=[('Running', 'Running'), ('Idle', 'Idle'), ('Down', 'Down'), ('Maintenance', 'Maintenance')], default='Idle', max_length=50, verbose_name='Operational Status')),
                ('utilization', models.FloatField(default=0.0)),
                ('shift', models.CharField(blank=True, default='', max_length=100)),
                ('last_activity', models.CharField(blank=True, default='', max_length=100)),
                ('flow_position', models.CharField(blank=True, default='', max_length=100)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='manufacturing.department')),
                ('plant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='manufacturing.plant')),
                ('production_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='manufacturing.productionline')),
                ('resource_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='manufacturing.resourcegroup')),
            ],
            options={
                'verbose_name': 'Resource',
                'verbose_name_plural': 'Resources',
                'db_table': 'manufacturing_resource',
                'ordering': ['name'],
            },
        ),
    ]
