# Generated by Django 6.0.4 on 2026-05-05 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0003_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='timezone',
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='profile',
            name='reports_to',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='productionline',
            name='code',
            field=models.CharField(max_length=20, verbose_name='Line Code'),
        ),
        migrations.AlterField(
            model_name='productionline',
            name='plant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_lines', to='manufacturing.plant'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='manufacturing.resourcegroup'),
        ),
    ]
