# Generated by Django 6.0.4 on 2026-05-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0004_remove_profile_timezone_profile_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='plant',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
