# Generated by Django 6.0.4 on 2026-05-09 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0011_remove_company_tax_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcegroup',
            name='plant',
        ),
    ]
