# Generated by Django 6.0.4 on 2026-05-09 23:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0012_remove_resourcegroup_plant'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Model',
                'verbose_name_plural': 'Product Models',
                'db_table': 'manufacturing_product_model',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReferenceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Reference Category',
                'verbose_name_plural': 'Reference Categories',
                'db_table': 'manufacturing_reference_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resource Type',
                'verbose_name_plural': 'Resource Types',
                'db_table': 'manufacturing_resource_type',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'db_table': 'manufacturing_schedule',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='company',
            name='default_language',
        ),
        migrations.RemoveField(
            model_name='company',
            name='default_shift_model',
        ),
        migrations.RemoveField(
            model_name='company',
            name='default_units',
        ),
        migrations.RemoveField(
            model_name='company',
            name='industry_type',
        ),
        migrations.RemoveField(
            model_name='company',
            name='lean_methodology',
        ),
        migrations.RemoveField(
            model_name='company',
            name='manufacturing_type',
        ),
        migrations.RemoveField(
            model_name='company',
            name='production_calendar',
        ),
        migrations.RemoveField(
            model_name='department',
            name='group_count',
        ),
        migrations.RemoveField(
            model_name='department',
            name='resource_count',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='default_calendar_id',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='default_schedule_id',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='department_count',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='group_count',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='line_count',
        ),
        migrations.RemoveField(
            model_name='plant',
            name='resource_count',
        ),
        migrations.RemoveField(
            model_name='productionline',
            name='department_count',
        ),
        migrations.RemoveField(
            model_name='productionline',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='productionline',
            name='group_count',
        ),
        migrations.RemoveField(
            model_name='productionline',
            name='models_produced',
        ),
        migrations.RemoveField(
            model_name='productionline',
            name='resource_count',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='flow_position',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='last_activity',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='op_status',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='resource_type',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='shift',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='utilization',
        ),
        migrations.RemoveField(
            model_name='resourcegroup',
            name='group_type',
        ),
        migrations.RemoveField(
            model_name='resourcegroup',
            name='resource_count',
        ),
        migrations.AddField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='productionline',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resource',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resourcegroup',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='department',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='plant',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='plant',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='productionline',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productionline',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='productionline',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='resource',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='resourcegroup',
            name='code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='resourcegroup',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='resourcegroup',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20),
        ),
        migrations.CreateModel(
            name='ProcessFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('version', models.CharField(blank=True, default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('production_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_flows', to='manufacturing.productionline')),
                ('product_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='process_flows', to='manufacturing.productmodel')),
            ],
            options={
                'verbose_name': 'Process Flow',
                'verbose_name_plural': 'Process Flows',
                'db_table': 'manufacturing_process_flow',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('entity_type', models.CharField(choices=[('DEPARTMENT', 'Department'), ('RESOURCE_GROUP', 'Resource Group'), ('RESOURCE', 'Resource')], max_length=30)),
                ('entity_id', models.CharField(max_length=50)),
                ('lead_time_minutes', models.FloatField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('process_flow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='manufacturing.processflow')),
            ],
            options={
                'verbose_name': 'Process Step',
                'verbose_name_plural': 'Process Steps',
                'db_table': 'manufacturing_process_step',
                'ordering': ['process_flow', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='manufacturing.schedule')),
            ],
            options={
                'verbose_name': 'Shift',
                'verbose_name_plural': 'Shifts',
                'db_table': 'manufacturing_shift',
                'ordering': ['schedule', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='VisualIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.CharField(max_length=50)),
                ('icon_key', models.CharField(blank=True, default='', max_length=100)),
                ('color_key', models.CharField(blank=True, default='', max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Visual Identity',
                'verbose_name_plural': 'Visual Identities',
                'db_table': 'manufacturing_visual_identity',
                'unique_together': {('entity_type', 'entity_id')},
            },
        ),
        migrations.CreateModel(
            name='ProductionLineDepartmentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_assignments', to='manufacturing.department')),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_assignments', to='manufacturing.productionline')),
            ],
            options={
                'verbose_name': 'Line-Department Assignment',
                'verbose_name_plural': 'Line-Department Assignments',
                'db_table': 'manufacturing_production_line_department',
                'ordering': ['production_line', 'sequence'],
                'unique_together': {('production_line', 'department')},
            },
        ),
        migrations.CreateModel(
            name='ReferenceValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='manufacturing.referencecategory')),
            ],
            options={
                'verbose_name': 'Reference Value',
                'verbose_name_plural': 'Reference Values',
                'db_table': 'manufacturing_reference_value',
                'ordering': ['category', 'sort_order', 'name'],
                'unique_together': {('category', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ScheduleAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('RESOURCE', 'Resource'), ('RESOURCE_GROUP', 'Resource Group'), ('DEPARTMENT', 'Department'), ('PRODUCTION_LINE', 'Production Line'), ('PLANT', 'Plant'), ('COMPANY', 'Company')], max_length=30)),
                ('entity_id', models.CharField(max_length=50)),
                ('inheritance_mode', models.CharField(choices=[('NONE', 'None'), ('PARENT', 'Inherit from parent'), ('CHILDREN', 'Apply to children'), ('BOTH', 'Both directions')], default='NONE', max_length=20)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='manufacturing.schedule')),
            ],
            options={
                'verbose_name': 'Schedule Assignment',
                'verbose_name_plural': 'Schedule Assignments',
                'db_table': 'manufacturing_schedule_assignment',
                'ordering': ['entity_type', 'entity_id'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='manufacturi_entity__c7655d_idx')],
            },
        ),
    ]
