# Generated by Django 6.0.4 on 2026-05-10 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0016_plant_extended_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='country_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='manufacturing.referencevalue'),
        ),
        migrations.AddField(
            model_name='company',
            name='default_timezone_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='manufacturing.referencevalue'),
        ),
        migrations.AddField(
            model_name='company',
            name='manufacturing_focus',
            field=models.ManyToManyField(blank=True, related_name='companies_focus', to='manufacturing.referencevalue'),
        ),
        migrations.AddField(
            model_name='company',
            name='status_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='manufacturing.referencevalue'),
        ),
        migrations.AddField(
            model_name='department',
            name='department_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='manufacturing.referencevalue'),
        ),
        migrations.AddField(
            model_name='department',
            name='status_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='manufacturing.referencevalue'),
        ),
        migrations.AddField(
            model_name='plant',
            name='country_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='manufacturing.referencevalue'),
        ),
        migrations.AddField(
            model_name='plant',
            name='default_calendar_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='manufacturing.referencevalue'),
        ),
        migrations.AddField(
            model_name='plant',
            name='default_schedule_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='manufacturing.referencevalue'),
        ),
        migrations.AddField(
            model_name='plant',
            name='default_shift_model_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='manufacturing.referencevalue'),
        ),
        migrations.AddField(
            model_name='plant',
            name='manufacturing_focus_refs',
            field=models.ManyToManyField(blank=True, related_name='plants_focus', to='manufacturing.referencevalue'),
        ),
        migrations.AddField(
            model_name='plant',
            name='plant_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='manufacturing.referencevalue'),
        ),
        migrations.AddField(
            model_name='plant',
            name='status_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='manufacturing.referencevalue'),
        ),
        migrations.AddField(
            model_name='plant',
            name='timezone_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='manufacturing.referencevalue'),
        ),
        migrations.AddField(
            model_name='plant',
            name='week_start_day_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='manufacturing.referencevalue'),
        ),
        migrations.AddField(
            model_name='productionline',
            name='shift_pattern_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='manufacturing.referencevalue'),
        ),
        migrations.AddField(
            model_name='productionline',
            name='status_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='manufacturing.referencevalue'),
        ),
        migrations.AddField(
            model_name='referencevalue',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='resource',
            name='capabilities',
            field=models.ManyToManyField(blank=True, related_name='resources_with_capability', to='manufacturing.referencevalue'),
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='manufacturing.referencevalue'),
        ),
        migrations.AddField(
            model_name='resource',
            name='status_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='manufacturing.referencevalue'),
        ),
        migrations.AddField(
            model_name='resourcegroup',
            name='group_type_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='manufacturing.referencevalue'),
        ),
        migrations.AddField(
            model_name='resourcegroup',
            name='status_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='manufacturing.referencevalue'),
        ),
    ]
