# Generated by Django 6.0.4

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0018_company_admin_name_company_admin_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='default_calendar_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='manufacturing.referencevalue'),
        ),
        migrations.AddField(
            model_name='company',
            name='week_start_day_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='manufacturing.referencevalue'),
        ),
        migrations.AddField(
            model_name='company',
            name='product_line_refs',
            field=models.ManyToManyField(blank=True, related_name='company_product_lines', to='manufacturing.referencevalue'),
        ),
        migrations.AddField(
            model_name='company',
            name='lean_methodology_refs',
            field=models.ManyToManyField(blank=True, related_name='company_lean_methodologies', to='manufacturing.referencevalue'),
        ),
    ]
