# Generated by Django 6.0.4 on 2026-05-13 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0021_productionline_detail_refs'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=20)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('product_family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='manufacturing.referencevalue')),
                ('product_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routings', to='manufacturing.productmodel')),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routings', to='manufacturing.productionline')),
            ],
            options={
                'verbose_name': 'Routing',
                'verbose_name_plural': 'Routings',
                'db_table': 'manufacturing_routing',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoutingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.IntegerField(db_index=True)),
                ('cycle_time_sec', models.FloatField(default=0)),
                ('setup_time_sec', models.FloatField(blank=True, default=0, null=True)),
                ('changeover_time_sec', models.FloatField(blank=True, default=0, null=True)),
                ('required_operators', models.IntegerField(blank=True, default=1, null=True)),
                ('schedule_source', models.CharField(choices=[('PLANT', 'Plant'), ('LINE', 'Line'), ('DEPARTMENT', 'Department'), ('RESOURCE_GROUP', 'Resource Group'), ('RESOURCE', 'Resource'), ('CUSTOM', 'Custom')], default='LINE', max_length=20)),
                ('buffer_type', models.CharField(blank=True, max_length=50, null=True)),
                ('wip_min', models.IntegerField(blank=True, null=True)),
                ('wip_max', models.IntegerField(blank=True, null=True)),
                ('quality_checkpoint', models.BooleanField(default=False)),
                ('rework_allowed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_steps', to='manufacturing.department')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_steps', to='manufacturing.resource')),
                ('resource_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_steps', to='manufacturing.resourcegroup')),
                ('routing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='manufacturing.routing')),
                ('standard_work', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routing_steps', to='manufacturing.processflow')),
            ],
            options={
                'verbose_name': 'Routing Step',
                'verbose_name_plural': 'Routing Steps',
                'db_table': 'manufacturing_routing_step',
                'ordering': ['routing', 'sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='routing',
            index=models.Index(fields=['production_line', 'status'], name='manufacturi_product_5cd516_idx'),
        ),
        migrations.AddIndex(
            model_name='routing',
            index=models.Index(fields=['production_line', 'product_model'], name='manufacturi_product_eda8be_idx'),
        ),
        migrations.AddIndex(
            model_name='routing',
            index=models.Index(fields=['production_line', 'product_family'], name='manufacturi_product_bfdb85_idx'),
        ),
        migrations.AddIndex(
            model_name='routingstep',
            index=models.Index(fields=['routing', 'sequence'], name='manufacturi_routing_b1e663_idx'),
        ),
        migrations.AddConstraint(
            model_name='routingstep',
            constraint=models.UniqueConstraint(fields=('routing', 'sequence'), name='uq_routing_step_sequence'),
        ),
    ]
