# Generated by Django 6.0.4 on 2026-05-13 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0022_routing_routingstep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionline',
            name='product_model_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='manufacturing.referencevalue'),
        ),
    ]
