# Generated by Django 6.0.4 on 2026-05-13 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0023_department_indexes'),
        ('manufacturing', '0023_productionline_product_model_id'),
    ]

    operations = [
    ]
