# Generated by Django 6.0.4 on 2026-05-13 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0024_merge_20260513_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionline',
            name='product_model_id',
        ),
        migrations.RemoveField(
            model_name='productionline',
            name='product_models',
        ),
        migrations.RemoveField(
            model_name='productionline',
            name='production_family_id',
        ),
        migrations.CreateModel(
            name='ProductionLineProductFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('product_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pl_family_assignments', to='manufacturing.referencevalue')),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_assignments', to='manufacturing.productionline')),
            ],
            options={
                'verbose_name': 'Line-Family Assignment',
                'verbose_name_plural': 'Line-Family Assignments',
                'db_table': 'manufacturing_production_line_family',
                'ordering': ['production_line', 'product_family__name'],
                'indexes': [models.Index(fields=['production_line', 'product_family'], name='manufacturi_product_057854_idx'), models.Index(fields=['production_line', 'status'], name='manufacturi_product_a74197_idx')],
                'constraints': [models.UniqueConstraint(fields=('production_line', 'product_family'), name='uq_pl_family')],
            },
        ),
        migrations.CreateModel(
            name='ProductionLineProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('product_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pl_model_family_assignments', to='manufacturing.referencevalue')),
                ('product_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pl_model_assignments', to='manufacturing.referencevalue')),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_assignments', to='manufacturing.productionline')),
            ],
            options={
                'verbose_name': 'Line-Model Assignment',
                'verbose_name_plural': 'Line-Model Assignments',
                'db_table': 'manufacturing_production_line_model',
                'ordering': ['production_line', 'product_model__name'],
                'indexes': [models.Index(fields=['production_line', 'product_model'], name='manufacturi_product_adffeb_idx'), models.Index(fields=['production_line', 'product_family'], name='manufacturi_product_0e0c7a_idx'), models.Index(fields=['production_line', 'status'], name='manufacturi_product_3d0a66_idx')],
                'constraints': [models.UniqueConstraint(fields=('production_line', 'product_model'), name='uq_pl_model')],
            },
        ),
    ]
