# Generated by Django 6.0.4 on 2026-05-14 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0030_relation_integrity_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='referencevalue',
            name='is_configurable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='referencevalue',
            name='is_system_managed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referencevalue',
            name='usage_context',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='referencevalue',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
