# Generated by Django 6.0.4 on 2026-05-15 07:33

from django.db import migrations, models


def drop_legacy_assignment_unique(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT COUNT(*)
            FROM information_schema.statistics
            WHERE table_schema = DATABASE()
              AND table_name = 'manufacturing_production_line_department'
              AND index_name = 'manufacturing_production_production_line_id_depar_49f3e56d_uniq'
            """
        )
        if cursor.fetchone()[0]:
            cursor.execute(
                """
                ALTER TABLE manufacturing_production_line_department
                DROP INDEX manufacturing_production_production_line_id_depar_49f3e56d_uniq
                """
            )


def remove_legacy_resource_department_column(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(
            """
            SELECT constraint_name
            FROM information_schema.key_column_usage
            WHERE table_schema = DATABASE()
              AND table_name = 'manufacturing_resource'
              AND column_name = 'department_id'
              AND referenced_table_name IS NOT NULL
            """
        )
        for (constraint_name,) in cursor.fetchall():
            cursor.execute(f"ALTER TABLE manufacturing_resource DROP FOREIGN KEY {constraint_name}")
        cursor.execute(
            """
            SELECT COUNT(*)
            FROM information_schema.columns
            WHERE table_schema = DATABASE()
              AND table_name = 'manufacturing_resource'
              AND column_name = 'department_id'
            """
        )
        if cursor.fetchone()[0]:
            cursor.execute("ALTER TABLE manufacturing_resource DROP COLUMN department_id")


def repair_duplicate_names(apps, schema_editor):
    def dedupe(model_name, scope_fields):
        Model = apps.get_model("manufacturing", model_name)
        seen = {}
        for obj in Model.objects.order_by(*(scope_fields + ["name", "id"])):
            scope = tuple(getattr(obj, f"{field}_id", getattr(obj, field, None)) for field in scope_fields)
            key = scope + ((obj.name or "").strip().casefold(),)
            if key not in seen:
                seen[key] = 1
                continue
            seen[key] += 1
            suffix = (getattr(obj, "code", "") or str(obj.id)).strip() or str(obj.id)
            base_name = (obj.name or model_name).strip() or model_name
            obj.name = f"{base_name} ({suffix})"
            obj.save(update_fields=["name"])

    dedupe("Company", [])
    dedupe("Plant", ["company"])
    dedupe("ProductionLine", ["plant"])
    dedupe("Department", ["plant"])
    dedupe("ResourceGroup", ["department"])
    dedupe("Resource", ["resource_group"])


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0036_resource_department_field'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(drop_legacy_assignment_unique, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='productionlinedepartmentassignment',
                    unique_together=set(),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(remove_legacy_resource_department_column, migrations.RunPython.noop),
            ],
            state_operations=[
                migrations.RemoveField(
                    model_name='resource',
                    name='department',
                ),
            ],
        ),
        migrations.RunPython(repair_duplicate_names, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['name'], name='mfg_company_name_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['code'], name='mfg_company_code_idx'),
        ),
        migrations.AddIndex(
            model_name='plant',
            index=models.Index(fields=['company'], name='mfg_plant_company_idx'),
        ),
        migrations.AddIndex(
            model_name='plant',
            index=models.Index(fields=['company', 'code'], name='mfg_plant_company_code_idx'),
        ),
        migrations.AddIndex(
            model_name='plant',
            index=models.Index(fields=['status'], name='mfg_plant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='productionlinedepartmentassignment',
            index=models.Index(fields=['plant', 'production_line'], name='mfg_pld_plant_line_idx'),
        ),
        migrations.AddIndex(
            model_name='productionlinedepartmentassignment',
            index=models.Index(fields=['plant', 'department'], name='mfg_pld_plant_dept_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcegroup',
            index=models.Index(fields=['department'], name='mfg_rg_department_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcegroup',
            index=models.Index(fields=['department', 'code'], name='mfg_rg_department_code_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcegroup',
            index=models.Index(fields=['status'], name='mfg_rg_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('plant', 'name'), name='uq_department_plant_name'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('id', 'plant'), name='uq_department_id_plant'),
        ),
        migrations.AddConstraint(
            model_name='plant',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='uq_plant_company_name'),
        ),
        migrations.AddConstraint(
            model_name='productionline',
            constraint=models.UniqueConstraint(fields=('plant', 'name'), name='uq_line_plant_name'),
        ),
        migrations.AddConstraint(
            model_name='productionline',
            constraint=models.UniqueConstraint(fields=('id', 'plant'), name='uq_line_id_plant'),
        ),
        migrations.AddConstraint(
            model_name='productionlinedepartmentassignment',
            constraint=models.UniqueConstraint(fields=('production_line', 'department'), name='uq_line_department_assignment'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.UniqueConstraint(fields=('resource_group', 'name'), name='uq_resource_group_name'),
        ),
        migrations.AddConstraint(
            model_name='resourcegroup',
            constraint=models.UniqueConstraint(fields=('department', 'name'), name='uq_resource_group_department_name'),
        ),
        migrations.RunSQL(
            sql=[
                """
                ALTER TABLE manufacturing_production_line_department
                ADD CONSTRAINT fk_pld_line_same_plant
                FOREIGN KEY (production_line_id, plant_id)
                REFERENCES manufacturing_production_line (id, plant_id)
                """,
                """
                ALTER TABLE manufacturing_production_line_department
                ADD CONSTRAINT fk_pld_dept_same_plant
                FOREIGN KEY (department_id, plant_id)
                REFERENCES manufacturing_department (id, plant_id)
                """,
            ],
            reverse_sql=[
                "ALTER TABLE manufacturing_production_line_department DROP FOREIGN KEY fk_pld_dept_same_plant",
                "ALTER TABLE manufacturing_production_line_department DROP FOREIGN KEY fk_pld_line_same_plant",
            ],
        ),
    ]
