# Generated by Django 6.0.4 on 2026-05-15 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0037_alter_productionlinedepartmentassignment_unique_together_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bom',
            index=models.Index(fields=['product_model', 'status'], name='mfg_bom_model_status_idx'),
        ),
        migrations.AddIndex(
            model_name='routing',
            index=models.Index(fields=['production_line', 'product_model', 'status'], name='mfg_route_line_model_stat_idx'),
        ),
    ]
