# Generated by Django 6.0.4 on 2026-05-15 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0038_bom_mfg_bom_model_status_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialBin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('bin_type', models.CharField(choices=[('RM', 'Raw Material'), ('INPUT', 'Input'), ('OUTPUT', 'Output'), ('WIP', 'WIP'), ('SUPERMARKET', 'Supermarket'), ('FIFO', 'FIFO'), ('FG', 'Finished Goods'), ('SCRAP', 'Scrap'), ('QUARANTINE', 'Quarantine')], max_length=30)),
                ('capacity', models.FloatField(default=0)),
                ('location_code', models.CharField(blank=True, default='', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_bins', to='manufacturing.material')),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_bins', to='manufacturing.plant')),
                ('resource_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_bins', to='manufacturing.resourcegroup')),
                ('uom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='manufacturing.referencevalue')),
            ],
            options={
                'db_table': 'manufacturing_material_bin',
                'ordering': ['plant', 'code'],
            },
        ),
        migrations.AddField(
            model_name='materialmovementrule',
            name='destination_bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movement_rules_as_destination', to='manufacturing.materialbin'),
        ),
        migrations.AddField(
            model_name='materialmovementrule',
            name='source_bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movement_rules_as_source', to='manufacturing.materialbin'),
        ),
        migrations.AddField(
            model_name='operationinput',
            name='source_bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_inputs', to='manufacturing.materialbin'),
        ),
        migrations.AddField(
            model_name='operationoutput',
            name='destination_bin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operation_outputs', to='manufacturing.materialbin'),
        ),
        migrations.AddIndex(
            model_name='materialbin',
            index=models.Index(fields=['plant', 'bin_type', 'resource_group', 'material'], name='mfg_bin_scope_idx'),
        ),
        migrations.AddIndex(
            model_name='materialbin',
            index=models.Index(fields=['plant', 'is_active'], name='mfg_bin_plant_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='materialbin',
            constraint=models.UniqueConstraint(fields=('plant', 'code'), name='uq_material_bin_plant_code'),
        ),
        migrations.AddConstraint(
            model_name='materialbin',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gte', 0)), name='ck_material_bin_capacity_gte_0'),
        ),
    ]
