# Generated by Django 6.0.4 on 2026-05-15 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0039_materialbin_materialmovementrule_destination_bin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapacityProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('PLANT', 'Plant'), ('PRODUCTION_LINE', 'Production Line'), ('DEPARTMENT', 'Department'), ('RESOURCE_GROUP', 'Resource Group'), ('RESOURCE', 'Resource')], max_length=30)),
                ('scope_id', models.CharField(max_length=50)),
                ('capacity_mode', models.CharField(choices=[('RESOURCE_SUM', 'Sum of Resources'), ('BOTTLENECK', 'Bottleneck'), ('MANUAL', 'Manual'), ('INHERITED', 'Inherited')], default='INHERITED', max_length=20)),
                ('manual_capacity', models.FloatField(blank=True, null=True)),
                ('capacity_uom', models.CharField(blank=True, default='', max_length=50)),
                ('efficiency_factor', models.FloatField(default=1.0)),
                ('oee_factor', models.FloatField(blank=True, null=True)),
                ('takt_factor', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Capacity Profile',
                'verbose_name_plural': 'Capacity Profiles',
                'db_table': 'manufacturing_capacity_profile',
                'ordering': ['scope_type', 'scope_id'],
                'indexes': [models.Index(fields=['scope_type', 'scope_id'], name='cap_profile_scope_idx')],
                'constraints': [models.UniqueConstraint(fields=('scope_type', 'scope_id', 'is_active'), name='uq_cap_profile_scope_active')],
            },
        ),
        migrations.CreateModel(
            name='CapacityRecalculationJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.CharField(choices=[('SCHEDULE_CHANGED', 'Schedule Changed'), ('PROFILE_CHANGED', 'Profile Changed'), ('STRUCTURE_CHANGED', 'Structure Changed')], max_length=30)),
                ('scope_type', models.CharField(choices=[('PLANT', 'Plant'), ('PRODUCTION_LINE', 'Production Line'), ('DEPARTMENT', 'Department'), ('RESOURCE_GROUP', 'Resource Group'), ('RESOURCE', 'Resource')], max_length=30)),
                ('scope_id', models.CharField(max_length=50)),
                ('from_datetime', models.DateTimeField()),
                ('to_datetime', models.DateTimeField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Capacity Recalculation Job',
                'verbose_name_plural': 'Capacity Recalculation Jobs',
                'db_table': 'manufacturing_capacity_recalc_job',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='recalc_job_status_idx'), models.Index(fields=['scope_type', 'scope_id'], name='recalc_job_scope_idx'), models.Index(fields=['created_at'], name='recalc_job_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('PLANT', 'Plant'), ('PRODUCTION_LINE', 'Production Line'), ('DEPARTMENT', 'Department'), ('RESOURCE_GROUP', 'Resource Group'), ('RESOURCE', 'Resource')], max_length=30)),
                ('scope_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('timezone', models.CharField(blank=True, default='', max_length=100)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Work Schedule',
                'verbose_name_plural': 'Work Schedules',
                'db_table': 'manufacturing_work_schedule',
                'ordering': ['scope_type', 'scope_id', 'effective_from'],
                'indexes': [models.Index(fields=['scope_type', 'scope_id', 'is_active'], name='ws_scope_active_idx'), models.Index(fields=['effective_from', 'effective_to'], name='ws_effective_idx')],
            },
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('weekday', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('crosses_midnight', models.BooleanField(default=False)),
                ('paid_minutes', models.IntegerField(default=0)),
                ('break_minutes', models.IntegerField(default=0)),
                ('net_minutes', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='manufacturing.workschedule')),
            ],
            options={
                'verbose_name': 'Work Shift',
                'verbose_name_plural': 'Work Shifts',
                'db_table': 'manufacturing_work_shift',
                'ordering': ['schedule', 'weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='CapacitySnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_type', models.CharField(choices=[('PLANT', 'Plant'), ('PRODUCTION_LINE', 'Production Line'), ('DEPARTMENT', 'Department'), ('RESOURCE_GROUP', 'Resource Group'), ('RESOURCE', 'Resource')], max_length=30)),
                ('scope_id', models.CharField(max_length=50)),
                ('from_datetime', models.DateTimeField()),
                ('to_datetime', models.DateTimeField()),
                ('available_minutes', models.FloatField(default=0)),
                ('theoretical_capacity', models.FloatField(default=0)),
                ('effective_capacity', models.FloatField(default=0)),
                ('bottleneck_capacity', models.FloatField(blank=True, null=True)),
                ('capacity_uom', models.CharField(blank=True, default='', max_length=50)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('source_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='manufacturing.capacityprofile')),
                ('source_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='snapshots', to='manufacturing.workschedule')),
            ],
            options={
                'verbose_name': 'Capacity Snapshot',
                'verbose_name_plural': 'Capacity Snapshots',
                'db_table': 'manufacturing_capacity_snapshot',
                'ordering': ['scope_type', 'scope_id', 'from_datetime'],
                'indexes': [models.Index(fields=['scope_type', 'scope_id', 'from_datetime', 'to_datetime'], name='cap_snap_scope_window_idx')],
            },
        ),
    ]
