# Generated by Django 6.0.4 on 2026-05-15 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0040_capacityprofile_capacityrecalculationjob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitysnapshot',
            name='snapshot_type',
            field=models.CharField(choices=[('PLANNING', 'Planning'), ('EXECUTION', 'Execution')], db_index=True, default='PLANNING', max_length=20),
        ),
        migrations.AddField(
            model_name='capacitysnapshot',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('FROZEN', 'Frozen')], db_index=True, default='ACTIVE', max_length=20),
        ),
        migrations.AddField(
            model_name='capacitysnapshot',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='scheduleassignment',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='scheduleassignment',
            name='plant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='schedule_assignments', to='manufacturing.plant'),
        ),
        migrations.AddField(
            model_name='scheduleassignment',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scheduleassignment',
            name='work_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='manufacturing.workschedule'),
        ),
        migrations.AlterField(
            model_name='scheduleassignment',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='manufacturing.schedule'),
        ),
        migrations.AddIndex(
            model_name='capacitysnapshot',
            index=models.Index(fields=['scope_type', 'scope_id', 'snapshot_type', 'status'], name='cap_snap_scope_state_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleassignment',
            index=models.Index(fields=['plant', 'entity_type', 'entity_id', 'is_active'], name='sched_assign_scope_idx'),
        ),
        migrations.AddConstraint(
            model_name='capacitysnapshot',
            constraint=models.UniqueConstraint(fields=('scope_type', 'scope_id', 'from_datetime', 'to_datetime', 'snapshot_type', 'version'), name='uq_cap_snap_scope_window_ver'),
        ),
    ]
