# Generated by Django 6.0.4 on 2026-05-15 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0041_capacitysnapshot_snapshot_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitysnapshot',
            name='constraint_reason',
            field=models.CharField(choices=[('MACHINE', 'Machine'), ('LABOR', 'Labor'), ('BALANCED', 'Balanced'), ('NO_SCHEDULE', 'No Schedule'), ('NO_LABOR', 'No Labor'), ('NO_MACHINE', 'No Machine')], db_index=True, default='NO_MACHINE', max_length=20),
        ),
        migrations.AddField(
            model_name='capacitysnapshot',
            name='effective_capacity_units',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='capacitysnapshot',
            name='labor_available_minutes',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='capacitysnapshot',
            name='labor_capacity_units',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='capacitysnapshot',
            name='machine_available_minutes',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='capacitysnapshot',
            name='machine_capacity_units',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='capacitysnapshot',
            name='operators_available',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='capacitysnapshot',
            name='operators_required',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='LaborRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operators_required', models.PositiveIntegerField()),
                ('labor_minutes_per_unit', models.FloatField()),
                ('is_active', models.BooleanField(default=True)),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='labor_requirements', to='manufacturing.plant')),
                ('product_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labor_requirements', to='manufacturing.productmodel')),
                ('resource_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='labor_requirements', to='manufacturing.resourcegroup')),
                ('routing_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='labor_requirements', to='manufacturing.routingstep')),
                ('skill_required', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='labor_requirements', to='manufacturing.referencevalue')),
            ],
            options={
                'db_table': 'manufacturing_labor_requirement',
                'ordering': ['plant', 'resource_group', 'routing_step', 'effective_from'],
                'indexes': [models.Index(fields=['plant', 'resource_group', 'is_active'], name='labor_req_rg_active_idx'), models.Index(fields=['plant', 'routing_step', 'is_active'], name='labor_req_step_active_idx'), models.Index(fields=['effective_from', 'effective_to'], name='labor_req_effective_idx')],
            },
        ),
        migrations.CreateModel(
            name='OperatorAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effective_from', models.DateTimeField()),
                ('effective_to', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operator_assignments', to=settings.AUTH_USER_MODEL)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operator_assignments', to='manufacturing.plant')),
                ('resource', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operator_assignments', to='manufacturing.resource')),
                ('resource_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operator_assignments', to='manufacturing.resourcegroup')),
                ('schedule_assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='operator_assignments', to='manufacturing.scheduleassignment')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_assignments', to='manufacturing.referencevalue')),
            ],
            options={
                'db_table': 'manufacturing_operator_assignment',
                'ordering': ['plant', 'operator', 'effective_from'],
                'indexes': [models.Index(fields=['plant', 'resource_group', 'is_active'], name='op_assign_rg_active_idx'), models.Index(fields=['plant', 'resource', 'is_active'], name='op_assign_res_active_idx'), models.Index(fields=['operator', 'is_active', 'effective_from'], name='op_assign_person_active_idx')],
            },
        ),
    ]
