# Generated by Django 6.0.4 on 2026-05-15 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0042_capacitysnapshot_constraint_reason_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFamily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Family',
                'verbose_name_plural': 'Product Families',
                'db_table': 'manufacturing_product_family',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('configuration_summary', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'manufacturing_product_variant',
                'ordering': ['model', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PartNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('revision', models.CharField(blank=True, default='', max_length=50)),
                ('uom', models.CharField(blank=True, default='EA', max_length=50)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_numbers', to='manufacturing.productmodel')),
            ],
            options={
                'db_table': 'manufacturing_part_number',
                'ordering': ['part_number'],
            },
        ),
        migrations.AddField(
            model_name='bom',
            name='part_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boms', to='manufacturing.partnumber'),
        ),
        migrations.AddField(
            model_name='processflow',
            name='part_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_flows', to='manufacturing.partnumber'),
        ),
        migrations.AddField(
            model_name='routing',
            name='part_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routings', to='manufacturing.partnumber'),
        ),
        migrations.AddIndex(
            model_name='bom',
            index=models.Index(fields=['part_number', 'status'], name='mfg_bom_part_status_idx'),
        ),
        migrations.AddIndex(
            model_name='routing',
            index=models.Index(fields=['production_line', 'part_number', 'status'], name='mfg_route_line_part_stat_idx'),
        ),
        migrations.AddField(
            model_name='partnumber',
            name='family',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='part_numbers', to='manufacturing.productfamily'),
        ),
        migrations.AddField(
            model_name='productmodel',
            name='family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='models', to='manufacturing.productfamily'),
        ),
        migrations.AddConstraint(
            model_name='productmodel',
            constraint=models.UniqueConstraint(fields=('family', 'code'), name='uq_product_model_family_code'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='manufacturing.productmodel'),
        ),
        migrations.AddField(
            model_name='partnumber',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='part_numbers', to='manufacturing.productvariant'),
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('model', 'code'), name='uq_product_variant_model_code'),
        ),
        migrations.AddIndex(
            model_name='partnumber',
            index=models.Index(fields=['family', 'model', 'variant'], name='part_hierarchy_idx'),
        ),
        migrations.AddIndex(
            model_name='partnumber',
            index=models.Index(fields=['is_active', 'status'], name='part_active_status_idx'),
        ),
    ]
