# Generated by Django 6.0.4 on 2026-05-15 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0043_productfamily_productvariant_partnumber_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workschedule',
            name='timezone',
            field=models.CharField(default='UTC', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='workshift',
            constraint=models.CheckConstraint(condition=models.Q(('paid_minutes__gt', 0)), name='ws_paid_minutes_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='workshift',
            constraint=models.CheckConstraint(condition=models.Q(('break_minutes__gte', 0)), name='ws_break_minutes_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='workshift',
            constraint=models.CheckConstraint(condition=models.Q(('net_minutes__gt', 0)), name='ws_net_minutes_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='workshift',
            constraint=models.CheckConstraint(condition=models.Q(('net_minutes__lte', models.F('paid_minutes'))), name='ws_net_minutes_lte_paid'),
        ),
        migrations.AddConstraint(
            model_name='workshift',
            constraint=models.CheckConstraint(condition=models.Q(('weekday__gte', 0), ('weekday__lte', 6)), name='ws_weekday_range'),
        ),
        migrations.AddConstraint(
            model_name='workshift',
            constraint=models.UniqueConstraint(fields=('schedule', 'weekday', 'start_time', 'end_time', 'name'), name='uq_ws_shift_slot'),
        ),
    ]
