# Generated by Django 6.0.4 on 2026-05-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0044_alter_workschedule_timezone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workschedule',
            name='timezone',
            field=models.CharField(blank=True, default='UTC', max_length=100),
        ),
    ]
