# Generated by Django 6.0.4 on 2026-05-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0045_alter_workschedule_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='capacitysnapshot',
            name='missing_reasons',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
