# Generated by Django 6.0.4 on 2026-05-18 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0048_move_backfilled_parts_to_variants'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSourceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('domain', models.CharField(choices=[('PLANT_STRUCTURE', 'Plant Structure'), ('MATERIALS', 'Materials'), ('BOM', 'Bill of Materials'), ('ROUTING', 'Routing'), ('SCHEDULES', 'Schedules'), ('INVENTORY', 'Inventory')], max_length=50)),
                ('source_type', models.CharField(choices=[('EXCEL', 'Excel'), ('CSV', 'CSV'), ('ERP_EXPORT', 'ERP Export'), ('API', 'API')], max_length=20)),
                ('path', models.CharField(max_length=500)),
                ('file_pattern', models.CharField(blank=True, default='', max_length=200)),
                ('archive_path', models.CharField(blank=True, max_length=500, null=True)),
                ('error_path', models.CharField(blank=True, max_length=500, null=True)),
                ('polling_interval_minutes', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Import Source Config',
                'verbose_name_plural': 'Import Source Configs',
                'db_table': 'integration_import_source_config',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['domain'], name='intg_src_domain_idx'), models.Index(fields=['is_active'], name='intg_src_active_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(choices=[('PLANT_STRUCTURE', 'Plant Structure'), ('MATERIALS', 'Materials'), ('BOM', 'Bill of Materials'), ('ROUTING', 'Routing'), ('SCHEDULES', 'Schedules'), ('INVENTORY', 'Inventory')], max_length=50)),
                ('file_name', models.CharField(max_length=500)),
                ('file_path', models.CharField(max_length=500)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIAL_SUCCESS', 'Partial Success')], default='PENDING', max_length=20)),
                ('records_processed', models.IntegerField(default=0)),
                ('records_created', models.IntegerField(default=0)),
                ('records_updated', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('error_summary', models.TextField(blank=True, null=True)),
                ('triggered_by', models.CharField(blank=True, max_length=200, null=True)),
                ('source_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='manufacturing.importsourceconfig')),
            ],
            options={
                'verbose_name': 'Import Job',
                'verbose_name_plural': 'Import Jobs',
                'db_table': 'integration_import_job',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportValidationError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sheet_name', models.CharField(blank=True, max_length=200, null=True)),
                ('row_number', models.IntegerField(blank=True, null=True)),
                ('entity_type', models.CharField(max_length=100)),
                ('field_name', models.CharField(blank=True, max_length=100, null=True)),
                ('error_code', models.CharField(max_length=50)),
                ('message', models.TextField()),
                ('raw_value', models.TextField(blank=True, null=True)),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_errors', to='manufacturing.importjob')),
            ],
            options={
                'verbose_name': 'Import Validation Error',
                'verbose_name_plural': 'Import Validation Errors',
                'db_table': 'integration_import_validation_error',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MappingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(choices=[('PLANT_STRUCTURE', 'Plant Structure'), ('MATERIALS', 'Materials'), ('BOM', 'Bill of Materials'), ('ROUTING', 'Routing'), ('SCHEDULES', 'Schedules'), ('INVENTORY', 'Inventory')], max_length=50)),
                ('source_field', models.CharField(max_length=200)),
                ('destination_field', models.CharField(max_length=200)),
                ('transform_rule', models.TextField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Mapping Rule',
                'verbose_name_plural': 'Mapping Rules',
                'db_table': 'integration_mapping_rule',
                'ordering': ['domain', 'source_field'],
                'indexes': [models.Index(fields=['domain'], name='intg_map_domain_idx'), models.Index(fields=['is_active'], name='intg_map_active_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['status'], name='intg_job_status_idx'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['domain'], name='intg_job_domain_idx'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['source_config'], name='intg_job_source_idx'),
        ),
        migrations.AddIndex(
            model_name='importvalidationerror',
            index=models.Index(fields=['import_job'], name='intg_err_job_idx'),
        ),
        migrations.AddIndex(
            model_name='importvalidationerror',
            index=models.Index(fields=['entity_type'], name='intg_err_entity_idx'),
        ),
        migrations.AddIndex(
            model_name='importvalidationerror',
            index=models.Index(fields=['error_code'], name='intg_err_code_idx'),
        ),
    ]
