# Generated by Django 6.0.4 on 2026-05-18 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_importsourceconfig'),
        ('manufacturing', '0049_importsourceconfig_importjob_importvalidationerror_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='importsourceconfig',
            name='intg_src_domain_idx',
        ),
        migrations.RemoveIndex(
            model_name='importsourceconfig',
            name='intg_src_active_idx',
        ),
        migrations.AlterField(
            model_name='importjob',
            name='source_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to='application.importsourceconfig'),
        ),
        migrations.RemoveIndex(
            model_name='importjob',
            name='intg_job_domain_idx',
        ),
        migrations.AlterField(
            model_name='mappingrule',
            name='domain',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='ImportSourceConfig',
        ),
        migrations.RemoveField(
            model_name='importjob',
            name='domain',
        ),
    ]
