# Generated by Django 6.0.4 on 2026-05-18 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0050_remove_importsourceconfig_intg_src_domain_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PREVIEWED', 'Previewed'), ('VALIDATED', 'Validated'), ('COMPARED', 'Compared'), ('READY_TO_APPLY', 'Ready to Apply'), ('APPLIED', 'Applied'), ('PREVIEW_FAILED', 'Preview Failed'), ('VALIDATION_FAILED', 'Validation Failed'), ('COMPARE_FAILED', 'Compare Failed'), ('APPLY_FAILED', 'Apply Failed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed'), ('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('PARTIAL_SUCCESS', 'Partial Success')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='ImportAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=50)),
                ('user', models.CharField(blank=True, default='', max_length=200)),
                ('message', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(default=dict)),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='manufacturing.importjob')),
            ],
            options={
                'db_table': 'integration_import_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['import_job'], name='intg_audit_job_idx'), models.Index(fields=['action'], name='intg_audit_action_idx')],
            },
        ),
        migrations.CreateModel(
            name='ImportCompareResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('UNCHANGED', 'Unchanged'), ('CONFLICT', 'Conflict'), ('DEACTIVATE', 'Deactivate')], max_length=20)),
                ('entity_type', models.CharField(max_length=100)),
                ('stable_key', models.CharField(db_index=True, max_length=200)),
                ('current_value', models.JSONField(default=dict)),
                ('incoming_value', models.JSONField(default=dict)),
                ('diff', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('import_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compare_results', to='manufacturing.importjob')),
            ],
            options={
                'db_table': 'integration_import_compare_result',
                'ordering': ['stable_key'],
                'indexes': [models.Index(fields=['import_job'], name='intg_cmp_job_idx'), models.Index(fields=['action'], name='intg_cmp_action_idx')],
            },
        ),
    ]
