# Generated by Django 6.0.4 on 2026-05-19 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0051_alter_importjob_status_importauditlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialbin',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='materialbin',
            name='fifo_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materialbin',
            name='location_reference',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='materialbin',
            name='material_group',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='materialbin',
            name='production_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_bins', to='manufacturing.productionline'),
        ),
        migrations.AddField(
            model_name='materialbin',
            name='replenishment_mode',
            field=models.CharField(blank=True, choices=[('MANUAL', 'Manual'), ('KANBAN', 'Kanban'), ('CONWIP', 'Conwip'), ('PULL', 'Pull'), ('PUSH', 'Push'), ('REORDER_POINT', 'Reorder Point'), ('MIN_MAX', 'Min/Max')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='materialbin',
            name='supermarket_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='materialbin',
            name='warehouse_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='materialbin',
            name='bin_type',
            field=models.CharField(choices=[('RM', 'Raw Material'), ('INPUT', 'Input'), ('OUTPUT', 'Output'), ('WIP', 'WIP'), ('FIFO', 'FIFO'), ('SUPERMARKET', 'Supermarket'), ('FG', 'Finished Goods'), ('SCRAP', 'Scrap'), ('QUARANTINE', 'Quarantine'), ('SPARES', 'Spares'), ('LINE_SIDE', 'Line Side')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='materialbin',
            index=models.Index(fields=['plant', 'production_line'], name='mfg_bin_prod_line_idx'),
        ),
    ]
