# Generated by Django 5.1.7

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0052_materialbin_description_materialbin_fifo_enabled_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('warehouse_type', models.CharField(choices=[('RM', 'Raw Material'), ('WIP', 'WIP'), ('FG', 'Finished Goods'), ('SCRAP', 'Scrap'), ('QUARANTINE', 'Quarantine'), ('SPARES', 'Spares'), ('GENERAL', 'General')], default='GENERAL', max_length=30)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouses', to='manufacturing.plant')),
            ],
            options={
                'db_table': 'manufacturing_warehouse',
                'ordering': ['plant', 'code'],
            },
        ),
        migrations.AddField(
            model_name='materialbin',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='material_bins', to='manufacturing.warehouse'),
        ),
        migrations.AddConstraint(
            model_name='warehouse',
            constraint=models.UniqueConstraint(fields=('plant', 'code'), name='uq_warehouse_plant_code'),
        ),
    ]
