# Generated by Django 6.0.4
# Makes warehouse_code nullable since it's been replaced by the warehouse FK.
# The warehouse_code field is now a property on the model.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0053_warehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialbin',
            name='warehouse_code',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
