# Generated by Django 6.0.4 on 2026-05-19 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0054_alter_materialbin_warehouse_code_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialbin',
            name='warehouse_code',
        ),
        migrations.AddField(
            model_name='importjob',
            name='file_hash',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='importjob',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='file_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('FILE_ATTACHED', 'File Attached'), ('PREVIEWED', 'Previewed'), ('VALIDATED', 'Validated'), ('COMPARED', 'Compared'), ('READY_TO_APPLY', 'Ready to Apply'), ('APPLIED', 'Applied'), ('PREVIEW_FAILED', 'Preview Failed'), ('VALIDATION_FAILED', 'Validation Failed'), ('COMPARE_FAILED', 'Compare Failed'), ('APPLY_FAILED', 'Apply Failed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed'), ('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('PARTIAL_SUCCESS', 'Partial Success')], default='PENDING', max_length=20),
        ),
    ]
