# Generated by Django 6.0.4 on 2026-05-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_passwordresettoken'),
        ('manufacturing', '0055_remove_materialbin_warehouse_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='file_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('FILE_ATTACHED', 'File Attached'), ('PREVIEWED', 'Previewed'), ('VALIDATED', 'Validated'), ('COMPARED', 'Compared'), ('READY_TO_APPLY', 'Ready to Apply'), ('APPLIED', 'Applied'), ('ARCHIVED', 'Archived'), ('PREVIEW_FAILED', 'Preview Failed'), ('VALIDATION_FAILED', 'Validation Failed'), ('COMPARE_FAILED', 'Compare Failed'), ('APPLY_FAILED', 'Apply Failed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed'), ('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('PARTIAL_SUCCESS', 'Partial Success')], default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['source_config', 'file_hash', 'status'], name='intg_job_src_hash_status_idx'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['source_config', 'file_name', 'status'], name='intg_job_src_name_status_idx'),
        ),
    ]
