# Generated by Django 6.0.4 on 2026-05-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0056_alter_importjob_file_hash_alter_importjob_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('FILE_ATTACHED', 'File Attached'), ('FILE_MISSING', 'File Missing'), ('PREVIEWED', 'Previewed'), ('VALIDATED', 'Validated'), ('COMPARED', 'Compared'), ('READY_TO_APPLY', 'Ready to Apply'), ('APPLIED', 'Applied'), ('ARCHIVED', 'Archived'), ('PREVIEW_FAILED', 'Preview Failed'), ('VALIDATION_FAILED', 'Validation Failed'), ('COMPARE_FAILED', 'Compare Failed'), ('APPLY_FAILED', 'Apply Failed'), ('CANCELLED', 'Cancelled'), ('FAILED', 'Failed'), ('PENDING', 'Pending'), ('RUNNING', 'Running'), ('COMPLETED', 'Completed'), ('PARTIAL_SUCCESS', 'Partial Success')], default='PENDING', max_length=20),
        ),
    ]
