# Generated by Django 6.0.4 on 2026-05-20 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0057_alter_importjob_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('domain', models.CharField(default='PLANT_STRUCTURE', max_length=50)),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=False)),
                ('created_by', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Import Profile',
                'verbose_name_plural': 'Import Profiles',
                'db_table': 'erp_import_profile',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ImportFieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity_type', models.CharField(max_length=100)),
                ('source_column', models.CharField(max_length=200)),
                ('target_field', models.CharField(max_length=200)),
                ('transform_rule', models.TextField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_mappings', to='manufacturing.importprofile')),
            ],
            options={
                'verbose_name': 'Import Field Mapping',
                'verbose_name_plural': 'Import Field Mappings',
                'db_table': 'erp_import_field_mapping',
                'ordering': ['entity_type', 'sort_order', 'source_column'],
                'unique_together': {('profile', 'entity_type', 'source_column')},
            },
        ),
    ]
