# Generated by Django 6.0.4 on 2026-05-22 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0058_importprofile_importfieldmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='importjob',
            name='error_artifact_path',
            field=models.CharField(blank=True, default='', help_text='Error artifact path under erp_data/error/', max_length=512),
        ),
        migrations.AddField(
            model_name='importjob',
            name='imported_file_path',
            field=models.CharField(blank=True, default='', help_text='Imported file path under erp_data/imported/', max_length=512),
        ),
        migrations.AddField(
            model_name='importjob',
            name='result_artifact_path',
            field=models.CharField(blank=True, default='', help_text='Result snapshot path under erp_data/structure/ or erp_data/imported/', max_length=512),
        ),
        migrations.AddField(
            model_name='importprofile',
            name='profile_file_path',
            field=models.CharField(blank=True, default='', help_text='Profile file path under erp_data/structure/', max_length=512),
        ),
        migrations.AddField(
            model_name='importprofile',
            name='source_template_path',
            field=models.CharField(blank=True, default='', help_text='Template file path under erp_data/patterns/', max_length=512),
        ),
        migrations.AlterField(
            model_name='importjob',
            name='file_path',
            field=models.CharField(blank=True, default='', help_text='Path under erp_data/source/', max_length=500),
        ),
        migrations.CreateModel(
            name='ErpSourceDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('scope', models.CharField(choices=[('PLANT_STRUCTURE', 'Plant Structure'), ('PRODUCT_MASTER', 'Product Master Data'), ('MATERIALS', 'Materials'), ('WAREHOUSE_BINS', 'Warehouse / Bins'), ('ROUTING', 'Routing'), ('SCHEDULES', 'Schedules'), ('CAPACITY', 'Capacity'), ('QUALITY', 'Quality'), ('CUSTOM', 'Custom')], max_length=40)),
                ('source_type', models.CharField(choices=[('MANUAL', 'Manual'), ('EXCEL', 'Excel'), ('CSV', 'CSV'), ('ERP_EXPORT', 'ERP Export'), ('API', 'API')], default='MANUAL', max_length=20)),
                ('destination_table', models.CharField(blank=True, default='', max_length=120)),
                ('expected_file_pattern', models.CharField(blank=True, default='', max_length=200)),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('DEPRECATED', 'Deprecated')], default='DRAFT', max_length=20)),
                ('schema_json', models.JSONField(blank=True, default=dict)),
                ('row_count', models.IntegerField(default=0)),
                ('last_imported_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'erp_source_definition',
                'ordering': ['scope', 'name'],
                'indexes': [models.Index(fields=['scope', 'active'], name='erp_src_scope_active_idx'), models.Index(fields=['status'], name='erp_src_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='ErpImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=500)),
                ('file_hash', models.CharField(blank=True, default='', max_length=64)),
                ('imported_by', models.CharField(blank=True, default='', max_length=200)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('mode', models.CharField(choices=[('FULL', 'Full'), ('APPEND', 'Append'), ('OVERWRITE', 'Overwrite')], default='FULL', max_length=20)),
                ('status', models.CharField(choices=[('IMPORTING', 'Importing'), ('STAGED', 'Staged'), ('VALIDATED', 'Validated'), ('FAILED', 'Failed'), ('APPLIED', 'Applied')], default='IMPORTING', max_length=20)),
                ('row_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('source_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='manufacturing.erpsourcedefinition')),
            ],
            options={
                'db_table': 'erp_import_batch',
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='ErpDefinitionField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_name', models.CharField(max_length=120)),
                ('data_type', models.CharField(blank=True, default='string', max_length=40)),
                ('required', models.BooleanField(default=False)),
                ('primary_key', models.BooleanField(default=False)),
                ('foreign_key', models.BooleanField(default=False)),
                ('nexus_field', models.CharField(blank=True, default='', max_length=120)),
                ('aliases_json', models.JSONField(blank=True, default=list)),
                ('active', models.BooleanField(default=True)),
                ('source_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='manufacturing.erpsourcedefinition')),
            ],
            options={
                'db_table': 'erp_definition_field',
                'ordering': ['source_definition', 'field_name'],
            },
        ),
        migrations.CreateModel(
            name='ErpStagingRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('row_number', models.IntegerField()),
                ('raw_data_json', models.JSONField(default=dict)),
                ('normalized_data_json', models.JSONField(blank=True, default=dict)),
                ('validation_status', models.CharField(blank=True, default='', max_length=20)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staging_rows', to='manufacturing.erpimportbatch')),
                ('source_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staging_rows', to='manufacturing.erpsourcedefinition')),
            ],
            options={
                'db_table': 'erp_staging_row',
                'ordering': ['batch', 'row_number'],
            },
        ),
        migrations.CreateModel(
            name='ErpValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scope', models.CharField(choices=[('PLANT_STRUCTURE', 'Plant Structure'), ('PRODUCT_MASTER', 'Product Master Data'), ('MATERIALS', 'Materials'), ('WAREHOUSE_BINS', 'Warehouse / Bins'), ('ROUTING', 'Routing'), ('SCHEDULES', 'Schedules'), ('CAPACITY', 'Capacity'), ('QUALITY', 'Quality'), ('CUSTOM', 'Custom')], max_length=40)),
                ('destination_table', models.CharField(blank=True, default='', max_length=120)),
                ('severity', models.CharField(choices=[('ERROR', 'Error'), ('WARNING', 'Warning'), ('INFO', 'Info')], max_length=16)),
                ('entity', models.CharField(blank=True, default='', max_length=120)),
                ('field_name', models.CharField(blank=True, default='', max_length=120)),
                ('row_number', models.IntegerField(blank=True, null=True)),
                ('rule_code', models.CharField(max_length=60)),
                ('message', models.TextField()),
                ('recommended_action', models.TextField(blank=True, default='')),
                ('source_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='validation_results', to='manufacturing.erpsourcedefinition')),
            ],
            options={
                'db_table': 'erp_validation_result',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ErpImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(max_length=60)),
                ('message', models.TextField(blank=True, default='')),
                ('user', models.CharField(blank=True, default='', max_length=200)),
                ('metadata_json', models.JSONField(blank=True, default=dict)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='manufacturing.erpimportbatch')),
            ],
            options={
                'db_table': 'erp_import_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['batch'], name='erp_log_batch_idx')],
            },
        ),
        migrations.CreateModel(
            name='ErpRelationshipDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_field', models.CharField(max_length=120)),
                ('target_field', models.CharField(max_length=120)),
                ('relationship_type', models.CharField(choices=[('ONE_TO_ONE', '1:1'), ('BELONGS_TO', 'Belongs To'), ('HAS_MANY', 'Has Many'), ('HAS_ONE', 'Has One'), ('MANY_TO_MANY', 'Many to Many'), ('REFERENCE', 'Reference')], max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('source_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='manufacturing.erpsourcedefinition')),
                ('target_source_definition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='manufacturing.erpsourcedefinition')),
            ],
            options={
                'db_table': 'erp_relationship_definition',
                'ordering': ['source_definition', 'source_field'],
                'indexes': [models.Index(fields=['source_definition'], name='erp_rel_src_idx'), models.Index(fields=['target_source_definition'], name='erp_rel_target_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='erpimportbatch',
            index=models.Index(fields=['source_definition'], name='erp_batch_src_idx'),
        ),
        migrations.AddIndex(
            model_name='erpimportbatch',
            index=models.Index(fields=['status'], name='erp_batch_status_idx'),
        ),
        migrations.AddIndex(
            model_name='erpdefinitionfield',
            index=models.Index(fields=['source_definition'], name='erp_def_field_src_idx'),
        ),
        migrations.AddIndex(
            model_name='erpdefinitionfield',
            index=models.Index(fields=['primary_key'], name='erp_def_field_pk_idx'),
        ),
        migrations.AddConstraint(
            model_name='erpdefinitionfield',
            constraint=models.UniqueConstraint(fields=('source_definition', 'field_name'), name='uq_erp_def_field_name'),
        ),
        migrations.AddIndex(
            model_name='erpstagingrow',
            index=models.Index(fields=['batch'], name='erp_staging_batch_idx'),
        ),
        migrations.AddIndex(
            model_name='erpstagingrow',
            index=models.Index(fields=['source_definition'], name='erp_staging_src_idx'),
        ),
        migrations.AddIndex(
            model_name='erpvalidationresult',
            index=models.Index(fields=['source_definition'], name='erp_val_src_idx'),
        ),
        migrations.AddIndex(
            model_name='erpvalidationresult',
            index=models.Index(fields=['severity'], name='erp_val_severity_idx'),
        ),
        migrations.AddIndex(
            model_name='erpvalidationresult',
            index=models.Index(fields=['scope'], name='erp_val_scope_idx'),
        ),
    ]
