# Generated by Django 6.0.4 on 2026-05-24 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0059_importjob_error_artifact_path_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ErpImportPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('scope', models.CharField(choices=[('PLANT_STRUCTURE', 'Plant Structure'), ('PRODUCT_MASTER', 'Product Master'), ('MATERIALS', 'Materials'), ('WAREHOUSE_BINS', 'Warehouse Bins'), ('ROUTING', 'Routing'), ('SCHEDULES', 'Schedules'), ('CAPACITY', 'Capacity'), ('QUALITY', 'Quality'), ('CUSTOM', 'Custom')], default='CUSTOM', max_length=50)),
                ('destination_entity', models.CharField(help_text='Target LeanSync entity (e.g. Plant, Department, Material)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=200)),
                ('source_file_pattern', models.CharField(blank=True, default='', help_text='Expected file name pattern (glob)', max_length=512)),
            ],
            options={
                'verbose_name': 'ERP Import Pattern',
                'verbose_name_plural': 'ERP Import Patterns',
                'db_table': 'erp_import_pattern',
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ErpImportPatternFieldMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_name', models.CharField(help_text='Source field name from the file', max_length=200)),
                ('source_data_type', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('reference', 'Reference')], default='string', max_length=50)),
                ('destination_name', models.CharField(help_text='Destination Nexus field name', max_length=200)),
                ('destination_data_type', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('reference', 'Reference')], default='string', max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_mappings', to='manufacturing.erpimportpattern')),
            ],
            options={
                'verbose_name': 'ERP Import Pattern Field Mapping',
                'verbose_name_plural': 'ERP Import Pattern Field Mappings',
                'db_table': 'erp_import_pattern_field_mapping',
                'ordering': ['pattern', 'sort_order', 'source_name'],
                'unique_together': {('pattern', 'source_name')},
            },
        ),
    ]
