# Generated by Django 6.0.4 on 2026-05-24 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0060_erpimportpattern_erpimportpatternfieldmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpimportpattern',
            name='plant_selection',
            field=models.JSONField(blank=True, default=dict, help_text='Plant scope: {"mode": "all"} or {"mode": "selected", "plantIds": [1,2,3]}', null=True),
        ),
    ]
