# Generated by Django 6.0.4 on 2026-05-25 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0061_erpimportpattern_plant_selection'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpimportpattern',
            name='department_selection',
            field=models.JSONField(blank=True, default=dict, help_text='Department scope: {"mode": "all"} or {"mode": "selected", "departmentIds": [1,2,3]}', null=True),
        ),
        migrations.AddField(
            model_name='erpimportpattern',
            name='resource_group_selection',
            field=models.JSONField(blank=True, default=dict, help_text='Resource group scope: {"mode": "all"} or {"mode": "selected", "resourceGroupIds": [1,2,3]}', null=True),
        ),
    ]
