# Generated by Django 6.0.4 on 2026-05-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0063_seed_resource_patterns'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpimportpattern',
            name='source_schema',
            field=models.JSONField(blank=True, default=list, help_text='Extracted source fields: [{"fieldName": "Code", "dataType": "string"}, ...]', null=True),
        ),
    ]
