# Generated by Django 6.0.4 on 2026-05-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0064_erpimportpattern_source_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpimportpattern',
            name='source_file_type',
            field=models.CharField(blank=True, default='', help_text='Derived file extension from source_file_pattern (e.g. xlsx, csv)', max_length=20),
        ),
    ]
