# Generated by Django 6.0.4 on 2026-05-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0065_erpimportpattern_source_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpimportpattern',
            name='source_sheet_name',
            field=models.CharField(blank=True, default=None, help_text='Sheet name within a multi-sheet Excel workbook. Null for CSV/JSON/XML.', max_length=255, null=True),
        ),
    ]
