# Generated by Django 6.0.4 on 2026-05-27 18:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0066_erpimportpattern_source_sheet_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionLineResourceGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('production_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_resource_groups', to='manufacturing.productionline')),
                ('resource_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_line_assignments', to='manufacturing.resourcegroup')),
            ],
            options={
                'verbose_name': 'Production Line Resource Group Assignment',
                'verbose_name_plural': 'Production Line Resource Group Assignments',
                'db_table': 'manufacturing_production_line_resource_group',
                'ordering': ['production_line', 'sequence'],
                'indexes': [models.Index(fields=['production_line', 'sequence'], name='manufacturi_product_82c8cb_idx'), models.Index(fields=['production_line', 'is_active'], name='manufacturi_product_e5326c_idx'), models.Index(fields=['resource_group', 'is_active'], name='manufacturi_resourc_998455_idx')],
                'constraints': [models.UniqueConstraint(fields=('production_line', 'resource_group'), name='uq_pl_rg_assignment'), models.UniqueConstraint(fields=('production_line', 'sequence'), name='uq_pl_rg_sequence')],
            },
        ),
    ]
