# Generated by Django 6.0.5 on 2026-05-29 21:57

from django.db import migrations


def drop_tables(apps, schema_editor):
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("DROP TABLE IF EXISTS manufacturing_erp_import_pattern_field_mapping")
        cursor.execute("DROP TABLE IF EXISTS manufacturing_erp_import_pattern")


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0067_productionlineresourcegroup'),
    ]

    operations = [
        migrations.RunPython(drop_tables, migrations.RunPython.noop),
    ]
