# Generated by Django 6.0.5 on 2026-05-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0068_remove_erpimportpatternfieldmapping_pattern_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='part_number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
