# Generated by Django 6.0.4 on 2026-05-31 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0070_cleanup_and_structure_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='structuredocument',
            name='change_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='structuredocument',
            name='is_controlled_copy',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='structuredocument',
            name='review_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='structuredocument',
            name='document_type',
            field=models.CharField(choices=[('WORK_INSTRUCTION', 'Work Instruction'), ('STANDARD_WORK', 'Standard Work'), ('PROCEDURE', 'Procedure'), ('MATERIAL_FLOW_STANDARD', 'Material Flow Standard')], max_length=50),
        ),
        migrations.AlterField(
            model_name='structuredocument',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('APPROVED', 'Approved'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='structuredocument',
            name='target_type',
            field=models.CharField(choices=[('COMPANY', 'Company'), ('PLANT', 'Plant'), ('PRODUCTION_LINE', 'Production Line'), ('DEPARTMENT', 'Department'), ('RESOURCE_GROUP', 'Resource Group'), ('RESOURCE', 'Resource')], max_length=50),
        ),
        migrations.CreateModel(
            name='StructureDocumentAuditTrail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(max_length=50)),
                ('actor', models.CharField(blank=True, default='', max_length=200)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('reason', models.TextField(blank=True, default='')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='manufacturing.structuredocument')),
            ],
            options={
                'verbose_name': 'Document Audit Trail',
                'verbose_name_plural': 'Document Audit Trails',
                'db_table': 'manufacturing_structure_document_audit_trail',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['document'], name='mfg_sdat_doc_idx'), models.Index(fields=['action'], name='mfg_sdat_action_idx')],
            },
        ),
        migrations.CreateModel(
            name='StructureDocumentRevisionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(max_length=50)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.IntegerField()),
                ('code', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('revision', models.CharField(max_length=20)),
                ('status_from', models.CharField(blank=True, max_length=20, null=True)),
                ('status_to', models.CharField(max_length=20)),
                ('content_snapshot', models.TextField(blank=True, default='')),
                ('change_reason', models.TextField(blank=True, default='')),
                ('changed_by', models.CharField(blank=True, default='', max_length=200)),
                ('lifecycle_action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('ARCHIVED', 'Archived'), ('REVISION_CREATED', 'Revision Created'), ('CONTROLLED_COPY_CHANGED', 'Controlled Copy Changed')], max_length=50)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_history', to='manufacturing.structuredocument')),
            ],
            options={
                'verbose_name': 'Document Revision History',
                'verbose_name_plural': 'Document Revision Histories',
                'db_table': 'manufacturing_structure_document_revision_history',
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['document'], name='mfg_sdrh_doc_idx'), models.Index(fields=['lifecycle_action'], name='mfg_sdrh_action_idx')],
            },
        ),
    ]
