# Generated by Django 6.0.4 on 2026-06-01 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0071_document_control_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('audit_type', models.CharField(choices=[('FIVE_S', '5S'), ('SAFETY', 'Safety'), ('QUALITY', 'Quality'), ('PROCESS_CHECK', 'Process Check'), ('STANDARD_WORK_CHECK', 'Standard Work Check')], max_length=50)),
                ('target_type', models.CharField(choices=[('PLANT', 'Plant'), ('PRODUCTION_LINE', 'Production Line'), ('DEPARTMENT', 'Department'), ('RESOURCE_GROUP', 'Resource Group'), ('RESOURCE', 'Resource')], max_length=50)),
                ('target_id', models.IntegerField()),
                ('title', models.CharField(max_length=500)),
                ('auditor', models.CharField(blank=True, default='', max_length=200)),
                ('audit_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('score', models.FloatField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Audit',
                'verbose_name_plural': 'Audits',
                'db_table': 'manufacturing_audit',
                'indexes': [models.Index(fields=['audit_type', 'status'], name='mfg_audit_type_status_idx'), models.Index(fields=['target_type', 'target_id'], name='mfg_audit_target_idx'), models.Index(fields=['audit_date'], name='mfg_audit_date_idx'), models.Index(fields=['auditor'], name='mfg_audit_auditor_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=1000)),
                ('result', models.CharField(blank=True, choices=[('PASS', 'Pass'), ('FAIL', 'Fail'), ('N_A', 'N/A')], max_length=10, null=True)),
                ('comment', models.TextField(blank=True, default='')),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_items', to='manufacturing.audit')),
            ],
            options={
                'verbose_name': 'Audit Checklist Item',
                'verbose_name_plural': 'Audit Checklist Items',
                'db_table': 'manufacturing_audit_checklist_item',
                'indexes': [models.Index(fields=['audit', 'result'], name='mfg_aci_audit_result_idx')],
            },
        ),
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], max_length=10)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('CLOSED', 'Closed')], default='OPEN', max_length=10)),
                ('owner', models.CharField(blank=True, default='', max_length=200)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('audit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='manufacturing.audit')),
            ],
            options={
                'verbose_name': 'Audit Finding',
                'verbose_name_plural': 'Audit Findings',
                'db_table': 'manufacturing_audit_finding',
                'indexes': [models.Index(fields=['audit', 'status'], name='mfg_af_audit_status_idx'), models.Index(fields=['severity'], name='mfg_af_severity_idx')],
            },
        ),
    ]
