# Generated by Django 6.0.4 on 2026-06-03 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0074_audit_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer_value', models.CharField(blank=True, default='', max_length=500)),
                ('comment', models.TextField(blank=True, default='')),
                ('evidence_url', models.URLField(blank=True, default='', max_length=500)),
                ('finding_required', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Audit Answer',
                'verbose_name_plural': 'Audit Answers',
                'db_table': 'manufacturing_audit_answer',
            },
        ),
        migrations.AlterModelOptions(
            name='audittemplatecategory',
            options={'ordering': ['template', 'sequence'], 'verbose_name': 'Audit Template Section', 'verbose_name_plural': 'Audit Template Sections'},
        ),
        migrations.RemoveField(
            model_name='audittemplate',
            name='is_active',
        ),
        migrations.AddField(
            model_name='audit',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audits', to='manufacturing.audittemplate'),
        ),
        migrations.AddField(
            model_name='audittemplate',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audittemplate',
            name='module_scope',
            field=models.CharField(choices=[('PRODUCTION_CONTROL', 'Production Control'), ('QUALITY_CONTROL', 'Quality Control'), ('SAFETY_CONTROL', 'Safety Control'), ('MATERIAL_CONTROL', 'Material Control')], default='PRODUCTION_CONTROL', max_length=30),
        ),
        migrations.AddField(
            model_name='audittemplate',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20),
        ),
        migrations.AddField(
            model_name='audittemplate',
            name='target_types',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='audittemplatequestion',
            name='help_text',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='audittemplatequestion',
            name='is_required',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='audittemplatequestion',
            name='response_type',
            field=models.CharField(choices=[('PASS_FAIL_NA', 'Pass / Fail / N/A'), ('YES_NO_NA', 'Yes / No / N/A'), ('SCORE_1_5', 'Score 1-5'), ('TEXT', 'Text'), ('NUMBER', 'Number')], default='SCORE_1_5', max_length=20),
        ),
        migrations.AddField(
            model_name='audittemplatequestion',
            name='weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='audit',
            name='audit_type',
            field=models.CharField(choices=[('FIVE_S', '5S'), ('SAFETY', 'Safety'), ('QUALITY', 'Quality'), ('PROCESS_CHECK', 'Process Check'), ('STANDARD_WORK_CHECK', 'Standard Work Check'), ('TPM_EQUIPMENT_CHECK', 'TPM / Equipment Check'), ('KANBAN_PULL_CHECK', 'Kanban / Pull System Check')], max_length=50),
        ),
        migrations.AlterField(
            model_name='audittemplate',
            name='audit_type',
            field=models.CharField(choices=[('FIVE_S', '5S'), ('SAFETY', 'Safety'), ('QUALITY', 'Quality'), ('PROCESS_CHECK', 'Process Check'), ('STANDARD_WORK_CHECK', 'Standard Work Check'), ('TPM_EQUIPMENT_CHECK', 'TPM / Equipment Check'), ('KANBAN_PULL_CHECK', 'Kanban / Pull System Check')], max_length=50),
        ),
        migrations.AddIndex(
            model_name='audit',
            index=models.Index(fields=['template'], name='mfg_audit_template_idx'),
        ),
        migrations.AddField(
            model_name='auditanswer',
            name='audit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='manufacturing.audit'),
        ),
        migrations.AddField(
            model_name='auditanswer',
            name='template_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='manufacturing.audittemplatequestion'),
        ),
        migrations.AddField(
            model_name='auditfinding',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='findings', to='manufacturing.auditanswer'),
        ),
        migrations.AddIndex(
            model_name='auditfinding',
            index=models.Index(fields=['answer'], name='mfg_af_answer_idx'),
        ),
        migrations.AddIndex(
            model_name='auditanswer',
            index=models.Index(fields=['audit'], name='mfg_aa_audit_idx'),
        ),
        migrations.AddIndex(
            model_name='auditanswer',
            index=models.Index(fields=['template_question'], name='mfg_aa_tq_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='auditanswer',
            unique_together={('audit', 'template_question')},
        ),
    ]
