# Generated by Django 6.0.5 on 2026-06-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0075_audit_template_extensions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='audit_type',
            field=models.CharField(choices=[('FIVE_S', '5S'), ('SAFETY', 'Safety'), ('QUALITY', 'Quality'), ('PROCESS_CHECK', 'Process Check'), ('STANDARD_WORK_CHECK', 'Standard Work Check'), ('TPM_EQUIPMENT_CHECK', 'TPM / Equipment Check'), ('KANBAN_PULL_CHECK', 'Kanban / Pull System Check'), ('QC_PRODUCT_CHECK', 'Product Quality Check'), ('QC_PROCESS_AUDIT', 'Process Quality Audit'), ('QC_FIRST_PIECE', 'First Piece Check'), ('QC_FINAL_INSPECTION', 'Final Inspection Audit'), ('QC_DMR_REVIEW', 'DMR Review Check'), ('QC_RMA_REVIEW', 'RMA Review Check')], max_length=50),
        ),
        migrations.AlterField(
            model_name='audittemplate',
            name='audit_type',
            field=models.CharField(choices=[('FIVE_S', '5S'), ('SAFETY', 'Safety'), ('QUALITY', 'Quality'), ('PROCESS_CHECK', 'Process Check'), ('STANDARD_WORK_CHECK', 'Standard Work Check'), ('TPM_EQUIPMENT_CHECK', 'TPM / Equipment Check'), ('KANBAN_PULL_CHECK', 'Kanban / Pull System Check'), ('QC_PRODUCT_CHECK', 'Product Quality Check'), ('QC_PROCESS_AUDIT', 'Process Quality Audit'), ('QC_FIRST_PIECE', 'First Piece Check'), ('QC_FINAL_INSPECTION', 'Final Inspection Audit'), ('QC_DMR_REVIEW', 'DMR Review Check'), ('QC_RMA_REVIEW', 'RMA Review Check')], max_length=50),
        ),
    ]
