"""Domain constants for the improvement app."""

SUGGESTION_STATUS_NEW = "NEW"
SUGGESTION_STATUS_UNDER_REVIEW = "UNDER_REVIEW"
SUGGESTION_STATUS_ACCEPTED = "ACCEPTED"
SUGGESTION_STATUS_REJECTED = "REJECTED"
SUGGESTION_STATUS_CONVERTED_TO_KAIZEN = "CONVERTED_TO_KAIZEN"

SUGGESTION_STATUS_CHOICES = [
    (SUGGESTION_STATUS_NEW, "New"),
    (SUGGESTION_STATUS_UNDER_REVIEW, "Under Review"),
    (SUGGESTION_STATUS_ACCEPTED, "Accepted"),
    (SUGGESTION_STATUS_REJECTED, "Rejected"),
    (SUGGESTION_STATUS_CONVERTED_TO_KAIZEN, "Converted to Kaizen"),
]

KAIZEN_STATUS_PLANNED = "PLANNED"
KAIZEN_STATUS_IN_PROGRESS = "IN_PROGRESS"
KAIZEN_STATUS_COMPLETED = "COMPLETED"
KAIZEN_STATUS_CANCELLED = "CANCELLED"

KAIZEN_STATUS_CHOICES = [
    (KAIZEN_STATUS_PLANNED, "Planned"),
    (KAIZEN_STATUS_IN_PROGRESS, "In Progress"),
    (KAIZEN_STATUS_COMPLETED, "Completed"),
    (KAIZEN_STATUS_CANCELLED, "Cancelled"),
]

KAIZEN_ACTION_STATUS_OPEN = "OPEN"
KAIZEN_ACTION_STATUS_IN_PROGRESS = "IN_PROGRESS"
KAIZEN_ACTION_STATUS_DONE = "DONE"
KAIZEN_ACTION_STATUS_CANCELLED = "CANCELLED"

KAIZEN_ACTION_STATUS_CHOICES = [
    (KAIZEN_ACTION_STATUS_OPEN, "Open"),
    (KAIZEN_ACTION_STATUS_IN_PROGRESS, "In Progress"),
    (KAIZEN_ACTION_STATUS_DONE, "Done"),
    (KAIZEN_ACTION_STATUS_CANCELLED, "Cancelled"),
]

A3_PHASE_DRAFT = "DRAFT"
A3_PHASE_PLAN = "PLAN"
A3_PHASE_DO = "DO"
A3_PHASE_CHECK = "CHECK"
A3_PHASE_ACT = "ACT"
A3_STATUS_COMPLETED = "COMPLETED"
A3_STATUS_CANCELLED = "CANCELLED"

A3_STATUS_CHOICES = [
    (A3_PHASE_DRAFT, "Draft"),
    (A3_PHASE_PLAN, "Plan"),
    (A3_PHASE_DO, "Do"),
    (A3_PHASE_CHECK, "Check"),
    (A3_PHASE_ACT, "Act"),
    (A3_STATUS_COMPLETED, "Completed"),
    (A3_STATUS_CANCELLED, "Cancelled"),
]

A3_ACTION_STATUS_OPEN = "OPEN"
A3_ACTION_STATUS_IN_PROGRESS = "IN_PROGRESS"
A3_ACTION_STATUS_DONE = "DONE"
A3_ACTION_STATUS_CANCELLED = "CANCELLED"

A3_ACTION_STATUS_CHOICES = [
    (A3_ACTION_STATUS_OPEN, "Open"),
    (A3_ACTION_STATUS_IN_PROGRESS, "In Progress"),
    (A3_ACTION_STATUS_DONE, "Done"),
    (A3_ACTION_STATUS_CANCELLED, "Cancelled"),
]

APPROVED_TARGET_TYPES = [
    "Plant", "ProductionLine", "Department", "ResourceGroup", "Resource",
]

SUGGESTION_PRIORITY_LOW = "LOW"
SUGGESTION_PRIORITY_MEDIUM = "MEDIUM"
SUGGESTION_PRIORITY_HIGH = "HIGH"
SUGGESTION_PRIORITY_CRITICAL = "CRITICAL"

SUGGESTION_PRIORITY_CHOICES = [
    (SUGGESTION_PRIORITY_LOW, "Low"),
    (SUGGESTION_PRIORITY_MEDIUM, "Medium"),
    (SUGGESTION_PRIORITY_HIGH, "High"),
    (SUGGESTION_PRIORITY_CRITICAL, "Critical"),
]

KAIZEN_PRIORITY_LOW = "LOW"
KAIZEN_PRIORITY_MEDIUM = "MEDIUM"
KAIZEN_PRIORITY_HIGH = "HIGH"
KAIZEN_PRIORITY_CRITICAL = "CRITICAL"

KAIZEN_PRIORITY_CHOICES = [
    (KAIZEN_PRIORITY_LOW, "Low"),
    (KAIZEN_PRIORITY_MEDIUM, "Medium"),
    (KAIZEN_PRIORITY_HIGH, "High"),
    (KAIZEN_PRIORITY_CRITICAL, "Critical"),
]

SOURCE_TYPE_SUGGESTION = "SUGGESTION"
SOURCE_TYPE_GEMBA = "GEMBA"
SOURCE_TYPE_AUDIT = "AUDIT"
SOURCE_TYPE_MANUAL = "MANUAL"
SOURCE_TYPE_PROCESS_ISSUE = "PROCESS_ISSUE"
SOURCE_TYPE_MER = "MER"

# ── Manufacturing Engineering Request (MER) ──
MER_STATUS_SUBMITTED = "SUBMITTED"
MER_STATUS_UNDER_REVIEW = "UNDER_REVIEW"
MER_STATUS_APPROVED = "APPROVED"
MER_STATUS_IN_PROGRESS = "IN_PROGRESS"
MER_STATUS_COMPLETED = "COMPLETED"
MER_STATUS_REJECTED = "REJECTED"
MER_STATUS_CANCELLED = "CANCELLED"

MER_STATUS_CHOICES = [
    (MER_STATUS_SUBMITTED, "Submitted"),
    (MER_STATUS_UNDER_REVIEW, "Under Review"),
    (MER_STATUS_APPROVED, "Approved"),
    (MER_STATUS_IN_PROGRESS, "In Progress"),
    (MER_STATUS_COMPLETED, "Completed"),
    (MER_STATUS_REJECTED, "Rejected"),
    (MER_STATUS_CANCELLED, "Cancelled"),
]

MER_TYPE_ENGINEERING_CHANGE = "ENGINEERING_CHANGE"
MER_TYPE_TOOLING = "TOOLING"
MER_TYPE_PROCESS_IMPROVEMENT = "PROCESS_IMPROVEMENT"
MER_TYPE_EQUIPMENT_MODIFICATION = "EQUIPMENT_MODIFICATION"

MER_TYPE_CHOICES = [
    (MER_TYPE_ENGINEERING_CHANGE, "Engineering Change"),
    (MER_TYPE_TOOLING, "Tooling Request"),
    (MER_TYPE_PROCESS_IMPROVEMENT, "Process Improvement"),
    (MER_TYPE_EQUIPMENT_MODIFICATION, "Equipment Modification"),
]

MER_CATEGORY_CHOICES = [
    ("SAFETY", "Safety"),
    ("QUALITY", "Quality"),
    ("COST", "Cost Reduction"),
    ("DELIVERY", "Delivery"),
    ("PRODUCTIVITY", "Productivity"),
    ("MAINTENANCE", "Maintenance"),
    ("OTHER", "Other"),
]

MER_PRIORITY_LOW = "LOW"
MER_PRIORITY_MEDIUM = "MEDIUM"
MER_PRIORITY_HIGH = "HIGH"
MER_PRIORITY_CRITICAL = "CRITICAL"

MER_PRIORITY_CHOICES = [
    (MER_PRIORITY_LOW, "Low"),
    (MER_PRIORITY_MEDIUM, "Medium"),
    (MER_PRIORITY_HIGH, "High"),
    (MER_PRIORITY_CRITICAL, "Critical"),
]

SOURCE_TYPE_CHOICES = [
    (SOURCE_TYPE_SUGGESTION, "Suggestion"),
    (SOURCE_TYPE_GEMBA, "Gemba Walk"),
    (SOURCE_TYPE_AUDIT, "Audit"),
    (SOURCE_TYPE_MANUAL, "Manual"),
    (SOURCE_TYPE_PROCESS_ISSUE, "Process Issue"),
    (SOURCE_TYPE_MER, "Manufacturing Engineering Request"),
]
