# Generated by Django 6.0.5 on 2026-06-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkspaceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('WAITING', 'Waiting'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('assigned_to', models.CharField(blank=True, default='', max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('source_type', models.CharField(blank=True, default='', max_length=50)),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('source_title', models.CharField(blank=True, default='', max_length=255)),
                ('source_module', models.CharField(blank=True, default='', max_length=50)),
                ('created_by', models.CharField(blank=True, default='', max_length=255)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_by', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Workspace Task',
                'verbose_name_plural': 'Workspace Tasks',
                'db_table': 'workspace_task',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['assigned_to'], name='wtask_assigned_idx'), models.Index(fields=['status'], name='wtask_status_idx'), models.Index(fields=['priority'], name='wtask_priority_idx'), models.Index(fields=['due_date'], name='wtask_due_idx'), models.Index(fields=['source_type', 'source_id'], name='wtask_source_idx')],
            },
        ),
    ]
