# Generated by Django 6.0.5 on 2026-06-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_chat_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatthread',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='chatthread',
            name='thread_type',
            field=models.CharField(choices=[('DIRECT', 'Direct'), ('GROUP', 'Group')], default='DIRECT', max_length=20),
        ),
    ]
