# Generated by Django 6.0.5 on 2026-06-22 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_chat_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatparticipant',
            name='is_favorited',
            field=models.BooleanField(default=False),
        ),
    ]
