import type { GembaObservation, GembaWalkSession } from "@/types/gemba";

export const mockGembaSession: GembaWalkSession = {
  id: 1,
  lineId: 1,
  plantId: null,
  shiftName: "DAY",
  walkDate: "2026-06-10",
  status: "IN_PROGRESS",
  observer: "Supervisor",
  startedAt: "2026-06-10T06:00:00Z",
  completedAt: null,
  summary: "",
  createdById: 1,
  updatedById: null,
  createdAt: "2026-06-10T05:30:00Z",
  updatedAt: "2026-06-10T06:00:00Z",
};

export const mockGembaObservations: GembaObservation[] = [
  {
    id: 1,
    sessionId: 1,
    targetType: "RESOURCE",
    targetId: 101,
    title: "WIP accumulation before CNC-03",
    description: "12 units queued at CNC-03 input buffer. Cycle time 45.2s vs takt of 40.3s.",
    area: "Precision Machining — CNC-03",
    focus: "WIP accumulation before CNC-03",
    category: "PRODUCTIVITY",
    severity: "HIGH",
    priority: "HIGH",
    linkedResourceText: "CNC-03",
    ownerId: null,
    ownerName: null,
    dueDate: null,
    status: "OPEN",
    resolutionNote: "",
    resolvedById: null,
    resolvedAt: null,
    closedById: null,
    closedAt: null,
    verificationNote: "",
    verifiedById: null,
    verifiedAt: null,
    availableActions: ["ASSIGN","CREATE_ISSUE","CREATE_ACTION","RESOLVE"],
    createdIssueId: 1,
    createdActionId: 2,
    createdById: 1,
    createdByName: "Kenji Nakamura",
    createdAt: "2026-06-10T07:30:00Z",
    updatedAt: "2026-06-10T07:30:00Z",
    locationPath: "Tijuana Plant › C2 Cylinder Assembly › Precision Machining › CNC-03",
    locationLabel: "CNC-03 — Precision Machining",
  },
  {
    id: 2,
    sessionId: 1,
    targetType: "RESOURCE_GROUP",
    targetId: 201,
    title: "Surface scratch defects on cylinder housing",
    description: "Found 5 cylinder housings with surface scratches. Tool wear pattern on CNC-03 boring tool.",
    area: "Visual Inspection Station",
    focus: "Surface scratch defects on cylinder housing",
    category: "QUALITY",
    severity: "HIGH",
    priority: "HIGH",
    linkedResourceText: "Visual Inspection",
    ownerId: null,
    ownerName: null,
    dueDate: "2026-06-12",
    status: "OPEN",
    resolutionNote: "",
    resolvedById: null,
    resolvedAt: null,
    closedById: null,
    closedAt: null,
    verificationNote: "",
    verifiedById: null,
    verifiedAt: null,
    availableActions: ["ASSIGN","CREATE_ISSUE","CREATE_ACTION","RESOLVE"],
    createdIssueId: 2,
    createdActionId: 3,
    createdById: 1,
    createdByName: "Sarah K.",
    createdAt: "2026-06-10T09:30:00Z",
    updatedAt: "2026-06-10T09:30:00Z",
    locationPath: "Tijuana Plant › C2 Cylinder Assembly › Precision Machining",
    locationLabel: "Precision Machining",
  },
  {
    id: 3,
    sessionId: 1,
    targetType: "DEPARTMENT",
    targetId: 301,
    title: "Material rack disorganization",
    description: "Cylinder B material rack disorganized with mixed part numbers. Reorganized and labelled.",
    area: "Sub-Assembly — Station 3",
    focus: "Material rack organization",
    category: "FIVE_S",
    severity: "LOW",
    priority: "MEDIUM",
    linkedResourceText: "Station 3 — Press",
    ownerId: null,
    ownerName: null,
    dueDate: null,
    status: "RESOLVED",
    resolutionNote: "Rack reorganized, team briefed on 5S standards.",
    resolvedById: 1,
    resolvedAt: "2026-06-10T10:00:00Z",
    closedById: null,
    closedAt: null,
    verificationNote: "Confirmed reorganized",
    verifiedById: null,
    verifiedAt: null,
    availableActions: ["VERIFY","CLOSE"],
    createdIssueId: null,
    createdActionId: null,
    createdById: 1,
    createdByName: "Tanaka H.",
    createdAt: "2026-06-10T08:00:00Z",
    updatedAt: "2026-06-10T10:00:00Z",
    locationPath: "Tijuana Plant › C2 Cylinder Assembly",
    locationLabel: "C2 Cylinder Assembly",
  },
  {
    id: 4,
    sessionId: 1,
    targetType: "PRODUCTION_LINE",
    targetId: 401,
    title: "Coolant pump failure on CNC-03",
    description: "Coolant pump failure. Bearing wear in pump motor. Minor coolant leak contained.",
    area: "CNC-03 — Coolant System",
    focus: "Coolant pump failure investigation",
    category: "SAFETY",
    severity: "CRITICAL",
    priority: "URGENT",
    linkedResourceText: "CNC-03",
    ownerId: null,
    ownerName: null,
    dueDate: null,
    status: "IN_REVIEW",
    resolutionNote: "",
    resolvedById: null,
    resolvedAt: null,
    closedById: null,
    closedAt: null,
    verificationNote: "",
    verifiedById: null,
    verifiedAt: null,
    availableActions: ["ASSIGN","RESOLVE"],
    createdIssueId: null,
    createdActionId: 2,
    createdById: 1,
    createdByName: "Carlos G.",
    createdAt: "2026-06-10T11:00:00Z",
    updatedAt: "2026-06-10T11:00:00Z",
    locationPath: "Tijuana Plant › C2 Cylinder Assembly",
    locationLabel: "C2 Cylinder Assembly",
  },
  {
    id: 5,
    sessionId: 1,
    targetType: "PLANT",
    targetId: 501,
    title: "Positive team morale during morning huddle",
    description: "Operator suggested visual aid for torque specs. Quick win implemented.",
    area: "Final Test & Pack",
    focus: "Shift start — team morale",
    category: "MORALE",
    severity: "INFO",
    priority: "LOW",
    linkedResourceText: "",
    ownerId: null,
    ownerName: null,
    dueDate: null,
    status: "CLOSED",
    resolutionNote: "Laminated reference card posted at Assembly Station A.",
    resolvedById: 1,
    resolvedAt: "2026-06-10T07:00:00Z",
    closedById: 1,
    closedAt: "2026-06-10T07:30:00Z",
    verificationNote: "",
    verifiedById: null,
    verifiedAt: null,
    availableActions: ["REOPEN"],
    createdIssueId: null,
    createdActionId: null,
    createdById: 1,
    createdByName: "Lisa M.",
    createdAt: "2026-06-10T06:45:00Z",
    updatedAt: "2026-06-10T07:30:00Z",
    locationPath: "Tijuana Plant",
    locationLabel: "Tijuana Plant",
  },
  {
    id: 6,
    sessionId: 1,
    targetType: "RESOURCE",
    targetId: 102,
    title: "Torque check digitization opportunity",
    description: "Operator manually records torque values on paper. Could be digitized with current torque tool.",
    area: "Final Assembly Line",
    focus: "Torque check process observation",
    category: "PRODUCTIVITY",
    severity: "LOW",
    priority: "LOW",
    linkedResourceText: "Assembly Line A",
    ownerId: null,
    ownerName: null,
    dueDate: null,
    status: "RESOLVED",
    resolutionNote: "Logged as improvement suggestion.",
    resolvedById: 1,
    resolvedAt: "2026-06-09T16:00:00Z",
    closedById: null,
    closedAt: null,
    verificationNote: "",
    verifiedById: null,
    verifiedAt: null,
    availableActions: ["VERIFY","CLOSE"],
    createdIssueId: null,
    createdActionId: null,
    createdById: 1,
    createdByName: "Miguel R.",
    createdAt: "2026-06-09T14:30:00Z",
    updatedAt: "2026-06-09T16:00:00Z",
    locationPath: "Tijuana Plant › Final Assembly Line",
    locationLabel: "Assembly Line A",
  },
  {
    id: 7,
    sessionId: 1,
    targetType: "RESOURCE_GROUP",
    targetId: 202,
    title: "Conveyor sensor alignment issue",
    description: "Conveyor 2 photo-eye sensor knocked out of alignment. Realigned and tested.",
    area: "Material Handling",
    focus: "Conveyor sensor alignment",
    category: "MAINTENANCE",
    severity: "LOW",
    priority: "MEDIUM",
    linkedResourceText: "Conveyor 2",
    ownerId: null,
    ownerName: null,
    dueDate: null,
    status: "RESOLVED",
    resolutionNote: "Sensor realigned. Guard recommended to prevent recurrence.",
    resolvedById: 1,
    resolvedAt: "2026-06-09T11:00:00Z",
    closedById: null,
    closedAt: null,
    verificationNote: "",
    verifiedById: null,
    verifiedAt: null,
    availableActions: ["VERIFY","CLOSE"],
    createdIssueId: null,
    createdActionId: null,
    createdById: 1,
    createdByName: "John D.",
    createdAt: "2026-06-09T10:20:00Z",
    updatedAt: "2026-06-09T11:00:00Z",
    locationPath: "Tijuana Plant › Material Handling",
    locationLabel: "Material Handling",
  },
];

export const mockGembaMetrics = {
  total: mockGembaObservations.length,
  open: mockGembaObservations.filter((o) => o.status === "OPEN").length,
  inReview: mockGembaObservations.filter((o) => o.status === "IN_REVIEW").length,
  actionRequired: mockGembaObservations.filter((o) => o.status === "ACTION_REQUIRED").length,
  converted: mockGembaObservations.filter((o) => o.status.startsWith("CONVERTED")).length,
  resolved: mockGembaObservations.filter((o) => o.status === "RESOLVED").length,
  closed: mockGembaObservations.filter((o) => o.status === "CLOSED").length,
  critical: mockGembaObservations.filter((o) => o.severity === "CRITICAL" && !["RESOLVED", "CLOSED"].includes(o.status)).length,
  overdue: 0,
  byCategory: JSON.stringify({
    PRODUCTIVITY: 2,
    QUALITY: 1,
    SAFETY: 1,
    FIVE_S: 1,
    MAINTENANCE: 1,
    MORALE: 1,
  }),
};

export const mockDailyGembaBoard = {
  activeSession: mockGembaSession,
  observations: mockGembaObservations,
  metrics: mockGembaMetrics,
};
