import type { DashboardQueryData, RecordsQueryData, FiltersQueryData } from "@/types/linePerformance";

export const mockLinePerformanceDashboard: DashboardQueryData = {
  linePerformanceDashboard: {
    line: {
      id: "L001",
      code: "L-CYL",
      name: "C2-Cylinder Assembly",
      plantId: "P1",
      plantName: "Main Plant",
      status: "active",
    },
    shift: {
      id: "S1",
      name: "Morning Shift",
      startTime: "06:00",
      endTime: "14:00",
      date: "2026-06-10",
    },
    kpis: {
      planQuantity: 500,
      actualQuantity: 420,
      gap: -80,
      gapStatus: "behind",
      runRate: 52,
      runRateUnit: "units/hr",
      oeeSignal: 0.72,
      oeeStatus: "warning",
      availability: 0.85,
      performance: 0.88,
      quality: 0.96,
      downtimeMinutes: 45,
      firstPassYield: 0.96,
      qualityStatus: "warning",
    },
    planVsActual: {
      plannedQuantity: 500,
      actualQuantity: 420,
      remainingQuantity: 80,
      gap: -80,
      targetRunRate: 62,
      actualRunRate: 52,
      runRateUnit: "units/hr",
      projectedEndOfShift: 478,
      progressPercent: 84,
      status: "behind",
    },
    oeeSignal: {
      availability: 0.85,
      performance: 0.88,
      quality: 0.96,
      overall: 0.72,
      availabilityStatus: "warning",
      performanceStatus: "good",
      qualityStatus: "good",
      overallStatus: "warning",
      explanation: "OEE below target primarily due to minor stoppages (performance loss) and the material shortage event this morning.",
    },
    downtimeSummary: {
      totalDowntimeMinutes: 45,
      topReason: "Material shortage — Cylinder B rack empty",
      topReasonDurationMinutes: 20,
      activeDowntimeEvent: null,
      totalEvents: 3,
    },
    downtimeEvents: [
      {
        id: "DE-001",
        startTime: "07:15",
        endTime: "07:35",
        durationMinutes: 20,
        reason: "Material shortage — Cylinder B rack empty",
        reasonCode: "MAT-001",
        status: "resolved",
        description: "Awaiting forklift delivery of Cylinder B pallet. Operator notified supervisor at 07:10.",
        linkedIssueId: null,
        linkedActionId: "ACT-001",
        resourceName: "Station 3 — Press",
        resourceGroupName: "Sub-Assembly",
      },
      {
        id: "DE-002",
        startTime: "08:45",
        endTime: "09:00",
        durationMinutes: 15,
        reason: "Micro stoppage — Sensor misalignment",
        reasonCode: "MICRO-003",
        status: "resolved",
        description: "Photo-eye sensor on conveyor 2 knocked out of alignment. Operator reset and re-zeroed.",
        linkedIssueId: null,
        linkedActionId: null,
        resourceName: "Conveyor 2",
        resourceGroupName: "Material Handling",
      },
      {
        id: "DE-003",
        startTime: "10:30",
        endTime: "10:40",
        durationMinutes: 10,
        reason: "Changeover — Model B to Model A",
        reasonCode: "CO-002",
        status: "resolved",
        description: "Scheduled changeover. New fixtures installed, first-piece inspection passed.",
        linkedIssueId: null,
        linkedActionId: null,
        resourceName: "Assembly Line",
        resourceGroupName: "Final Assembly",
      },
    ],
    qualitySummary: {
      goodQuantity: 403,
      rejectedQuantity: 12,
      reworkQuantity: 5,
      scrapQuantity: 7,
      firstPassYield: 0.96,
      defectCount: 8,
      topDefectReason: "Surface scratch on cylinder housing (5 units)",
      linkedIssueCount: 1,
    },
    bottleneckSignal: {
      resourceName: "CNC-03 — Machining Center #3",
      resourceGroupName: "Precision Machining",
      cycleTimeSignal: "45.2s (+12% above takt)",
      queueWipSignal: "12 units queued (+200% above norm)",
      blockedStatus: "running",
      starvedStatus: null,
      runningStatus: "running_at_capacity",
      reasonSummary: "CNC-03 cycle time exceeds takt time by 12%. Downstream stations experiencing 8 min idle per hour. Queue of 12 units indicates bottleneck.",
      attentionMessage: "Immediate: Review CNC-03 program for cycle time reduction. Medium-term: Consider operator support or parallel operation.",
      isConstrained: true,
    },
    linkedIssues: [
      {
        id: "ISS-001",
        title: "CNC-03 cycle time exceeds takt — bottleneck impacting throughput",
        severity: "high",
        status: "open",
        owner: "Miguel R. (Process Eng.)",
        dueDate: "2026-06-14",
        createdAt: "2026-06-10T07:30:00Z",
      },
      {
        id: "ISS-002",
        title: "Surface scratch defect rate rising on cylinder housing",
        severity: "medium",
        status: "open",
        owner: "Sarah K. (Quality)",
        dueDate: "2026-06-12",
        createdAt: "2026-06-10T09:15:00Z",
      },
    ],
    linkedActions: [
      {
        id: "ACT-001",
        title: "Resolve material shortage — 確認 Cylinder B supplier delivery schedule",
        priority: "urgent",
        status: "in_progress",
        assignedTo: "Tanaka H. (Logistics)",
        dueDate: "2026-06-10T14:00:00Z",
        createdAt: "2026-06-10T07:20:00Z",
      },
      {
        id: "ACT-002",
        title: "Analyze CNC-03 cycle time — run time study this shift",
        priority: "high",
        status: "open",
        assignedTo: "Miguel R. (Process Eng.)",
        dueDate: "2026-06-11T14:00:00Z",
        createdAt: "2026-06-10T07:35:00Z",
      },
      {
        id: "ACT-003",
        title: "Investigate surface scratch root cause on cylinder housing",
        priority: "medium",
        status: "open",
        assignedTo: "Sarah K. (Quality)",
        dueDate: "2026-06-12T14:00:00Z",
        createdAt: "2026-06-10T09:20:00Z",
      },
    ],
    timelineEvents: [
      {
        id: "TE-001",
        eventType: "shift_started",
        description: "Morning shift started — 12 operators, 3 supervisors",
        timestamp: "06:00",
        severity: null,
        userId: null,
        userName: null,
      },
      {
        id: "TE-002",
        eventType: "downtime_started",
        description: "Material shortage at Station 3 — Cylinder B rack empty",
        timestamp: "07:15",
        severity: "critical",
        userId: "U001",
        userName: "John D. (Operator)",
      },
      {
        id: "TE-003",
        eventType: "downtime_stopped",
        description: "Material shortage resolved — forklift delivered new pallet",
        timestamp: "07:35",
        severity: null,
        userId: "U002",
        userName: "Sarah F. (Logistics)",
      },
      {
        id: "TE-004",
        eventType: "issue_created",
        description: "Issue #ISS-001: CNC-03 cycle time exceeds takt",
        timestamp: "07:30",
        severity: "high",
        userId: "U003",
        userName: "Miguel R. (Process Eng.)",
      },
      {
        id: "TE-005",
        eventType: "action_created",
        description: "Action #ACT-001: Resolve material shortage",
        timestamp: "07:20",
        severity: "urgent",
        userId: "U004",
        userName: "Tanaka H. (Logistics)",
      },
      {
        id: "TE-006",
        eventType: "production_count_update",
        description: "Production count: 210 units completed (42% of plan)",
        timestamp: "08:00",
        severity: null,
        userId: null,
        userName: "Auto-feed",
      },
      {
        id: "TE-007",
        eventType: "downtime_started",
        description: "Micro stoppage — Sensor misalignment on Conveyor 2",
        timestamp: "08:45",
        severity: "medium",
        userId: "U001",
        userName: "John D. (Operator)",
      },
      {
        id: "TE-008",
        eventType: "downtime_stopped",
        description: "Sensor realigned and conveyor restarted",
        timestamp: "09:00",
        severity: null,
        userId: "U001",
        userName: "John D. (Operator)",
      },
      {
        id: "TE-009",
        eventType: "quality_issue_logged",
        description: "5 cylinder housings rejected — surface scratch defect",
        timestamp: "09:15",
        severity: "medium",
        userId: "U005",
        userName: "Lisa M. (Inspector)",
      },
      {
        id: "TE-010",
        eventType: "bottleneck_detected",
        description: "CNC-03 identified as bottleneck — queue of 12 units",
        timestamp: "09:30",
        severity: "high",
        userId: null,
        userName: "System",
      },
      {
        id: "TE-011",
        eventType: "changeover_started",
        description: "Changeover from Model B to Model A started",
        timestamp: "10:30",
        severity: null,
        userId: "U006",
        userName: "Carlos G. (Setup)",
      },
      {
        id: "TE-012",
        eventType: "changeover_completed",
        description: "Changeover complete — first-piece inspection passed",
        timestamp: "10:40",
        severity: null,
        userId: "U006",
        userName: "Carlos G. (Setup)",
      },
      {
        id: "TE-013",
        eventType: "production_count_update",
        description: "Production count: 420 units completed (84% of plan)",
        timestamp: "11:00",
        severity: null,
        userId: null,
        userName: "Auto-feed",
      },
    ],
    allowedActions: ["refresh", "log_downtime", "create_issue", "create_action"],
    lastUpdatedAt: "2026-06-10T11:00:00Z",
  },
};

export const mockLinePerformanceRecords: RecordsQueryData = {
  linePerformanceRecords: [
    {
      id: "R-001",
      shiftName: "Morning Shift",
      date: "2026-06-10",
      startTime: "06:00",
      endTime: "14:00",
      plannedQuantity: 500,
      actualQuantity: 420,
      gap: -80,
      oeeStatus: "warning",
      downtimeMinutes: 45,
      qualityIssueCount: 2,
      status: "active",
    },
    {
      id: "R-002",
      shiftName: "Afternoon Shift",
      date: "2026-06-10",
      startTime: "14:00",
      endTime: "22:00",
      plannedQuantity: 500,
      actualQuantity: 0,
      gap: 0,
      oeeStatus: "pending",
      downtimeMinutes: 0,
      qualityIssueCount: 0,
      status: "upcoming",
    },
    {
      id: "R-003",
      shiftName: "Night Shift",
      date: "2026-06-10",
      startTime: "22:00",
      endTime: "06:00",
      plannedQuantity: 400,
      actualQuantity: 0,
      gap: 0,
      oeeStatus: "pending",
      downtimeMinutes: 0,
      qualityIssueCount: 0,
      status: "upcoming",
    },
    {
      id: "R-004",
      shiftName: "Morning Shift",
      date: "2026-06-09",
      startTime: "06:00",
      endTime: "14:00",
      plannedQuantity: 500,
      actualQuantity: 485,
      gap: -15,
      oeeStatus: "good",
      downtimeMinutes: 12,
      qualityIssueCount: 1,
      status: "completed",
    },
    {
      id: "R-005",
      shiftName: "Afternoon Shift",
      date: "2026-06-09",
      startTime: "14:00",
      endTime: "22:00",
      plannedQuantity: 500,
      actualQuantity: 510,
      gap: 10,
      oeeStatus: "good",
      downtimeMinutes: 8,
      qualityIssueCount: 0,
      status: "completed",
    },
    {
      id: "R-006",
      shiftName: "Night Shift",
      date: "2026-06-09",
      startTime: "22:00",
      endTime: "06:00",
      plannedQuantity: 400,
      actualQuantity: 380,
      gap: -20,
      oeeStatus: "good",
      downtimeMinutes: 22,
      qualityIssueCount: 1,
      status: "completed",
    },
    {
      id: "R-007",
      shiftName: "Morning Shift",
      date: "2026-06-08",
      startTime: "06:00",
      endTime: "14:00",
      plannedQuantity: 500,
      actualQuantity: 320,
      gap: -180,
      oeeStatus: "critical",
      downtimeMinutes: 95,
      qualityIssueCount: 5,
      status: "completed",
    },
    {
      id: "R-008",
      shiftName: "Afternoon Shift",
      date: "2026-06-08",
      startTime: "14:00",
      endTime: "22:00",
      plannedQuantity: 500,
      actualQuantity: 450,
      gap: -50,
      oeeStatus: "warning",
      downtimeMinutes: 35,
      qualityIssueCount: 2,
      status: "completed",
    },
  ],
};

export const mockLinePerformanceFilters: FiltersQueryData = {
  linePerformanceFilters: {
    shifts: [
      { id: "S1", name: "Morning Shift", startTime: "06:00", endTime: "14:00" },
      { id: "S2", name: "Afternoon Shift", startTime: "14:00", endTime: "22:00" },
      { id: "S3", name: "Night Shift", startTime: "22:00", endTime: "06:00" },
    ],
    dates: ["2026-06-10", "2026-06-09", "2026-06-08", "2026-06-07"],
    statuses: ["active", "completed", "upcoming"],
    downtimeReasons: [
      { id: "DR-001", code: "MAT", name: "Material shortage" },
      { id: "DR-002", code: "MICRO", name: "Micro stoppage" },
      { id: "DR-003", code: "CO", name: "Changeover" },
      { id: "DR-004", code: "BRK", name: "Breakdown" },
      { id: "DR-005", code: "MAINT", name: "Planned maintenance" },
      { id: "DR-006", code: "QUAL", name: "Quality issue" },
      { id: "DR-007", code: "OPR", name: "Operator unavailability" },
      { id: "DR-008", code: "SAFE", name: "Safety stop" },
    ],
  },
};
