import type { LiveShopfloorDashboardQueryData, LiveShopfloorEventsQueryData, LiveShopfloorFiltersQueryData } from "@/types/liveShopfloor";

export const mockLiveShopfloorDashboard: LiveShopfloorDashboardQueryData = {
  liveShopfloorDashboard: {
    lineSummary: {
      id: "L001",
      code: "L-CYL",
      name: "C2-Cylinder Assembly",
      plantId: "P1",
      plantName: "Main Plant — Building 2",
      status: "active",
      displayStatus: "Running",
    },
    shiftSummary: {
      id: "S1",
      name: "Morning Shift",
      startTime: "06:00",
      endTime: "14:00",
      date: "2026-06-10",
      elapsedPercent: 72,
      remainingMinutes: 112,
      supervisor: "Kenji Nakamura",
      crew: "Team A (12 operators)",
    },
    currentProduction: {
      productName: "Cylinder Assembly Type-B",
      productCode: "CYL-B-200",
      partNumber: "PN-200-887",
      productionOrderId: "PO-2026-4581",
      productionOrderNumber: "PO-4581",
      plannedQuantity: 500,
      actualQuantity: 420,
      operationName: "Final Assembly & Test",
      routingStep: "Step 4 / 6",
    },
    liveStatus: {
      lineStatus: "running",
      displayStatus: "Running",
      runState: "Producing at 85% of takt",
      bottleneckResource: "CNC-03 — Machining Center #3",
      lastUpdatedAt: "2026-06-10T11:02:30Z",
    },
    assignedResourceGroups: [
      {
        id: "AL-001",
        resourceGroupId: "RG-001",
        resourceGroupCode: "SUB-ASM",
        resourceGroupName: "Sub-Assembly",
        departmentName: "Assembly Dept",
        sequence: 1,
        status: "running",
        displayStatus: "Running",
        activeOperation: "Cylinder body pressing",
        activeDowntimeReason: null,
        issueCount: 0,
        actionCount: 0,
        lastUpdated: "11:00",
      },
      {
        id: "AL-002",
        resourceGroupId: "RG-002",
        resourceGroupCode: "PREC-MACH",
        resourceGroupName: "Precision Machining",
        departmentName: "Machining Dept",
        sequence: 2,
        status: "stopped",
        displayStatus: "Stopped",
        activeOperation: "CNC boring — Cylinder housing",
        activeDowntimeReason: "10:45 — Coolant pump failure on CNC-03",
        issueCount: 2,
        actionCount: 1,
        lastUpdated: "11:01",
      },
      {
        id: "AL-003",
        resourceGroupId: "RG-003",
        resourceGroupCode: "MAT-HAND",
        resourceGroupName: "Material Handling",
        departmentName: "Logistics Dept",
        sequence: 3,
        status: "running",
        displayStatus: "Running",
        activeOperation: "Kitting — Cylinder B",
        activeDowntimeReason: "08:45 sensor issue (resolved)",
        issueCount: 0,
        actionCount: 0,
        lastUpdated: "10:40",
      },
      {
        id: "AL-004",
        resourceGroupId: "RG-004",
        resourceGroupCode: "QUALITY",
        resourceGroupName: "Quality Inspection",
        departmentName: "Quality Dept",
        sequence: 4,
        status: "running",
        displayStatus: "Running",
        activeOperation: "In-process inspection — Cylinder housing",
        activeDowntimeReason: null,
        issueCount: 1,
        actionCount: 1,
        lastUpdated: "11:00",
      },
      {
        id: "AL-005",
        resourceGroupId: "RG-005",
        resourceGroupCode: "FIN-ASM",
        resourceGroupName: "Final Assembly",
        departmentName: "Assembly Dept",
        sequence: 5,
        status: "running",
        displayStatus: "Running",
        activeOperation: "Seal installation & torque",
        activeDowntimeReason: null,
        issueCount: 0,
        actionCount: 0,
        lastUpdated: "11:00",
      },
      {
        id: "AL-006",
        resourceGroupId: "RG-006",
        resourceGroupCode: "TEST",
        resourceGroupName: "Final Test & Pack",
        departmentName: "Quality Dept",
        sequence: 6,
        status: "idle",
        displayStatus: "Starved",
        activeOperation: "Leak test & packaging",
        activeDowntimeReason: null,
        issueCount: 0,
        actionCount: 0,
        lastUpdated: "10:55",
      },
    ],
    resourceStatuses: [
      { id: "RS-001", name: "Press #1", code: "PR-01", resourceGroupId: "RG-001", resourceGroupName: "Sub-Assembly", status: "running", displayStatus: "Running", currentOperation: "Cylinder body pressing", activeDowntimeEventId: null, activeDowntimeReason: null, lastUpdated: "11:00" },
      { id: "RS-002", name: "Press #2", code: "PR-02", resourceGroupId: "RG-001", resourceGroupName: "Sub-Assembly", status: "idle", displayStatus: "Idle", currentOperation: "Setup for next batch", activeDowntimeEventId: null, activeDowntimeReason: null, lastUpdated: "10:50" },
      { id: "RS-003", name: "CNC-03", code: "CNC-03", resourceGroupId: "RG-002", resourceGroupName: "Precision Machining", status: "stopped", displayStatus: "Stopped", currentOperation: "Boring — Cylinder housing", activeDowntimeEventId: "DE-003", activeDowntimeReason: "Coolant pump failure", lastUpdated: "10:50" },
      { id: "RS-004", name: "CNC-04", code: "CNC-04", resourceGroupId: "RG-002", resourceGroupName: "Precision Machining", status: "running", displayStatus: "Running", currentOperation: "Thread cutting", activeDowntimeEventId: null, activeDowntimeReason: null, lastUpdated: "11:00" },
      { id: "RS-005", name: "CNC-05", code: "CNC-05", resourceGroupId: "RG-002", resourceGroupName: "Precision Machining", status: "changeover", displayStatus: "Changeover", currentOperation: "Tool change — Model A", activeDowntimeEventId: null, activeDowntimeReason: null, lastUpdated: "10:55" },
      { id: "RS-006", name: "Conveyor 1", code: "CV-01", resourceGroupId: "RG-003", resourceGroupName: "Material Handling", status: "running", displayStatus: "Running", currentOperation: "Transport — Cylinder bodies", activeDowntimeEventId: null, activeDowntimeReason: null, lastUpdated: "11:00" },
      { id: "RS-007", name: "Conveyor 2", code: "CV-02", resourceGroupId: "RG-003", resourceGroupName: "Material Handling", status: "running", displayStatus: "Running", currentOperation: "Transport — Finished parts", activeDowntimeEventId: "DE-002", activeDowntimeReason: "Sensor issue (resolved 09:00)", lastUpdated: "10:40" },
      { id: "RS-008", name: "CMM Station", code: "CMM-01", resourceGroupId: "RG-004", resourceGroupName: "Quality Inspection", status: "running", displayStatus: "Running", currentOperation: "CMM measurement — Cylinder housing", activeDowntimeEventId: null, activeDowntimeReason: null, lastUpdated: "11:00" },
      { id: "RS-009", name: "Visual Inspection", code: "VI-01", resourceGroupId: "RG-004", resourceGroupName: "Quality Inspection", status: "running", displayStatus: "Running", currentOperation: "Surface finish check", activeDowntimeEventId: null, activeDowntimeReason: null, lastUpdated: "10:55" },
      { id: "RS-010", name: "Assembly Line A", code: "ASM-A", resourceGroupId: "RG-005", resourceGroupName: "Final Assembly", status: "running", displayStatus: "Running", currentOperation: "Seal installation", activeDowntimeEventId: null, activeDowntimeReason: null, lastUpdated: "11:00" },
      { id: "RS-011", name: "Torque Station", code: "TQ-01", resourceGroupId: "RG-005", resourceGroupName: "Final Assembly", status: "running", displayStatus: "Running", currentOperation: "Bolt torque — 45 Nm", activeDowntimeEventId: null, activeDowntimeReason: null, lastUpdated: "11:00" },
      { id: "RS-012", name: "Leak Tester", code: "LT-01", resourceGroupId: "RG-006", resourceGroupName: "Final Test & Pack", status: "idle", displayStatus: "Starved", currentOperation: "Waiting for units", activeDowntimeEventId: null, activeDowntimeReason: null, lastUpdated: "10:55" },
      { id: "RS-013", name: "Pack Station", code: "PK-01", resourceGroupId: "RG-006", resourceGroupName: "Final Test & Pack", status: "idle", displayStatus: "Starved", currentOperation: "Waiting for tested units", activeDowntimeEventId: null, activeDowntimeReason: null, lastUpdated: "10:50" },
    ],
    resourceGroupStatusSummary: {
      runningCount: 4,
      stoppedCount: 1,
      blockedCount: 0,
      starvedCount: 1,
      maintenanceCount: 0,
      unknownCount: 0,
      activeBottleneckResource: "CNC-03 — Machining Center #3",
    },
    activeDowntime: {
      id: "DE-003",
      startTime: "10:45",
      reason: "Coolant pump failure on CNC-03",
      reasonCode: "BRK-004",
      durationMinutes: 17,
      status: "active",
      displayStatus: "Active",
      affectedResourceName: "CNC-03",
      affectedResourceGroupName: "Precision Machining",
      linkedIssueId: null,
      linkedActionId: "ACT-002",
      owner: "Carlos G. (Maintenance)",
    },
    recentDowntimeEvents: [
      {
        id: "DE-001",
        startTime: "07:15",
        endTime: "07:35",
        durationMinutes: 20,
        reason: "Material shortage — Cylinder B rack empty",
        reasonCode: "MAT-001",
        status: "resolved",
        displayStatus: "Resolved",
        affectedResourceName: "Station 3 — Press",
        affectedResourceGroupName: "Sub-Assembly",
      },
      {
        id: "DE-002",
        startTime: "08:45",
        endTime: "09:00",
        durationMinutes: 15,
        reason: "Micro stoppage — Sensor misalignment",
        reasonCode: "MICRO-003",
        status: "resolved",
        displayStatus: "Resolved",
        affectedResourceName: "Conveyor 2",
        affectedResourceGroupName: "Material Handling",
      },
    ],
    bottleneckSignal: {
      resourceName: "CNC-03 — Machining Center #3",
      resourceGroupName: "Precision Machining",
      cycleTimeSignal: "45.2s (+12% above takt of 40.3s)",
      queueWipSignal: "12 units queued (norm: 3–5)",
      blockedStatus: "running",
      starvedStatus: null,
      runningStatus: "running_at_capacity",
      reasonSummary: "CNC-03 running at 112% of takt time. Queue building upstream. Downstream Final Test & Pack starved.",
      attentionMessage: "Run time study on CNC-03 this shift. Consider operator assist or program optimization.",
      isConstrained: true,
    },
    openIssues: [
      {
        id: "ISS-001",
        title: "CNC-03 cycle time exceeds takt — bottleneck impacting throughput",
        severity: "high",
        displaySeverity: "High",
        status: "open",
        displayStatus: "Open",
        owner: "Miguel R. (Process Eng.)",
        dueDate: "2026-06-14",
        createdAt: "2026-06-10T07:30:00Z",
        sourceType: "LINE_PERFORMANCE",
        linkedResourceName: "CNC-03",
        linkedResourceGroupName: "Precision Machining",
      },
      {
        id: "ISS-002",
        title: "Surface scratch defect rate rising on cylinder housing",
        severity: "medium",
        displaySeverity: "Medium",
        status: "open",
        displayStatus: "Open",
        owner: "Sarah K. (Quality)",
        dueDate: "2026-06-12",
        createdAt: "2026-06-10T09:15:00Z",
        sourceType: "QUALITY_CONTROL",
        linkedResourceName: "Visual Inspection",
        linkedResourceGroupName: "Quality Inspection",
      },
    ],
    openActions: [
      {
        id: "ACT-001",
        title: "Resolve material shortage — confirm Cylinder B supplier delivery",
        priority: "urgent",
        displayPriority: "Urgent",
        status: "in_progress",
        displayStatus: "In Progress",
        assignedTo: "Tanaka H. (Logistics)",
        dueDate: "2026-06-10T14:00:00Z",
        createdAt: "2026-06-10T07:20:00Z",
        sourceType: "LINE_PERFORMANCE",
        linkedResourceName: "Station 3 — Press",
        linkedResourceGroupName: "Sub-Assembly",
      },
      {
        id: "ACT-002",
        title: "Run CNC-03 cycle time study this shift",
        priority: "high",
        displayPriority: "High",
        status: "open",
        displayStatus: "Open",
        assignedTo: "Miguel R. (Process Eng.)",
        dueDate: "2026-06-11T14:00:00Z",
        createdAt: "2026-06-10T07:35:00Z",
        sourceType: "LINE_PERFORMANCE",
        linkedResourceName: "CNC-03",
        linkedResourceGroupName: "Precision Machining",
      },
      {
        id: "ACT-003",
        title: "Investigate surface scratch root cause on cylinder housing",
        priority: "medium",
        displayPriority: "Medium",
        status: "open",
        displayStatus: "Open",
        assignedTo: "Sarah K. (Quality)",
        dueDate: "2026-06-12T14:00:00Z",
        createdAt: "2026-06-10T09:20:00Z",
        sourceType: "QUALITY_CONTROL",
        linkedResourceName: "Visual Inspection",
        linkedResourceGroupName: "Quality Inspection",
      },
    ],
    timelineEvents: [
      { id: "TE-001", eventType: "shift_started", description: "Morning shift started — 12 operators, 3 supervisors on floor", timestamp: "06:00", severity: null, displaySeverity: null, userId: null, userName: null, linkedResourceName: null, linkedResourceGroupName: null },
      { id: "TE-002", eventType: "downtime_started", description: "Material shortage at Station 3 — Cylinder B rack empty", timestamp: "07:15", severity: "critical", displaySeverity: "Critical", userId: "U001", userName: "John D. (Operator)", linkedResourceName: "Station 3 — Press", linkedResourceGroupName: "Sub-Assembly" },
      { id: "TE-003", eventType: "downtime_closed", description: "Material shortage resolved — forklift delivered new pallet", timestamp: "07:35", severity: null, displaySeverity: null, userId: "U002", userName: "Sarah F. (Logistics)", linkedResourceName: "Station 3 — Press", linkedResourceGroupName: "Sub-Assembly" },
      { id: "TE-004", eventType: "issue_created", description: "Issue created: CNC-03 cycle time exceeds takt", timestamp: "07:30", severity: "high", displaySeverity: "High", userId: "U003", userName: "Miguel R.", linkedResourceName: "CNC-03", linkedResourceGroupName: "Precision Machining" },
      { id: "TE-005", eventType: "action_created", description: "Action created: Resolve material shortage with supplier", timestamp: "07:20", severity: null, displaySeverity: null, userId: "U004", userName: "Tanaka H.", linkedResourceName: "Station 3", linkedResourceGroupName: "Sub-Assembly" },
      { id: "TE-006", eventType: "production_count_update", description: "Production count: 210 units (42% of plan)", timestamp: "08:00", severity: null, displaySeverity: null, userId: null, userName: "Auto-feed", linkedResourceName: null, linkedResourceGroupName: null },
      { id: "TE-007", eventType: "resource_status_changed", description: "Conveyor 2 sensor misalignment — micro stoppage", timestamp: "08:45", severity: "medium", displaySeverity: "Medium", userId: "U001", userName: "John D.", linkedResourceName: "Conveyor 2", linkedResourceGroupName: "Material Handling" },
      { id: "TE-008", eventType: "resource_status_changed", description: "Conveyor 2 restarted after sensor realignment", timestamp: "09:00", severity: null, displaySeverity: null, userId: "U001", userName: "John D.", linkedResourceName: "Conveyor 2", linkedResourceGroupName: "Material Handling" },
      { id: "TE-009", eventType: "quality_alert", description: "5 cylinder housings rejected — surface scratch defect", timestamp: "09:15", severity: "medium", displaySeverity: "Medium", userId: "U005", userName: "Lisa M. (Inspector)", linkedResourceName: "Visual Inspection", linkedResourceGroupName: "Quality Inspection" },
      { id: "TE-010", eventType: "bottleneck_detected", description: "CNC-03 identified as bottleneck (12 units queued)", timestamp: "09:30", severity: "high", displaySeverity: "High", userId: null, userName: "System", linkedResourceName: "CNC-03", linkedResourceGroupName: "Precision Machining" },
      { id: "TE-011", eventType: "changeover_started", description: "CNC-05 changeover: Model B → Model A tools", timestamp: "10:30", severity: null, displaySeverity: null, userId: "U006", userName: "Carlos G. (Setup)", linkedResourceName: "CNC-05", linkedResourceGroupName: "Precision Machining" },
      { id: "TE-012", eventType: "production_count_update", description: "Production count: 420 units (84% of plan)", timestamp: "11:00", severity: null, displaySeverity: null, userId: null, userName: "Auto-feed", linkedResourceName: null, linkedResourceGroupName: null },
      { id: "TE-013", eventType: "downtime_started", description: "CNC-03 coolant pump failure — unplanned maintenance started on Precision Machining", timestamp: "10:45", severity: "critical", displaySeverity: "Critical", userId: "U006", userName: "Carlos G. (Operator)", linkedResourceName: "CNC-03", linkedResourceGroupName: "Precision Machining" },
    ],
    allowedActions: ["refresh", "log_downtime", "close_downtime", "create_issue", "create_action"],
    lastUpdatedAt: "2026-06-10T11:02:30Z",
  },
};

export const mockLiveShopfloorEvents: LiveShopfloorEventsQueryData = {
  liveShopfloorEvents: [
    {
      id: "EVT-008",
      eventType: "downtime",
      displayType: "Downtime",
      title: "CNC-03 coolant pump failure",
      summary: "Precision Machining stopped — pump replacement in progress",
      description: "CNC-03 coolant pump failed at 10:45. Maintenance team dispatched. Estimated repair time: 45 min.",
      severity: "critical",
      displaySeverity: "Critical",
      status: "active",
      displayStatus: "Active",
      timestamp: "10:45",
      linkedResourceName: "CNC-03",
      linkedResourceGroupName: "Precision Machining",
      linkedIssueId: null,
      linkedActionId: "ACT-002",
    },
    {
      id: "EVT-001",
      eventType: "downtime",
      displayType: "Downtime",
      title: "Material shortage at Station 3",
      summary: "Cylinder B rack empty — 20 min lost",
      description: "Operator John D. reported empty Cylinder B rack at 07:10. Forklift delivery arrived at 07:35.",
      severity: "critical",
      displaySeverity: "Critical",
      status: "resolved",
      displayStatus: "Resolved",
      timestamp: "07:15",
      linkedResourceName: "Station 3 — Press",
      linkedResourceGroupName: "Sub-Assembly",
      linkedIssueId: null,
      linkedActionId: "ACT-001",
    },
    {
      id: "EVT-002",
      eventType: "bottleneck",
      displayType: "Bottleneck",
      title: "CNC-03 at capacity — bottleneck active",
      summary: "Cycle time 12% above takt, 12 units queued",
      description: "CNC-03 running at 45.2s/unit vs takt of 40.3s. Downstream starved.",
      severity: "high",
      displaySeverity: "High",
      status: "active",
      displayStatus: "Active",
      timestamp: "09:30",
      linkedResourceName: "CNC-03",
      linkedResourceGroupName: "Precision Machining",
      linkedIssueId: "ISS-001",
      linkedActionId: "ACT-002",
    },
    {
      id: "EVT-003",
      eventType: "quality_alert",
      displayType: "Quality Alert",
      title: "Surface scratch defect — 5 rejects",
      summary: "Cylinder housing surface finish out of spec",
      description: "Visual inspection at 09:15 found surface scratches on 5 cylinder housings. Possible tool wear on CNC-03.",
      severity: "medium",
      displaySeverity: "Medium",
      status: "open",
      displayStatus: "Open",
      timestamp: "09:15",
      linkedResourceName: "Visual Inspection",
      linkedResourceGroupName: "Quality Inspection",
      linkedIssueId: "ISS-002",
      linkedActionId: "ACT-003",
    },
    {
      id: "EVT-004",
      eventType: "downtime",
      displayType: "Downtime",
      title: "Micro stoppage — Conveyor 2 sensor",
      summary: "Photo-eye misalignment — 15 min lost",
      description: "Conveyor 2 photo-eye sensor knocked out of alignment during material movement.",
      severity: "medium",
      displaySeverity: "Medium",
      status: "resolved",
      displayStatus: "Resolved",
      timestamp: "08:45",
      linkedResourceName: "Conveyor 2",
      linkedResourceGroupName: "Material Handling",
      linkedIssueId: null,
      linkedActionId: null,
    },
    {
      id: "EVT-005",
      eventType: "issue",
      displayType: "Issue",
      title: "Open issue: CNC-03 cycle time",
      summary: "Process engineering investigating cycle time reduction",
      description: "High severity issue assigned to Miguel R. due by June 14.",
      severity: "high",
      displaySeverity: "High",
      status: "open",
      displayStatus: "Open",
      timestamp: "07:30",
      linkedResourceName: "CNC-03",
      linkedResourceGroupName: "Precision Machining",
      linkedIssueId: "ISS-001",
      linkedActionId: "ACT-002",
    },
    {
      id: "EVT-006",
      eventType: "action",
      displayType: "Action",
      title: "Urgent: Resolve material shortage — supplier contact",
      summary: "Tanaka H. contacting Cylinder B supplier for expedited delivery",
      description: "Urgent action assigned to Tanaka H. in Logistics. Due end of shift.",
      severity: "low",
      displaySeverity: "Low",
      status: "in_progress",
      displayStatus: "In Progress",
      timestamp: "07:20",
      linkedResourceName: "Station 3 — Press",
      linkedResourceGroupName: "Sub-Assembly",
      linkedIssueId: null,
      linkedActionId: "ACT-001",
    },
    {
      id: "EVT-007",
      eventType: "status_change",
      displayType: "Status Change",
      title: "Changeover started on CNC-05",
      summary: "Model B → Model A tool change in progress",
      description: "Setup operator Carlos G. performing standard changeover. Expected completion: 15 min.",
      severity: "low",
      displaySeverity: "Low",
      status: "active",
      displayStatus: "Active",
      timestamp: "10:30",
      linkedResourceName: "CNC-05",
      linkedResourceGroupName: "Precision Machining",
      linkedIssueId: null,
      linkedActionId: null,
    },
  ],
};

export const mockLiveShopfloorFilters: LiveShopfloorFiltersQueryData = {
  liveShopfloorFilters: {
    shifts: [
      { id: "S1", name: "Morning Shift", startTime: "06:00", endTime: "14:00" },
      { id: "S2", name: "Afternoon Shift", startTime: "14:00", endTime: "22:00" },
      { id: "S3", name: "Night Shift", startTime: "22:00", endTime: "06:00" },
    ],
    downtimeReasons: [
      { id: "DR-001", code: "MAT", name: "Material shortage" },
      { id: "DR-002", code: "MICRO", name: "Micro stoppage" },
      { id: "DR-003", code: "CO", name: "Changeover" },
      { id: "DR-004", code: "BRK", name: "Breakdown" },
      { id: "DR-005", code: "MAINT", name: "Planned maintenance" },
      { id: "DR-006", code: "QUAL", name: "Quality issue" },
      { id: "DR-007", code: "OPR", name: "Operator unavailability" },
      { id: "DR-008", code: "SAFE", name: "Safety stop" },
    ],
    eventTypes: ["downtime", "quality_alert", "material_shortage", "safety_alert", "issue", "action", "bottleneck", "status_change"],
    statusFilters: ["active", "resolved", "open", "in_progress", "closed"],
  },
};
