// ── Maintenance Mock Data ──
// Provides fallback data for all maintenance pages when backend resolvers are unavailable.

export const mockMaintenanceSummary = {
  maintenanceSummary: {
    openWorkOrders: 5,
    overdueWorkOrders: 2,
    activeBreakdowns: 3,
    pmDueThisWeek: 4,
    completedWorkOrders: 12,
    totalDowntimeMinutes: 245,
    lowStockSpareParts: 3,
    lastUpdated: "2026-06-10T11:00:00Z",
  },
};

export const mockWorkOrderDashboard = {
  workOrderDashboard: {
    openWorkOrders: 5,
    inProgress: 2,
    overdue: 2,
    completed: 12,
    preventive: 3,
    correctiveBreakdown: 4,
    waitingParts: 1,
    dueThisWeek: 4,
    totalDowntimeMinutes: 245,
    lastUpdated: "2026-06-10T11:00:00Z",
  },
};

// ── 5 Work Orders ──

export const mockMaintenanceWorkOrders = {
  maintenanceWorkOrders: [
    {
      id: 1,
      number: "WO-2026-001",
      title: "Lubricate press brake #3 — monthly PM",
      description: "Monthly preventive lubrication of press brake #3. Grease all fittings, check oil levels, and inspect hydraulic lines for wear.",
      workOrderType: "PREVENTIVE",
      targetType: "RESOURCE",
      targetId: 1,
      plantId: 1,
      productionLineId: 1,
      departmentId: 1,
      resourceGroupId: 1,
      resourceId: 1,
      priority: "MEDIUM",
      status: "IN_PROGRESS",
      requestedBy: "Carlos M. (Maintenance Lead)",
      assignedTo: "Roberto F. (Technician)",
      dateOpened: "2026-06-08",
      dueDate: "2026-06-12",
      plannedStartDate: "2026-06-10",
      plannedEndDate: "2026-06-10",
      actualStartDate: "2026-06-10T08:00:00Z",
      actualEndDate: null,
      downtimeMinutes: null,
      workInstructions: "1. Lock-out/Tag-out press brake #3\n2. Grease all 8 zerk fittings on slide ways\n3. Check hydraulic oil level — top off if below min line\n4. Inspect hydraulic hoses for cracks or leaks\n5. Wipe down slide ways and apply way oil\n6. Remove LOTO, test cycle 5 times\n7. Record oil added and observations",
      failureMode: "",
      safetyNotes: "⚠ LOTO required. Press brake #3 disconnect switch located on rear panel. Verify zero energy state before opening panels.",
      laborEstimate: 2.5,
      completionNotes: "",
      rootCause: "",
      correctiveAction: "",
      verificationResult: "",
      sparePartsRequired: null,
      attachments: null,
      linkedPmId: 1,
      linkedBreakdownId: null,
      createdAt: "2026-06-08T14:00:00Z",
      updatedAt: "2026-06-10T08:15:00Z",
    },
    {
      id: 2,
      number: "WO-2026-002",
      title: "CNC-03 coolant pump replacement",
      description: "Coolant pump on CNC-03 failed at 10:45. Pump not priming — likely impeller damage or motor burnout. Replace pump and verify coolant flow.",
      workOrderType: "BREAKDOWN",
      targetType: "RESOURCE",
      targetId: 3,
      plantId: 1,
      productionLineId: 1,
      departmentId: 2,
      resourceGroupId: 2,
      resourceId: 3,
      priority: "CRITICAL",
      status: "IN_PROGRESS",
      requestedBy: "Carlos G. (Operator)",
      assignedTo: "Ana R. (Maintenance Tech)",
      dateOpened: "2026-06-10",
      dueDate: "2026-06-10",
      plannedStartDate: "2026-06-10",
      plannedEndDate: "2026-06-10",
      actualStartDate: "2026-06-10T10:50:00Z",
      actualEndDate: null,
      downtimeMinutes: 35,
      workInstructions: "1. Verify LOTO on CNC-03 — disconnect main power\n2. Drain coolant tank into waste drum\n3. Disconnect pump electrical (tag wires)\n4. Remove pump mounting bolts (4x M8)\n5. Install new pump — torque bolts to 25 Nm\n6. Reconnect electrical — verify rotation direction\n7. Fill coolant tank, prime pump\n8. Test run 10 min — check for leaks, verify flow rate\n9. Record pump model/serial on work order",
      failureMode: "Coolant pump not priming. Motor runs but no flow. Impeller likely damaged by debris or bearing failure.",
      safetyNotes: "⚠ LOTO required. Coolant is water-soluble oil — wear nitrile gloves. Dispose of old coolant per environmental guidelines.",
      laborEstimate: 3.0,
      completionNotes: "",
      rootCause: "",
      correctiveAction: "",
      verificationResult: "",
      sparePartsRequired: "Coolant pump assembly (PN: CNC-PMP-003), Gasket set (PN: GSK-004)",
      attachments: null,
      linkedPmId: null,
      linkedBreakdownId: 1,
      createdAt: "2026-06-10T10:50:00Z",
      updatedAt: "2026-06-10T11:00:00Z",
    },
    {
      id: 3,
      number: "WO-2026-003",
      title: "Conveyor 2 sensor realignment & bracket reinforcement",
      description: "Photo-eye sensor on Conveyor 2 was knocked out of alignment. Reinforce sensor bracket to prevent recurrence. Realign and test.",
      workOrderType: "CORRECTIVE",
      targetType: "RESOURCE",
      targetId: 6,
      plantId: 1,
      productionLineId: 1,
      departmentId: 3,
      resourceGroupId: 3,
      resourceId: 6,
      priority: "HIGH",
      status: "OPEN",
      requestedBy: "John D. (Operator)",
      assignedTo: "Roberto F. (Technician)",
      dateOpened: "2026-06-10",
      dueDate: "2026-06-11",
      plannedStartDate: null,
      plannedEndDate: null,
      actualStartDate: null,
      actualEndDate: null,
      downtimeMinutes: 15,
      workInstructions: "1. Inspect sensor bracket for damage\n2. Weld reinforcement gusset if bracket is bent\n3. Realign sensor to target reflector\n4. Test 10 cycles at slow speed\n5. Verify read range with photoelectric sensor tester\n6. Record alignment values",
      failureMode: "Photo-eye sensor misaligned — intermittent detection failures causing micro stoppages.",
      safetyNotes: "Conveyor 2 can be isolated at local disconnect. No LOTO required for adjustment work. Watch for moving chain during testing.",
      laborEstimate: 1.0,
      completionNotes: "",
      rootCause: "",
      correctiveAction: "",
      verificationResult: "",
      sparePartsRequired: null,
      attachments: null,
      linkedPmId: null,
      linkedBreakdownId: 2,
      createdAt: "2026-06-10T09:00:00Z",
      updatedAt: "2026-06-10T09:00:00Z",
    },
    {
      id: 4,
      number: "WO-2026-004",
      title: "Annual calibration — torque wrenches (Set A)",
      description: "Annual recalibration of 12 torque wrenches in Set A (5–150 Nm range). Send to external lab. Issue loaner set during calibration period.",
      workOrderType: "CALIBRATION",
      targetType: "DEPARTMENT",
      targetId: 1,
      plantId: 1,
      productionLineId: null,
      departmentId: 1,
      resourceGroupId: null,
      resourceId: null,
      priority: "LOW",
      status: "DRAFT",
      requestedBy: "Quality Manager",
      assignedTo: "Lisa M. (Inspector)",
      dateOpened: "2026-06-09",
      dueDate: "2026-06-30",
      plannedStartDate: "2026-06-20",
      plannedEndDate: "2026-06-27",
      actualStartDate: null,
      actualEndDate: null,
      downtimeMinutes: null,
      workInstructions: "1. Collect all 12 torque wrenches from Set A (tool crib)\n2. Verify inventory against calibration log\n3. Package each wrench in protective case\n4. Complete calibration request form\n5. Ship to accredited calibration lab (use overnight)\n6. Issue loaner set B to affected stations\n7. Update calibration log with due dates",
      failureMode: "",
      safetyNotes: "Loaner set must be verified before use — check calibration stickers. Do not use for critical torque applications without verification.",
      laborEstimate: 4.0,
      completionNotes: "",
      rootCause: "",
      correctiveAction: "",
      verificationResult: "",
      sparePartsRequired: null,
      attachments: null,
      linkedPmId: null,
      linkedBreakdownId: null,
      createdAt: "2026-06-09T10:00:00Z",
      updatedAt: "2026-06-09T10:00:00Z",
    },
    {
      id: 5,
      number: "WO-2026-005",
      title: "Hydraulic power unit — filter & oil change",
      description: "Quarterly maintenance on hydraulic power unit HPU-02. Replace return filter, change hydraulic oil, and inspect accumulator pre-charge.",
      workOrderType: "PREVENTIVE",
      targetType: "RESOURCE",
      targetId: 8,
      plantId: 1,
      productionLineId: 1,
      departmentId: 2,
      resourceGroupId: 2,
      resourceId: 8,
      priority: "MEDIUM",
      status: "WAITING_PARTS",
      requestedBy: "Maintenance Planner",
      assignedTo: "Roberto F. (Technician)",
      dateOpened: "2026-06-07",
      dueDate: "2026-06-11",
      plannedStartDate: null,
      plannedEndDate: null,
      actualStartDate: null,
      actualEndDate: null,
      downtimeMinutes: null,
      workInstructions: "1. LOTO HPU-02 — disconnect motor starter\n2. Relieve system pressure (open bleed valve)\n3. Remove return filter — replace with new (PN: HYD-FLT-002)\n4. Drain hydraulic oil into waste drum\n5. Refill with ISO VG 46 hydraulic oil (35 gallons)\n6. Check accumulator pre-charge — top off to 1200 psi if needed\n7. Start HPU, cycle 5 min to purge air\n8. Check for leaks at all fittings\n9. Record oil added, filter PN, accumulator pressure",
      failureMode: "",
      safetyNotes: "⚠ High pressure hydraulic system. LOTO required. Relieve ALL pressure before opening system. Hydraulic oil at 150°F — risk of burns. Wear oil-resistant gloves and safety glasses.",
      laborEstimate: 3.5,
      completionNotes: "",
      rootCause: "",
      correctiveAction: "",
      verificationResult: "",
      sparePartsRequired: "Return filter (PN: HYD-FLT-002), Hydraulic oil ISO VG 46 (35 gal)",
      attachments: null,
      linkedPmId: 2,
      linkedBreakdownId: null,
      createdAt: "2026-06-07T08:00:00Z",
      updatedAt: "2026-06-09T14:00:00Z",
    },
  ],
};

// ── 5 PM Plans ──

export const mockPmPlans = {
  preventiveMaintenancePlans: [
    {
      id: 1,
      code: "PM-LUBE-001",
      title: "Monthly lubrication — press brake #3",
      description: "Monthly preventive lubrication of press brake #3. Grease fittings, check oil levels, inspect hydraulic lines.",
      targetType: "RESOURCE",
      targetId: 1,
      frequency: "MONTHLY",
      intervalValue: 30,
      nextDueDate: "2026-06-12",
      lastCompletedDate: "2026-05-12",
      assignedTo: "Roberto F.",
      priority: "MEDIUM",
      status: "ACTIVE",
      checklistJson: JSON.stringify([
        { id: "c1", task: "Grease all 8 zerk fittings on slide ways", required: true, instructions: "Use lithium-based EP grease gun" },
        { id: "c2", task: "Check hydraulic oil level in reservoir", required: true, instructions: "Top off to max line with ISO VG 46 if below min" },
        { id: "c3", task: "Inspect hydraulic hoses for cracks/leaks", required: true, instructions: "Replace any hose showing chafing, cracking, or weeping" },
        { id: "c4", task: "Apply way oil to slide ways", required: false, instructions: "Thin coat of way lube — wipe off excess" },
        { id: "c5", task: "Test cycle — 5 full strokes", required: true, instructions: "Listen for abnormal noise, watch for smooth travel" },
      ]),
      notes: "LOTO required. Press brake disconnect on rear panel. Approx 2.5 hrs labor.",
    },
    {
      id: 2,
      code: "PM-HYD-002",
      title: "Quarterly hydraulic unit maintenance — HPU-02",
      description: "Quarterly filter replacement, oil change, and accumulator check on hydraulic power unit HPU-02.",
      targetType: "RESOURCE",
      targetId: 8,
      frequency: "QUARTERLY",
      intervalValue: 90,
      nextDueDate: "2026-06-20",
      lastCompletedDate: "2026-03-20",
      assignedTo: "Roberto F.",
      priority: "MEDIUM",
      status: "ACTIVE",
      checklistJson: JSON.stringify([
        { id: "c1", task: "Replace return filter (PN: HYD-FLT-002)", required: true, instructions: "Torque filter housing to 35 Nm" },
        { id: "c2", task: "Drain and replace hydraulic oil (ISO VG 46)", required: true, instructions: "35 gallons. Dispose of old oil per env guidelines." },
        { id: "c3", task: "Check accumulator pre-charge (1200 psi)", required: true, instructions: "Top off with nitrogen if below 1150 psi" },
        { id: "c4", task: "Bleed air from system", required: true, instructions: "Open bleed valve, cycle pump 5 min without load" },
        { id: "c5", task: "Leak check all fittings and hoses", required: true, instructions: "Tighten any weeping fittings. Record in log." },
      ]),
      notes: "⚠ LOTO required. Hydraulic oil at operating temp of 150°F — risk of burns. Wear PPE.",
    },
    {
      id: 3,
      code: "PM-CAL-001",
      title: "Annual torque wrench calibration — Set A",
      description: "Annual recalibration of 12 torque wrenches. Coordinate with external calibration lab. Issue loaner set.",
      targetType: "DEPARTMENT",
      targetId: 1,
      frequency: "YEARLY",
      intervalValue: 365,
      nextDueDate: "2026-07-01",
      lastCompletedDate: "2025-07-01",
      assignedTo: "Lisa M.",
      priority: "LOW",
      status: "ACTIVE",
      checklistJson: JSON.stringify([
        { id: "c1", task: "Inventory all 12 torque wrenches from Set A", required: true, instructions: "Cross-reference with calibration log" },
        { id: "c2", task: "Package and ship to accredited lab", required: true, instructions: "Use foam-lined case. Overnight shipping." },
        { id: "c3", task: "Issue loaner Set B to affected stations", required: true, instructions: "Verify loaner calibration stickers are current" },
        { id: "c4", task: "Update calibration tracking spreadsheet", required: true, instructions: "Enter new due dates, update serial numbers" },
      ]),
      notes: "Budget: $1,200 for external calibration. 5 business day turnaround.",
    },
    {
      id: 4,
      code: "PM-BELT-004",
      title: "Weekly conveyor belt inspection — Line 1",
      description: "Weekly walk-down inspection of all conveyor belts on Production Line 1. Check tension, tracking, wear, and roller condition.",
      targetType: "PRODUCTION_LINE",
      targetId: 1,
      frequency: "WEEKLY",
      intervalValue: 7,
      nextDueDate: "2026-06-13",
      lastCompletedDate: "2026-06-06",
      assignedTo: "Team Lead (Maintenance)",
      priority: "HIGH",
      status: "ACTIVE",
      checklistJson: JSON.stringify([
        { id: "c1", task: "Check belt tension on all 6 conveyors", required: true, instructions: "Deflection should be 1-2% of span length" },
        { id: "c2", task: "Verify belt tracking — center of rollers", required: true, instructions: "Adjust tracking bolts if belt drifts > 5mm" },
        { id: "c3", task: "Inspect belt surface for wear/cuts", required: true, instructions: "Replace belt if damage exposes carcass" },
        { id: "c4", task: "Check roller bearings — listen for noise", required: true, instructions: "Replace any seized or noisy rollers" },
        { id: "c5", task: "Clean debris from belt and rollers", required: false, instructions: "Use compressed air or brush. Watch for trapped debris." },
        { id: "c6", task: "Verify emergency stops functional", required: true, instructions: "Test each E-stop along line" },
      ]),
      notes: "Approx 45 min for full inspection. Two-person team recommended.",
    },
    {
      id: 5,
      code: "PM-AC-005",
      title: "Monthly air compressor PM — Comp #2",
      description: "Monthly preventive maintenance on rotary screw air compressor #2. Oil level, belt tension, drain moisture, check dryers.",
      targetType: "RESOURCE",
      targetId: 10,
      frequency: "MONTHLY",
      intervalValue: 30,
      nextDueDate: "2026-06-25",
      lastCompletedDate: "2026-05-25",
      assignedTo: "Ana R.",
      priority: "MEDIUM",
      status: "PAUSED",
      checklistJson: JSON.stringify([
        { id: "c1", task: "Check compressor oil level and condition", required: true, instructions: "Top off with synthetic rotary screw oil. Sample if >500 hrs." },
        { id: "c2", task: "Drain moisture from receiver tank", required: true, instructions: "Open drain valve until stream is clear of water" },
        { id: "c3", task: "Check belt tension and condition", required: true, instructions: "Deflection 10mm at midpoint. Replace if cracked/frayed." },
        { id: "c4", task: "Inspect air dryer — check condensate drain", required: true, instructions: "Verify auto drain cycles. Clean filter if needed." },
        { id: "c5", task: "Check safety relief valve operation", required: true, instructions: "Lift test ring briefly. Valve should reseat." },
      ]),
      notes: "PAUSED — awaiting replacement belts (PN: BLT-AC-002). ETA from supplier: June 18.",
    },
  ],
};

export const mockDuePmPlans = {
  duePreventiveMaintenance: mockPmPlans.preventiveMaintenancePlans.filter((p) => p.status === "ACTIVE"),
};

// ── 5 Breakdowns ──

export const mockBreakdowns = {
  breakdowns: [
    {
      id: 1,
      number: "BD-2026-001",
      title: "CNC-03 coolant pump failure",
      description: "CNC-03 coolant pump failed at 10:45 during cylinder housing boring operation. Pump motor runs but no coolant flow. Production stopped on Precision Machining group.",
      targetType: "RESOURCE",
      targetId: 3,
      severity: "CRITICAL",
      priority: "CRITICAL",
      status: "IN_PROGRESS",
      reportedBy: "Carlos G. (Operator)",
      assignedTo: "Ana R. (Maintenance Tech)",
      reportedAt: "2026-06-10T10:45:00Z",
      repairStartedAt: "2026-06-10T10:50:00Z",
      repairCompletedAt: null,
      downtimeMinutes: 35,
      downtimeStart: "2026-06-10T10:45:00Z",
      downtimeEnd: null,
      rootCause: "",
      repairSummary: "",
      failureMode: "Coolant pump not priming — impeller likely damaged by debris or bearing failure. Motor draws normal current but no flow.",
      safetyImpact: "Coolant spill hazard if pump housing is cracked. Coolant is water-soluble oil — slippery floors.",
      productionImpact: "Precision Machining group stopped. 12 units queued upstream. Downstream Final Test starved. Estimated 45 min to repair.",
      isEquipmentDown: true,
      temporaryContainment: "Operator moved CNC-03 to manual mode for ongoing boring cycle. No production without coolant — risk of tool damage.",
      suspectedCause: "Debris in coolant tank clogged pump intake. Impeller vanes sheared off.",
      confirmedRootCause: "",
      correctiveAction: "",
      partsRequired: "Coolant pump assembly (PN: CNC-PMP-003), Gasket set (PN: GSK-004)",
      repairNotes: "",
      verificationResult: "",
      completionNotes: "",
      linkedWorkOrderId: 2,
    },
    {
      id: 2,
      number: "BD-2026-002",
      title: "Conveyor 2 — photo-eye sensor misalignment",
      description: "Photo-eye sensor on Conveyor 2 was knocked out of alignment during material handling. Caused intermittent stoppages and false empty readings.",
      targetType: "RESOURCE",
      targetId: 6,
      severity: "HIGH",
      priority: "HIGH",
      status: "RESOLVED",
      reportedBy: "John D. (Operator)",
      assignedTo: "Roberto F. (Technician)",
      reportedAt: "2026-06-10T08:45:00Z",
      repairStartedAt: "2026-06-10T08:50:00Z",
      repairCompletedAt: "2026-06-10T09:00:00Z",
      downtimeMinutes: 15,
      downtimeStart: "2026-06-10T08:45:00Z",
      downtimeEnd: "2026-06-10T09:00:00Z",
      rootCause: "Sensor bracket struck by forklift pallet. Bracket bent 12mm out of alignment.",
      repairSummary: "Realigned sensor bracket to target reflector. Tested 20 cycles — all passed. Scheduled bracket reinforcement as follow-up WO.",
      failureMode: "Intermittent detection failures. Sensor LED visible but beam not returning to receiver. Bracket bent out of alignment.",
      safetyImpact: "None. Conveyor isolated at local disconnect for adjustment.",
      productionImpact: "15 min micro stoppage. 8 units delayed in material handling. Downstream stations experienced minor starvation.",
      isEquipmentDown: false,
      temporaryContainment: "Operator taped sensor to approximate position to keep line running. Maintenance dispatched for permanent fix.",
      suspectedCause: "Forklift contact with sensor bracket during pallet drop-off.",
      confirmedRootCause: "Bracket bent 12mm out of alignment — forklift impact.",
      correctiveAction: "Reinforce bracket with welded gusset plate. Schedule as WO during off-shift.",
      partsRequired: "Sensor bracket reinforcement kit (in-house fabricated)",
      repairNotes: "Bracket realigned and tightened to 15 Nm. Tested OK. WO-2026-003 created for permanent bracket reinforcement.",
      verificationResult: "20 consecutive cycles with zero faults. Sensor range verified at 1.2m (spec: 0.8-1.5m). Pass.",
      completionNotes: "Resolved at 09:00. 15 min downtime. Follow-up bracket reinforcement work order created.",
      linkedWorkOrderId: 3,
    },
    {
      id: 3,
      number: "BD-2026-003",
      title: "Hydraulic leak — Press #2 cylinder seal",
      description: "Press #2 developing hydraulic oil leak from main cylinder rod seal. Dripping approx 2 drops/min. Increasing over last 2 hours.",
      targetType: "RESOURCE",
      targetId: 2,
      severity: "MEDIUM",
      priority: "MEDIUM",
      status: "REPORTED",
      reportedBy: "Maria L. (Operator)",
      assignedTo: "",
      reportedAt: "2026-06-10T09:30:00Z",
      repairStartedAt: null,
      repairCompletedAt: null,
      downtimeMinutes: null,
      downtimeStart: null,
      downtimeEnd: null,
      rootCause: "",
      repairSummary: "",
      failureMode: "Hydraulic oil dripping from cylinder rod seal. Rod shows scoring marks near full extension position. Leak rate increasing.",
      safetyImpact: "Oil on floor creates slip hazard. Hydraulic oil at 120°F — burn risk if in contact with skin.",
      productionImpact: "Press #2 still running but leak is worsening. May require shutdown if leak rate reaches 10 drops/min. Reduced cycle speed by 5%.",
      isEquipmentDown: false,
      temporaryContainment: "Absorbent pads placed under leak. Operator instructed to monitor drip rate hourly. Maintenance alerted.",
      suspectedCause: "Rod seal wear or rod scoring from contamination. Possible wiper seal failure allowing debris into seal area.",
      confirmedRootCause: "",
      correctiveAction: "",
      partsRequired: "Cylinder rod seal kit (PN: CYL-SEAL-002), Hydraulic oil ISO VG 46 (5 gal)",
      repairNotes: "",
      verificationResult: "",
      completionNotes: "",
      linkedWorkOrderId: null,
    },
    {
      id: 4,
      number: "BD-2026-004",
      title: "CMM measurement drift — temperature sensitivity",
      description: "Coordinate Measuring Machine (CMM-01) showing measurement drift of 0.03mm on reference standard. Suspected temperature sensitivity after HVAC adjustment.",
      targetType: "RESOURCE",
      targetId: 8,
      severity: "HIGH",
      priority: "HIGH",
      status: "REPORTED",
      reportedBy: "Lisa M. (Inspector)",
      assignedTo: "",
      reportedAt: "2026-06-10T07:15:00Z",
      repairStartedAt: null,
      repairCompletedAt: null,
      downtimeMinutes: null,
      downtimeStart: null,
      downtimeEnd: null,
      rootCause: "",
      repairSummary: "",
      failureMode: "CMM measurements drifting +0.03mm on calibrated reference sphere. Temperature in metrology lab changed by 2°C since HVAC adjustment on June 8.",
      safetyImpact: "None.",
      productionImpact: "Quality inspection slowed — parts being re-measured 3x to confirm. 15 parts awaiting first-article inspection. Risk of false rejects.",
      isEquipmentDown: false,
      temporaryContainment: "Temperature monitoring log started. Parts being conditioned 2 hrs before measurement. Increasing sample size to 5 per batch for statistical confidence.",
      suspectedCause: "HVAC system adjustment on June 8 changed lab temperature from 20°C to 22°C. CMM requires 20±1°C for specified accuracy.",
      confirmedRootCause: "",
      correctiveAction: "",
      partsRequired: "",
      repairNotes: "",
      verificationResult: "",
      completionNotes: "",
      linkedWorkOrderId: null,
    },
    {
      id: 5,
      number: "BD-2026-005",
      title: "Riveting gun #4 — jammed feed mechanism",
      description: "Pneumatic riveting gun #4 jammed during final assembly. Rivet feed mechanism stuck — rivets not advancing to nosepiece.",
      targetType: "RESOURCE",
      targetId: 11,
      severity: "LOW",
      priority: "LOW",
      status: "CLOSED",
      reportedBy: "Sofia G. (Operator)",
      assignedTo: "Roberto F. (Technician)",
      reportedAt: "2026-06-09T14:30:00Z",
      repairStartedAt: "2026-06-09T14:40:00Z",
      repairCompletedAt: "2026-06-09T15:10:00Z",
      downtimeMinutes: 40,
      downtimeStart: "2026-06-09T14:30:00Z",
      downtimeEnd: "2026-06-09T15:10:00Z",
      rootCause: "Debris (aluminum shaving) lodged in rivet feed track. Caused rivet to skew and jam in the nosepiece.",
      repairSummary: "Disassembled feed mechanism, removed jammed rivet and aluminum shaving. Cleaned feed track with compressed air. Lubricated and reassembled. Tested 50 cycles — all passed.",
      failureMode: "Rivets not advancing. Feed mechanism makes clicking sound but no rivet delivered to nosepiece.",
      safetyImpact: "None. Tool isolated by disconnecting air line.",
      productionImpact: "40 min downtime on Final Assembly station. 8 units delayed. Operator moved to alternate station during repair.",
      isEquipmentDown: true,
      temporaryContainment: "Spare riveting gun #3 issued to station. Gun #4 sent to maintenance for repair.",
      suspectedCause: "Debris in feed track — likely aluminum shaving from previous drilling operation.",
      confirmedRootCause: "Aluminum shaving 3mm x 1mm lodged in rivet feed track at position 23mm from nosepiece.",
      correctiveAction: "Add compressed air blow-off step to end of drilling operation procedure. Install small mesh guard over feed track opening.",
      partsRequired: "None. Existing parts cleaned and reused.",
      repairNotes: "Feed track cleaned, lubricated with light machine oil. No damage to feed pawl or nosepiece. Gun returned to service.",
      verificationResult: "50 consecutive rivet cycles with zero jams. Feed time consistent at 0.8s per rivet (spec: <1.0s). Pass.",
      completionNotes: "Closed after successful test. Root cause identified as aluminum shaving. Procedure update recommended.",
      linkedWorkOrderId: null,
    },
  ],
};

// ── 5 Spare Parts ──

export const mockSpareParts = {
  spareParts: [
    {
      id: 1,
      partNumber: "CNC-PMP-003",
      name: "Coolant pump assembly — CNC-03",
      description: "Grundfos CR-5 coolant pump for CNC-03 machining center. 230V 3-phase, 0.75kW, max flow 5 m³/hr.",
      category: "Hydraulic",
      manufacturer: "Grundfos",
      supplier: "Industrial Pump Supply Co.",
      uom: "EA",
      minQuantity: 2,
      quantityOnHand: 0,
      storageLocation: "Aisle C, Bin 204",
      notes: "Critical spare — no stock! Reorder immediately. Lead time 5-7 business days.",
      status: "ACTIVE",
    },
    {
      id: 2,
      partNumber: "HYD-FLT-002",
      name: "Return filter — HPU-02 hydraulic unit",
      description: "Parker HF-20 return filter element for HPU-02. Beta ratio 200, 25 micron, 250 psi max.",
      category: "Filters",
      manufacturer: "Parker Hannifin",
      supplier: "Motion Industries",
      uom: "EA",
      minQuantity: 4,
      quantityOnHand: 2,
      storageLocation: "Aisle B, Bin 112",
      notes: "Below minimum stock. Order 4 more to restore min level.",
      status: "ACTIVE",
    },
    {
      id: 3,
      partNumber: "HYD-SEAL-001",
      name: "Cylinder rod seal kit — Press #2",
      description: "Seal kit for Press #2 main cylinder. Includes rod seal, wiper seal, and 2x O-rings. Fits Parker 4in bore cylinder.",
      category: "Seals",
      manufacturer: "Parker Hannifin",
      supplier: "Motion Industries",
      uom: "KIT",
      minQuantity: 2,
      quantityOnHand: 1,
      storageLocation: "Aisle D, Bin 301",
      notes: "Low stock. Order 3 kits for min stock level.",
      status: "ACTIVE",
    },
    {
      id: 4,
      partNumber: "BLT-AC-002",
      name: "Compressor drive belt — Air Comp #2",
      description: "Gates Tri-Power B-78 V-belt for rotary screw air compressor #2. 78in outside length, 3/4in width.",
      category: "Belts",
      manufacturer: "Gates Corporation",
      supplier: "Grainger",
      uom: "EA",
      minQuantity: 6,
      quantityOnHand: 8,
      storageLocation: "Aisle A, Bin 015",
      notes: "Stock level OK. Used for quarterly belt replacement.",
      status: "ACTIVE",
    },
    {
      id: 5,
      partNumber: "CYL-SEAL-002",
      name: "Main cylinder seal overhaul kit",
      description: "Complete seal overhaul kit for Press #2 main cylinder. Includes rod seal, piston seal, wiper, O-rings, and backup rings.",
      category: "Seals",
      manufacturer: "Parker Hannifin",
      supplier: "Motion Industries",
      uom: "KIT",
      minQuantity: 1,
      quantityOnHand: 1,
      storageLocation: "Aisle D, Bin 302",
      notes: "Critical spare - maintain at least 1 kit on hand for emergency breakdowns.",
      status: "ACTIVE",
    },
  ],
};

export const mockLowStockSpareParts = {
  lowStockSpareParts: mockSpareParts.spareParts
    .filter((p) => p.status === "ACTIVE" && p.quantityOnHand <= p.minQuantity)
    .map(({ id, partNumber, name, description, category, uom, minQuantity, quantityOnHand, storageLocation, status }) => ({
      id, partNumber, name, description, category, uom, minQuantity, quantityOnHand, storageLocation, status,
    })),
};

// ── Spare Part Usages ──

export const mockSparePartUsages = {
  sparePartUsages: [
    { id: 1, partId: 1, workOrderId: 2, quantity: 1, usedBy: "Ana R.", usedAt: "2026-06-10T11:00:00Z", notes: "Coolant pump replacement on CNC-03", createdAt: "2026-06-10T11:00:00Z", updatedAt: "2026-06-10T11:00:00Z" },
    { id: 2, partId: 2, workOrderId: 5, quantity: 1, usedBy: "Roberto F.", usedAt: "2026-06-07T09:30:00Z", notes: "Quarterly filter change HPU-02", createdAt: "2026-06-07T09:30:00Z", updatedAt: "2026-06-07T09:30:00Z" },
    { id: 3, partId: 3, workOrderId: 5, quantity: 1, usedBy: "Roberto F.", usedAt: "2026-06-07T10:00:00Z", notes: "Preventive seal replacement", createdAt: "2026-06-07T10:00:00Z", updatedAt: "2026-06-07T10:00:00Z" },
  ],
};
