import type { VsmQueryData } from "@/types/vsm";

export const mockVsmDiagram: VsmQueryData = {
  vsmDiagram: {
    lineId: "L001",
    lineName: "C2-Cylinder Assembly",
    productName: "Cylinder Assembly Type-B",
    supplierName: "Tokyo Steel Co.",
    customerName: "Detroit Auto Inc.",
    totalLeadTimeMinutes: 2880,
    totalValueAddMinutes: 1260,
    customerDemandRate: 500,
    customerDemandPeriod: "day",
    customerDemandUnit: "units",
    availableMinutesPerShift: 450,
    chartShiftsPerDay: 2,
    taktTimeSeconds: 108,
    lastUpdatedAt: "2026-06-10T11:02:30Z",
    productionControl: {
      id: "PC-001",
      label: "Production Control",
      schedulingType: "Kanban / Pull",
      schedulingInterval: "Daily",
    },
    processNodes: [
      {
        id: "PN-001", sequence: 1, label: "Cutting", resourceGroupName: "Sub-Assembly",
        cycleTimeSeconds: 28, changeoverSeconds: 600, uptimePercent: 97, operatorCount: 1,
        wipBefore: 0, wipAfter: 80, defectRate: 0.5, isBottleneck: false, isPacemaker: true, isActive: true,
      },
      {
        id: "PN-002", sequence: 2, label: "Precision Machining", resourceGroupName: "Machining Dept",
        cycleTimeSeconds: 45, changeoverSeconds: 1800, uptimePercent: 88, operatorCount: 2,
        wipBefore: 80, wipAfter: 120, defectRate: 1.2, isBottleneck: true, isPacemaker: false, isActive: true,
      },
      {
        id: "PN-003", sequence: 3, label: "Material Handling", resourceGroupName: "Logistics Dept",
        cycleTimeSeconds: 15, changeoverSeconds: 120, uptimePercent: 99, operatorCount: 1,
        wipBefore: 60, wipAfter: 40, defectRate: null, isBottleneck: false, isPacemaker: false, isActive: true,
      },
      {
        id: "PN-004", sequence: 4, label: "Quality Inspection", resourceGroupName: "Quality Dept",
        cycleTimeSeconds: 35, changeoverSeconds: 0, uptimePercent: 95, operatorCount: 1,
        wipBefore: 40, wipAfter: 30, defectRate: 0, isBottleneck: false, isPacemaker: false, isActive: true,
      },
      {
        id: "PN-005", sequence: 5, label: "Final Assembly", resourceGroupName: "Assembly Dept",
        cycleTimeSeconds: 42, changeoverSeconds: 900, uptimePercent: 93, operatorCount: 2,
        wipBefore: 30, wipAfter: 50, defectRate: 0.8, isBottleneck: false, isPacemaker: false, isActive: true,
      },
      {
        id: "PN-006", sequence: 6, label: "Testing & Pack", resourceGroupName: "Quality Dept",
        cycleTimeSeconds: 38, changeoverSeconds: 300, uptimePercent: 91, operatorCount: 1,
        wipBefore: 50, wipAfter: 0, defectRate: 0.3, isBottleneck: false, isPacemaker: false, isActive: false,
      },
    ],
    inventoryNodes: [
      { id: "INV-001", label: "Raw Steel", type: "RM", quantity: 500, daysOfInventory: 3.2 },
      { id: "INV-002", label: "Machined Parts WIP", type: "WIP", quantity: 120, daysOfInventory: 1.4 },
      { id: "INV-003", label: "Inspected WIP", type: "WIP", quantity: 40, daysOfInventory: 0.5 },
      { id: "INV-004", label: "Assembly WIP", type: "WIP", quantity: 50, daysOfInventory: 0.6 },
      { id: "INV-005", label: "Finished Goods", type: "FG", quantity: 300, daysOfInventory: 2.0 },
    ],
    flowLinks: [
      { id: "FL-001", fromId: "SUPPLIER", toId: "INV-001", type: "PUSH", label: "Weekly delivery", deliveryFrequency: "Weekly" },
      { id: "FL-002", fromId: "INV-001", toId: "PN-001", type: "PUSH", label: "FIFO", deliveryFrequency: "" },
      { id: "FL-003", fromId: "PN-001", toId: "INV-002", type: "PUSH", label: "", deliveryFrequency: "" },
      { id: "FL-004", fromId: "INV-002", toId: "PN-002", type: "KANBAN", label: "Kanban = 40", deliveryFrequency: "" },
      { id: "FL-005", fromId: "PN-002", toId: "PN-003", type: "PUSH", label: "FIFO", deliveryFrequency: "" },
      { id: "FL-006", fromId: "PN-003", toId: "INV-003", type: "PUSH", label: "", deliveryFrequency: "" },
      { id: "FL-007", fromId: "INV-003", toId: "PN-004", type: "PUSH", label: "FIFO", deliveryFrequency: "" },
      { id: "FL-008", fromId: "PN-004", toId: "INV-004", type: "PUSH", label: "", deliveryFrequency: "" },
      { id: "FL-009", fromId: "INV-004", toId: "PN-005", type: "KANBAN", label: "Kanban = 20", deliveryFrequency: "" },
      { id: "FL-010", fromId: "PN-005", toId: "PN-006", type: "PUSH", label: "FIFO", deliveryFrequency: "" },
      { id: "FL-011", fromId: "PN-006", toId: "INV-005", type: "PUSH", label: "", deliveryFrequency: "" },
      { id: "FL-012", fromId: "INV-005", toId: "CUSTOMER", type: "PULL", label: "Ship daily", deliveryFrequency: "Daily" },
    ],
    informationFlows: [
      { id: "IF-001", fromId: "CUSTOMER", toId: "PC-001", label: "Daily orders", frequency: "Daily", flowStyle: "ELECTRONIC", method: "EDI", transmissionType: "ELECTRONIC", triggerType: "CUSTOMER_ORDER", controlledProcessId: "", notes: "" },
      { id: "IF-002", fromId: "PC-001", toId: "SUPPLIER", label: "Release schedule", frequency: "Weekly", flowStyle: "ELECTRONIC", method: "ERP email", transmissionType: "ELECTRONIC", triggerType: "RELEASE_SCHEDULE", controlledProcessId: "", notes: "" },
      { id: "IF-003", fromId: "PC-001", toId: "PN-001", label: "Production schedule", frequency: "Daily", flowStyle: "MANUAL", method: "Dispatch list", transmissionType: "MANUAL", triggerType: "PRODUCTION_SCHEDULE", controlledProcessId: "PN-001", notes: "" },
      { id: "IF-004", fromId: "PC-001", toId: "INV-002", label: "Kanban signal", frequency: "Real-time", flowStyle: "KANBAN", method: "Kanban card", transmissionType: "KANBAN", triggerType: "KANBAN_SIGNAL", controlledProcessId: "", notes: "" },
      { id: "IF-005", fromId: "PC-001", toId: "INV-004", label: "Kanban signal", frequency: "Real-time", flowStyle: "KANBAN", method: "Kanban card", transmissionType: "KANBAN", triggerType: "KANBAN_SIGNAL", controlledProcessId: "", notes: "" },
    ],
    timeline: [
      { stepName: "Cutting", processTimeMinutes: 28, waitTimeMinutes: 240, isBottleneck: false },
      { stepName: "Precision Machining", processTimeMinutes: 45, waitTimeMinutes: 360, isBottleneck: true },
      { stepName: "Material Handling", processTimeMinutes: 15, waitTimeMinutes: 120, isBottleneck: false },
      { stepName: "Quality Inspection", processTimeMinutes: 35, waitTimeMinutes: 180, isBottleneck: false },
      { stepName: "Final Assembly", processTimeMinutes: 42, waitTimeMinutes: 240, isBottleneck: false },
      { stepName: "Testing & Pack", processTimeMinutes: 38, waitTimeMinutes: 120, isBottleneck: false },
    ],
  },
};
