# Generated by Django 6.0.4 on 2026-05-27 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErpPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('source_file_type', models.CharField(choices=[('xlsx', 'Excel (.xlsx)'), ('xls', 'Excel (.xls)'), ('csv', 'CSV'), ('tsv', 'TSV'), ('xml', 'XML'), ('json', 'JSON')], default='xlsx', help_text='Expected source file format', max_length=20)),
                ('destination_entity', models.CharField(help_text='Target entity name (e.g. Plant, Department, Material)', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.CharField(blank=True, default='', max_length=200)),
            ],
            options={
                'verbose_name': 'ERP Pattern',
                'verbose_name_plural': 'ERP Patterns',
                'db_table': 'dm_erp_pattern',
                'ordering': ['-is_active', 'name'],
                'indexes': [models.Index(fields=['name'], name='dm_erp_patt_name_594f55_idx'), models.Index(fields=['is_active'], name='dm_erp_patt_is_acti_2cfa48_idx')],
            },
        ),
        migrations.CreateModel(
            name='ErpSourceFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('original_name', models.CharField(help_text='Original uploaded filename', max_length=512)),
                ('stored_name', models.CharField(help_text='Storage filename', max_length=512)),
                ('file_path', models.CharField(help_text='Full path to file in storage', max_length=1024)),
                ('file_type', models.CharField(choices=[('xlsx', 'Excel (.xlsx)'), ('xls', 'Excel (.xls)'), ('csv', 'CSV'), ('tsv', 'TSV'), ('xml', 'XML'), ('json', 'JSON')], default='xlsx', max_length=20)),
                ('uploaded_by', models.CharField(blank=True, default='', max_length=200)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('UPLOADED', 'Uploaded'), ('VALIDATED', 'Validated'), ('IMPORTED', 'Imported'), ('FAILED', 'Failed'), ('DELETED', 'Deleted')], default='UPLOADED', max_length=50)),
            ],
            options={
                'verbose_name': 'ERP Source File',
                'verbose_name_plural': 'ERP Source Files',
                'db_table': 'dm_erp_source_file',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['stored_name'], name='dm_erp_sour_stored__a80eca_idx'), models.Index(fields=['status'], name='dm_erp_sour_status_35fd52_idx'), models.Index(fields=['uploaded_at'], name='dm_erp_sour_uploade_22b529_idx')],
            },
        ),
        migrations.CreateModel(
            name='ErpPatternMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_name', models.CharField(help_text='Source field name from the file', max_length=200)),
                ('source_data_type', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('reference', 'Reference')], default='string', max_length=50)),
                ('destination_name', models.CharField(help_text='Target field name', max_length=200)),
                ('destination_data_type', models.CharField(choices=[('string', 'String'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('reference', 'Reference')], default='string', max_length=50)),
                ('is_required', models.BooleanField(default=False)),
                ('transform_rule', models.TextField(blank=True, default=None, help_text='Optional transformation rule (JSON or expression)', null=True)),
                ('order', models.IntegerField(default=0)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_mappings', to='data_management.erppattern')),
            ],
            options={
                'verbose_name': 'ERP Pattern Mapping',
                'verbose_name_plural': 'ERP Pattern Mappings',
                'db_table': 'dm_erp_pattern_mapping',
                'ordering': ['pattern', 'order', 'source_name'],
                'indexes': [models.Index(fields=['pattern', 'order'], name='dm_erp_patt_pattern_a15f61_idx')],
                'constraints': [models.UniqueConstraint(fields=('pattern', 'source_name'), name='uq_dm_pattern_mapping_source')],
            },
        ),
        migrations.CreateModel(
            name='ErpImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('IMPORTED', 'Imported'), ('FAILED', 'Failed')], default='READY', max_length=50)),
                ('rows_total', models.IntegerField(default=0)),
                ('rows_added', models.IntegerField(default=0)),
                ('rows_updated', models.IntegerField(default=0)),
                ('rows_not_updated', models.IntegerField(default=0)),
                ('rows_failed', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('pattern', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='import_logs', to='data_management.erppattern')),
                ('source_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_logs', to='data_management.erpsourcefile')),
            ],
            options={
                'verbose_name': 'ERP Import Log',
                'verbose_name_plural': 'ERP Import Logs',
                'db_table': 'dm_erp_import_log',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['pattern', 'status'], name='dm_erp_impo_pattern_cf8fd4_idx'), models.Index(fields=['started_at'], name='dm_erp_impo_started_2e8d78_idx')],
            },
        ),
    ]
