# Generated by Django 6.0.4 on 2026-05-27 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpimportlog',
            name='source_file_name',
            field=models.CharField(blank=True, default='', help_text='Snapshot of source file name at import time', max_length=512),
        ),
    ]
