# Generated by Django 6.0.4 on 2026-05-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0002_erpimportlog_source_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpimportlog',
            name='destination_entity_snapshot',
            field=models.CharField(blank=True, default='', help_text='Snapshot of destination entity at import time', max_length=100),
        ),
        migrations.AddField(
            model_name='erpimportlog',
            name='pattern_name_snapshot',
            field=models.CharField(blank=True, default='', help_text='Snapshot of pattern name at import time', max_length=200),
        ),
    ]
