# Generated by Django 6.0.4 on 2026-05-27 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_management', '0003_erpimportlog_destination_entity_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='erpimportlog',
            name='source_sheet_name_snapshot',
            field=models.CharField(blank=True, default='', help_text='Snapshot of source sheet name at import time', max_length=255),
        ),
    ]
