# Generated by Django 6.0.5 on 2026-06-01 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('submitted_by', models.CharField(blank=True, default='', max_length=255)),
                ('target_type', models.CharField(blank=True, default='', max_length=100)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, default='', max_length=100)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'New'), ('UNDER_REVIEW', 'Under Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CONVERTED_TO_KAIZEN', 'Converted to Kaizen')], default='NEW', max_length=30)),
                ('decision', models.TextField(blank=True, default='')),
                ('comments', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Kaizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('problem_statement', models.TextField(blank=True, default='')),
                ('target_type', models.CharField(blank=True, default='', max_length=100)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('current_condition', models.TextField(blank=True, default='')),
                ('target_condition', models.TextField(blank=True, default='')),
                ('owner', models.CharField(blank=True, default='', max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=30)),
                ('result_summary', models.TextField(blank=True, default='')),
                ('source_suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kaizens', to='improvement.suggestion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
