# Generated by Django 6.0.5 on 2026-06-01 16:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('improvement', '0001_add_suggestion_and_kaizen_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaizen',
            name='completed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='kaizen_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20),
        ),
        migrations.AddField(
            model_name='kaizen',
            name='source_type',
            field=models.CharField(choices=[('SUGGESTION', 'Suggestion'), ('GEMBA', 'Gemba Walk'), ('AUDIT', 'Audit'), ('MANUAL', 'Manual'), ('PROCESS_ISSUE', 'Process Issue'), ('MER', 'Manufacturing Engineering Request')], default='MANUAL', max_length=50),
        ),
        migrations.CreateModel(
            name='A3PDCA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('a3_code', models.CharField(blank=True, default='', max_length=50)),
                ('source_type', models.CharField(blank=True, default='', max_length=50)),
                ('target_type', models.CharField(blank=True, default='', max_length=100)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, default='', max_length=255)),
                ('priority', models.CharField(blank=True, default='MEDIUM', max_length=20)),
                ('background', models.TextField(blank=True, default='')),
                ('problem_statement', models.TextField(blank=True, default='')),
                ('current_condition', models.TextField(blank=True, default='')),
                ('target_condition', models.TextField(blank=True, default='')),
                ('root_cause_analysis', models.TextField(blank=True, default='')),
                ('countermeasures', models.TextField(blank=True, default='')),
                ('implementation_plan', models.TextField(blank=True, default='')),
                ('do_notes', models.TextField(blank=True, default='')),
                ('blockers', models.TextField(blank=True, default='')),
                ('result_validation', models.TextField(blank=True, default='')),
                ('before_after_comparison', models.TextField(blank=True, default='')),
                ('effectiveness_check', models.TextField(blank=True, default='')),
                ('standardization_actions', models.TextField(blank=True, default='')),
                ('lessons_learned', models.TextField(blank=True, default='')),
                ('follow_up_plan', models.TextField(blank=True, default='')),
                ('result_summary', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PLAN', 'Plan'), ('DO', 'Do'), ('CHECK', 'Check'), ('ACT', 'Act'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('source_kaizen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='a3_pdca_records', to='improvement.kaizen')),
            ],
            options={
                'verbose_name': 'A3/PDCA',
                'verbose_name_plural': 'A3/PDCA Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='A3PDCAAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phase', models.CharField(blank=True, default='', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('owner', models.CharField(blank=True, default='', max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('a3_pdca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='improvement.a3pdca')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='KaizenAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('owner', models.CharField(blank=True, default='', max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('kaizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='improvement.kaizen')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
