# Generated by Django 6.0.5 on 2026-06-02 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('improvement', '0003_add_mer_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacturingengineeringrequest',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
