# Generated by Django 6.0.5 on 2026-06-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('improvement', '0004_alter_manufacturingengineeringrequest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='manufacturingengineeringrequest',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
