# Generated by Django 6.0.5 on 2026-06-02 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_seed_admin_roles'),
        ('manufacturing', '0073_audit_control_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='administrative_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='manufacturing.referencevalue'),
        ),
        migrations.AlterField(
            model_name='userroleassignment',
            name='administrative_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_assignments', to='manufacturing.referencevalue'),
        ),
    ]
