# Generated by Django 6.0.5 on 2026-06-21 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_seed_roles_from_reference_values'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('SKILL', 'Skill'), ('CERTIFICATION', 'Certification'), ('LICENSE', 'License'), ('TRAINING', 'Training')], default='SKILL', max_length=20)),
                ('level', models.CharField(blank=True, default='', max_length=100)),
                ('issuer', models.CharField(blank=True, default='', max_length=200)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expires_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='administration.userprofile')),
            ],
            options={
                'verbose_name': 'Profile Skill',
                'verbose_name_plural': 'Profile Skills',
                'db_table': 'administration_profile_skill',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_profile'], name='admin_skill_user_idx'), models.Index(fields=['category'], name='admin_skill_cat_idx'), models.Index(fields=['is_active'], name='admin_skill_active_idx')],
            },
        ),
    ]
