# Generated by Django 6.0.5 on 2026-06-23 15:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_profileskill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('USER_ACTIVITY', 'User Activity'), ('DATA_CHANGE', 'Data Change'), ('LOGIN_EVENT', 'Login / Access Event'), ('SYSTEM_EVENT', 'System Event')], db_index=True, max_length=30)),
                ('username', models.CharField(blank=True, default='', max_length=200)),
                ('action', models.CharField(db_index=True, max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('entity_type', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('entity_id', models.CharField(blank=True, default='', max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'System Audit Log',
                'verbose_name_plural': 'System Audit Logs',
                'db_table': 'administration_system_audit_log',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type'], name='admin_audit_event_type_idx'), models.Index(fields=['action'], name='admin_audit_action_idx'), models.Index(fields=['entity_type'], name='admin_audit_entity_type_idx'), models.Index(fields=['event_type', 'created_at'], name='admin_audit_type_created_idx'), models.Index(fields=['user'], name='admin_audit_user_idx')],
            },
        ),
    ]
