"""Domain constants for the check app."""

APPROVED_TARGET_TYPES = ["PLANT", "PRODUCTION_LINE", "DEPARTMENT", "RESOURCE_GROUP", "RESOURCE"]

CONTROL_AREA_PRODUCTION = "PRODUCTION"
CONTROL_AREA_QUALITY = "QUALITY"
CONTROL_AREA_SAFETY = "SAFETY"
CONTROL_AREA_MATERIAL = "MATERIAL"

CONTROL_AREA_CHOICES = [
    (CONTROL_AREA_PRODUCTION, "Production"),
    (CONTROL_AREA_QUALITY, "Quality"),
    (CONTROL_AREA_SAFETY, "Safety"),
    (CONTROL_AREA_MATERIAL, "Material"),
]

# ── Problem ──
PROBLEM_TYPE_PRODUCTION = "PRODUCTION"
PROBLEM_TYPE_QUALITY = "QUALITY"
PROBLEM_TYPE_SAFETY = "SAFETY"
PROBLEM_TYPE_MATERIAL = "MATERIAL"
PROBLEM_TYPE_GENERAL = "GENERAL"

PROBLEM_TYPE_CHOICES = [
    (PROBLEM_TYPE_PRODUCTION, "Production"),
    (PROBLEM_TYPE_QUALITY, "Quality"),
    (PROBLEM_TYPE_SAFETY, "Safety"),
    (PROBLEM_TYPE_MATERIAL, "Material"),
    (PROBLEM_TYPE_GENERAL, "General"),
]

PROBLEM_STATUS_OPEN = "OPEN"
PROBLEM_STATUS_IN_REVIEW = "IN_REVIEW"
PROBLEM_STATUS_IN_PROGRESS = "IN_PROGRESS"
PROBLEM_STATUS_CONTAINED = "CONTAINED"
PROBLEM_STATUS_RESOLVED = "RESOLVED"
PROBLEM_STATUS_CLOSED = "CLOSED"
PROBLEM_STATUS_CANCELLED = "CANCELLED"

PROBLEM_STATUS_CHOICES = [
    (PROBLEM_STATUS_OPEN, "Open"),
    (PROBLEM_STATUS_IN_REVIEW, "In Review"),
    (PROBLEM_STATUS_IN_PROGRESS, "In Progress"),
    (PROBLEM_STATUS_CONTAINED, "Contained"),
    (PROBLEM_STATUS_RESOLVED, "Resolved"),
    (PROBLEM_STATUS_CLOSED, "Closed"),
    (PROBLEM_STATUS_CANCELLED, "Cancelled"),
]

# ── Action ──
ACTION_STATUS_OPEN = "OPEN"
ACTION_STATUS_IN_PROGRESS = "IN_PROGRESS"
ACTION_STATUS_DONE = "DONE"
ACTION_STATUS_COMPLETED = "COMPLETED"
ACTION_STATUS_OVERDUE = "OVERDUE"
ACTION_STATUS_CANCELLED = "CANCELLED"

ACTION_STATUS_CHOICES = [
    (ACTION_STATUS_OPEN, "Open"),
    (ACTION_STATUS_IN_PROGRESS, "In Progress"),
    (ACTION_STATUS_DONE, "Done"),
    (ACTION_STATUS_COMPLETED, "Completed"),
    (ACTION_STATUS_OVERDUE, "Overdue"),
    (ACTION_STATUS_CANCELLED, "Cancelled"),
]

ACTION_PRIORITY_LOW = "LOW"
ACTION_PRIORITY_MEDIUM = "MEDIUM"
ACTION_PRIORITY_HIGH = "HIGH"
ACTION_PRIORITY_CRITICAL = "CRITICAL"

ACTION_PRIORITY_CHOICES = [
    (ACTION_PRIORITY_LOW, "Low"),
    (ACTION_PRIORITY_MEDIUM, "Medium"),
    (ACTION_PRIORITY_HIGH, "High"),
    (ACTION_PRIORITY_CRITICAL, "Critical"),
]

ACTION_TYPE_CONTAINMENT = "CONTAINMENT"
ACTION_TYPE_CORRECTIVE = "CORRECTIVE"
ACTION_TYPE_PREVENTIVE = "PREVENTIVE"
ACTION_TYPE_FOLLOW_UP = "FOLLOW_UP"
ACTION_TYPE_VERIFICATION = "VERIFICATION"
ACTION_TYPE_ESCALATION = "ESCALATION"
ACTION_TYPE_OTHER = "OTHER"

ACTION_TYPE_CHOICES = [
    (ACTION_TYPE_CONTAINMENT, "Containment"),
    (ACTION_TYPE_CORRECTIVE, "Corrective"),
    (ACTION_TYPE_PREVENTIVE, "Preventive"),
    (ACTION_TYPE_FOLLOW_UP, "Follow-up"),
    (ACTION_TYPE_VERIFICATION, "Verification"),
    (ACTION_TYPE_ESCALATION, "Escalation"),
    (ACTION_TYPE_OTHER, "Other"),
]

# ── Production Check ──
PRODUCTION_CHECK_TYPE_FIVE_S = "FIVE_S"
PRODUCTION_CHECK_TYPE_PROCESS_CHECK = "PROCESS_CHECK"
PRODUCTION_CHECK_TYPE_STANDARD_WORK_CHECK = "STANDARD_WORK_CHECK"
PRODUCTION_CHECK_TYPE_TOOL_CONDITION_CHECK = "TOOL_CONDITION_CHECK"
PRODUCTION_CHECK_TYPE_LINE_COMPLIANCE_CHECK = "LINE_COMPLIANCE_CHECK"

PRODUCTION_CHECK_TYPE_CHOICES = [
    (PRODUCTION_CHECK_TYPE_FIVE_S, "5S"),
    (PRODUCTION_CHECK_TYPE_PROCESS_CHECK, "Process Check"),
    (PRODUCTION_CHECK_TYPE_STANDARD_WORK_CHECK, "Standard Work Check"),
    (PRODUCTION_CHECK_TYPE_TOOL_CONDITION_CHECK, "Tool Condition Check"),
    (PRODUCTION_CHECK_TYPE_LINE_COMPLIANCE_CHECK, "Line Compliance Check"),
]

CHECK_STATUS_DRAFT = "DRAFT"
CHECK_STATUS_COMPLETED = "COMPLETED"

CHECK_STATUS_CHOICES = [
    (CHECK_STATUS_DRAFT, "Draft"),
    (CHECK_STATUS_COMPLETED, "Completed"),
]

CHECKLIST_RESULT_PASS = "PASS"
CHECKLIST_RESULT_FAIL = "FAIL"
CHECKLIST_RESULT_N_A = "N_A"

CHECKLIST_RESULT_CHOICES = [
    (CHECKLIST_RESULT_PASS, "Pass"),
    (CHECKLIST_RESULT_FAIL, "Fail"),
    (CHECKLIST_RESULT_N_A, "N/A"),
]

# ── Quality Check ──
QUALITY_CHECK_TYPE_QUALITY_AUDIT = "QUALITY_AUDIT"
QUALITY_CHECK_TYPE_INSPECTION = "INSPECTION"
QUALITY_CHECK_TYPE_DEFECT_CHECK = "DEFECT_CHECK"
QUALITY_CHECK_TYPE_NONCONFORMANCE_CHECK = "NONCONFORMANCE_CHECK"

QUALITY_CHECK_TYPE_CHOICES = [
    (QUALITY_CHECK_TYPE_QUALITY_AUDIT, "Quality Audit"),
    (QUALITY_CHECK_TYPE_INSPECTION, "Inspection"),
    (QUALITY_CHECK_TYPE_DEFECT_CHECK, "Defect Check"),
    (QUALITY_CHECK_TYPE_NONCONFORMANCE_CHECK, "Nonconformance Check"),
]

# ── DMR ──
DMR_STATUS_OPEN = "OPEN"
DMR_STATUS_UNDER_REVIEW = "UNDER_REVIEW"
DMR_STATUS_QUARANTINED = "QUARANTINED"
DMR_STATUS_DISPOSITION_PENDING = "DISPOSITION_PENDING"
DMR_STATUS_DISPOSITION_APPROVED = "DISPOSITION_APPROVED"
DMR_STATUS_CLOSED = "CLOSED"
DMR_STATUS_CANCELLED = "CANCELLED"

DMR_STATUS_CHOICES = [
    (DMR_STATUS_OPEN, "Open"),
    (DMR_STATUS_UNDER_REVIEW, "Under Review"),
    (DMR_STATUS_QUARANTINED, "Quarantined"),
    (DMR_STATUS_DISPOSITION_PENDING, "Disposition Pending"),
    (DMR_STATUS_DISPOSITION_APPROVED, "Disposition Approved"),
    (DMR_STATUS_CLOSED, "Closed"),
    (DMR_STATUS_CANCELLED, "Cancelled"),
]

DMR_DISPOSITION_USE_AS_IS = "USE_AS_IS"
DMR_DISPOSITION_REWORK = "REWORK"
DMR_DISPOSITION_SCRAP = "SCRAP"
DMR_DISPOSITION_RETURN_TO_SUPPLIER = "RETURN_TO_SUPPLIER"
DMR_DISPOSITION_HOLD = "HOLD"
DMR_DISPOSITION_SORT_INSPECT = "SORT_INSPECT"

DMR_DISPOSITION_CHOICES = [
    (DMR_DISPOSITION_HOLD, "Hold / Quarantine"),
    (DMR_DISPOSITION_USE_AS_IS, "Use As Is"),
    (DMR_DISPOSITION_REWORK, "Rework"),
    (DMR_DISPOSITION_SCRAP, "Scrap"),
    (DMR_DISPOSITION_RETURN_TO_SUPPLIER, "Return to Supplier"),
    (DMR_DISPOSITION_SORT_INSPECT, "Sort / Inspect"),
]

# ── RMA ──
RMA_STATUS_OPEN = "OPEN"
RMA_STATUS_RECEIVED = "RECEIVED"
RMA_STATUS_UNDER_REVIEW = "UNDER_REVIEW"
RMA_STATUS_DISPOSITION_PENDING = "DISPOSITION_PENDING"
RMA_STATUS_CUSTOMER_RESPONSE_PENDING = "CUSTOMER_RESPONSE_PENDING"
RMA_STATUS_CLOSED = "CLOSED"
RMA_STATUS_CANCELLED = "CANCELLED"

RMA_STATUS_CHOICES = [
    (RMA_STATUS_OPEN, "Open"),
    (RMA_STATUS_RECEIVED, "Received"),
    (RMA_STATUS_UNDER_REVIEW, "Under Review"),
    (RMA_STATUS_DISPOSITION_PENDING, "Disposition Pending"),
    (RMA_STATUS_CUSTOMER_RESPONSE_PENDING, "Customer Response Pending"),
    (RMA_STATUS_CLOSED, "Closed"),
    (RMA_STATUS_CANCELLED, "Cancelled"),
]

RMA_DISPOSITION_REPLACE = "REPLACE"
RMA_DISPOSITION_REPAIR = "REPAIR"
RMA_DISPOSITION_CREDIT = "CREDIT"
RMA_DISPOSITION_REJECT_RETURN = "REJECT_RETURN"
RMA_DISPOSITION_SCRAP = "SCRAP"
RMA_DISPOSITION_RETURN_TO_CUSTOMER = "RETURN_TO_CUSTOMER"

RMA_DISPOSITION_CHOICES = [
    (RMA_DISPOSITION_REPLACE, "Replace"),
    (RMA_DISPOSITION_REPAIR, "Repair"),
    (RMA_DISPOSITION_CREDIT, "Credit"),
    (RMA_DISPOSITION_REJECT_RETURN, "Reject Return"),
    (RMA_DISPOSITION_SCRAP, "Scrap"),
    (RMA_DISPOSITION_RETURN_TO_CUSTOMER, "Return to Customer"),
]

RMA_CUSTOMER_RESPONSE_NOT_REQUIRED = "NOT_REQUIRED"
RMA_CUSTOMER_RESPONSE_PENDING = "PENDING"
RMA_CUSTOMER_RESPONSE_SENT = "SENT"
RMA_CUSTOMER_RESPONSE_ACCEPTED = "ACCEPTED"
RMA_CUSTOMER_RESPONSE_REJECTED = "REJECTED"
RMA_CUSTOMER_RESPONSE_CLOSED = "CLOSED"

RMA_CUSTOMER_RESPONSE_CHOICES = [
    (RMA_CUSTOMER_RESPONSE_NOT_REQUIRED, "Not Required"),
    (RMA_CUSTOMER_RESPONSE_PENDING, "Pending"),
    (RMA_CUSTOMER_RESPONSE_SENT, "Sent"),
    (RMA_CUSTOMER_RESPONSE_ACCEPTED, "Accepted"),
    (RMA_CUSTOMER_RESPONSE_REJECTED, "Rejected"),
    (RMA_CUSTOMER_RESPONSE_CLOSED, "Closed"),
]

# ── Safety Check ──
SAFETY_CHECK_TYPE_SAFETY_AUDIT = "SAFETY_AUDIT"
SAFETY_CHECK_TYPE_SAFETY_OBSERVATION = "SAFETY_OBSERVATION"
SAFETY_CHECK_TYPE_PPE_CHECK = "PPE_CHECK"
SAFETY_CHECK_TYPE_UNSAFE_CONDITION_CHECK = "UNSAFE_CONDITION_CHECK"
SAFETY_CHECK_TYPE_NEAR_MISS_REVIEW = "NEAR_MISS_REVIEW"

SAFETY_CHECK_TYPE_CHOICES = [
    (SAFETY_CHECK_TYPE_SAFETY_AUDIT, "Safety Audit"),
    (SAFETY_CHECK_TYPE_SAFETY_OBSERVATION, "Safety Observation"),
    (SAFETY_CHECK_TYPE_PPE_CHECK, "PPE Check"),
    (SAFETY_CHECK_TYPE_UNSAFE_CONDITION_CHECK, "Unsafe Condition Check"),
    (SAFETY_CHECK_TYPE_NEAR_MISS_REVIEW, "Near Miss Review"),
]

# ── Safety Incident / Event ──
EVENT_TYPE_INCIDENT = "INCIDENT"
EVENT_TYPE_ACCIDENT = "ACCIDENT"
EVENT_TYPE_NEAR_MISS = "NEAR_MISS"
EVENT_TYPE_HAZARD = "HAZARD"
EVENT_TYPE_OBSERVATION = "OBSERVATION"

EVENT_TYPE_CHOICES = [
    (EVENT_TYPE_INCIDENT, "Incident"),
    (EVENT_TYPE_ACCIDENT, "Accident"),
    (EVENT_TYPE_NEAR_MISS, "Near Miss"),
    (EVENT_TYPE_HAZARD, "Hazard"),
    (EVENT_TYPE_OBSERVATION, "Observation"),
]

EVENT_STATUS_DRAFT = "DRAFT"
EVENT_STATUS_REPORTED = "REPORTED"
EVENT_STATUS_UNDER_REVIEW = "UNDER_REVIEW"
EVENT_STATUS_ACTION_REQUIRED = "ACTION_REQUIRED"
EVENT_STATUS_CLOSED = "CLOSED"
EVENT_STATUS_CANCELLED = "CANCELLED"

EVENT_STATUS_CHOICES = [
    (EVENT_STATUS_DRAFT, "Draft"),
    (EVENT_STATUS_REPORTED, "Reported"),
    (EVENT_STATUS_UNDER_REVIEW, "Under Review"),
    (EVENT_STATUS_ACTION_REQUIRED, "Action Required"),
    (EVENT_STATUS_CLOSED, "Closed"),
    (EVENT_STATUS_CANCELLED, "Cancelled"),
]

# Retain legacy incident choice sets for existing SafetyIncident model
INCIDENT_TYPE_UNSAFE_CONDITION = "UNSAFE_CONDITION"
INCIDENT_TYPE_NEAR_MISS = "NEAR_MISS"
INCIDENT_TYPE_INCIDENT = "INCIDENT"
INCIDENT_TYPE_PPE_VIOLATION = "PPE_VIOLATION"
INCIDENT_TYPE_CHOICES = [
    (INCIDENT_TYPE_UNSAFE_CONDITION, "Unsafe Condition"),
    (INCIDENT_TYPE_NEAR_MISS, "Near Miss"),
    (INCIDENT_TYPE_INCIDENT, "Incident"),
    (INCIDENT_TYPE_PPE_VIOLATION, "PPE Violation"),
]
INCIDENT_STATUS_OPEN = "OPEN"
INCIDENT_STATUS_CONTAINED = "CONTAINED"
INCIDENT_STATUS_UNDER_REVIEW = "UNDER_REVIEW"
INCIDENT_STATUS_CLOSED = "CLOSED"
INCIDENT_STATUS_CANCELLED = "CANCELLED"
INCIDENT_STATUS_CHOICES = [
    (INCIDENT_STATUS_OPEN, "Open"),
    (INCIDENT_STATUS_CONTAINED, "Contained"),
    (INCIDENT_STATUS_UNDER_REVIEW, "Under Review"),
    (INCIDENT_STATUS_CLOSED, "Closed"),
    (INCIDENT_STATUS_CANCELLED, "Cancelled"),
]

# ── Material Check ──
MATERIAL_CHECK_TYPE_MATERIAL_FLOW_CHECK = "MATERIAL_FLOW_CHECK"
MATERIAL_CHECK_TYPE_FIFO_CHECK = "FIFO_CHECK"
MATERIAL_CHECK_TYPE_BIN_CHECK = "BIN_CHECK"
MATERIAL_CHECK_TYPE_WIP_CHECK = "WIP_CHECK"
MATERIAL_CHECK_TYPE_SHORTAGE_CHECK = "SHORTAGE_CHECK"
MATERIAL_CHECK_TYPE_WRONG_MATERIAL_CHECK = "WRONG_MATERIAL_CHECK"
MATERIAL_CHECK_TYPE_SUPERMARKET_CHECK = "SUPERMARKET_CHECK"

MATERIAL_CHECK_TYPE_CHOICES = [
    (MATERIAL_CHECK_TYPE_MATERIAL_FLOW_CHECK, "Material Flow Check"),
    (MATERIAL_CHECK_TYPE_FIFO_CHECK, "FIFO Check"),
    (MATERIAL_CHECK_TYPE_BIN_CHECK, "Bin Check"),
    (MATERIAL_CHECK_TYPE_WIP_CHECK, "WIP Check"),
    (MATERIAL_CHECK_TYPE_SHORTAGE_CHECK, "Shortage Check"),
    (MATERIAL_CHECK_TYPE_WRONG_MATERIAL_CHECK, "Wrong Material Check"),
    (MATERIAL_CHECK_TYPE_SUPERMARKET_CHECK, "Supermarket Check"),
]

MATERIAL_ISSUE_TYPE_SHORTAGE = "SHORTAGE"
MATERIAL_ISSUE_TYPE_WRONG_MATERIAL = "WRONG_MATERIAL"
MATERIAL_ISSUE_TYPE_BIN_ERROR = "BIN_ERROR"
MATERIAL_ISSUE_TYPE_FIFO_VIOLATION = "FIFO_VIOLATION"
MATERIAL_ISSUE_TYPE_WIP_OVERFLOW = "WIP_OVERFLOW"
MATERIAL_ISSUE_TYPE_MATERIAL_DAMAGE = "MATERIAL_DAMAGE"
MATERIAL_ISSUE_TYPE_HANDLING_ISSUE = "HANDLING_ISSUE"

MATERIAL_ISSUE_TYPE_CHOICES = [
    (MATERIAL_ISSUE_TYPE_SHORTAGE, "Shortage"),
    (MATERIAL_ISSUE_TYPE_WRONG_MATERIAL, "Wrong Material"),
    (MATERIAL_ISSUE_TYPE_BIN_ERROR, "Bin Error"),
    (MATERIAL_ISSUE_TYPE_FIFO_VIOLATION, "FIFO Violation"),
    (MATERIAL_ISSUE_TYPE_WIP_OVERFLOW, "WIP Overflow"),
    (MATERIAL_ISSUE_TYPE_MATERIAL_DAMAGE, "Material Damage"),
    (MATERIAL_ISSUE_TYPE_HANDLING_ISSUE, "Handling Issue"),
]

MATERIAL_ISSUE_STATUS_OPEN = "OPEN"
MATERIAL_ISSUE_STATUS_CONTAINED = "CONTAINED"
MATERIAL_ISSUE_STATUS_RESOLVED = "RESOLVED"
MATERIAL_ISSUE_STATUS_CLOSED = "CLOSED"
MATERIAL_ISSUE_STATUS_CANCELLED = "CANCELLED"

MATERIAL_ISSUE_STATUS_CHOICES = [
    (MATERIAL_ISSUE_STATUS_OPEN, "Open"),
    (MATERIAL_ISSUE_STATUS_CONTAINED, "Contained"),
    (MATERIAL_ISSUE_STATUS_RESOLVED, "Resolved"),
    (MATERIAL_ISSUE_STATUS_CLOSED, "Closed"),
    (MATERIAL_ISSUE_STATUS_CANCELLED, "Cancelled"),
]

# ── Source Types (for Issues and Actions) ──
SOURCE_TYPE_MANUAL = "MANUAL"
SOURCE_TYPE_AUDIT_FINDING = "AUDIT_FINDING"
SOURCE_TYPE_AUDIT = "AUDIT"
SOURCE_TYPE_GEMBA_WALK = "GEMBA_WALK"
SOURCE_TYPE_DMR = "DMR"
SOURCE_TYPE_RMA = "RMA"
SOURCE_TYPE_PRODUCTION_PROBLEM = "PRODUCTION_PROBLEM"
SOURCE_TYPE_SAFETY_EVENT = "SAFETY_EVENT"
SOURCE_TYPE_MATERIAL_PROBLEM = "MATERIAL_PROBLEM"
SOURCE_TYPE_QUALITY_PROBLEM = "QUALITY_PROBLEM"
SOURCE_TYPE_BREAKDOWN = "BREAKDOWN"
SOURCE_TYPE_MER = "MER"
SOURCE_TYPE_KAIZEN = "KAIZEN"

SOURCE_TYPE_CHOICES = [
    (SOURCE_TYPE_MANUAL, "Manual"),
    (SOURCE_TYPE_AUDIT_FINDING, "Audit Finding"),
    (SOURCE_TYPE_AUDIT, "Audit"),
    (SOURCE_TYPE_GEMBA_WALK, "Gemba Walk"),
    (SOURCE_TYPE_DMR, "DMR"),
    (SOURCE_TYPE_RMA, "RMA"),
    (SOURCE_TYPE_PRODUCTION_PROBLEM, "Production Problem"),
    (SOURCE_TYPE_SAFETY_EVENT, "Safety Event"),
    (SOURCE_TYPE_MATERIAL_PROBLEM, "Material Problem"),
    (SOURCE_TYPE_QUALITY_PROBLEM, "Quality Problem"),
    (SOURCE_TYPE_BREAKDOWN, "Breakdown"),
    (SOURCE_TYPE_MER, "MER"),
    (SOURCE_TYPE_KAIZEN, "Kaizen"),
]

# ── Safety Compliance (Injury Claim, Medical Case, Env Report, CAPA) ──

# Claim types
CLAIM_TYPE_FIRST_AID = "FIRST_AID"
CLAIM_TYPE_MEDICAL_TREATMENT = "MEDICAL_TREATMENT"
CLAIM_TYPE_LOST_TIME = "LOST_TIME"
CLAIM_TYPE_RESTRICTED_WORK = "RESTRICTED_WORK"
CLAIM_TYPE_FATALITY = "FATALITY"
CLAIM_TYPE_OCCUPATIONAL_ILLNESS = "OCCUPATIONAL_ILLNESS"
CLAIM_TYPE_OTHER = "OTHER"

CLAIM_TYPE_CHOICES = [
    (CLAIM_TYPE_FIRST_AID, "First Aid"),
    (CLAIM_TYPE_MEDICAL_TREATMENT, "Medical Treatment"),
    (CLAIM_TYPE_LOST_TIME, "Lost Time"),
    (CLAIM_TYPE_RESTRICTED_WORK, "Restricted Work"),
    (CLAIM_TYPE_FATALITY, "Fatality"),
    (CLAIM_TYPE_OCCUPATIONAL_ILLNESS, "Occupational Illness"),
    (CLAIM_TYPE_OTHER, "Other"),
]

CLAIM_STATUS_DRAFT = "DRAFT"
CLAIM_STATUS_OPEN = "OPEN"
CLAIM_STATUS_UNDER_REVIEW = "UNDER_REVIEW"
CLAIM_STATUS_WAITING_INFO = "WAITING_INFO"
CLAIM_STATUS_CLOSED = "CLOSED"
CLAIM_STATUS_CANCELLED = "CANCELLED"

CLAIM_STATUS_CHOICES = [
    (CLAIM_STATUS_DRAFT, "Draft"),
    (CLAIM_STATUS_OPEN, "Open"),
    (CLAIM_STATUS_UNDER_REVIEW, "Under Review"),
    (CLAIM_STATUS_WAITING_INFO, "Waiting Info"),
    (CLAIM_STATUS_CLOSED, "Closed"),
    (CLAIM_STATUS_CANCELLED, "Cancelled"),
]

CARE_TYPE_FIRST_AID = "FIRST_AID"
CARE_TYPE_ON_SITE = "ON_SITE"
CARE_TYPE_CLINIC_VISIT = "CLINIC_VISIT"
CARE_TYPE_EMERGENCY_ROOM = "EMERGENCY_ROOM"
CARE_TYPE_HOSPITALIZATION = "HOSPITALIZATION"
CARE_TYPE_SPECIALIST = "SPECIALIST"
CARE_TYPE_FOLLOW_UP = "FOLLOW_UP"

CARE_TYPE_CHOICES = [
    (CARE_TYPE_FIRST_AID, "First Aid"),
    (CARE_TYPE_ON_SITE, "On-Site Treatment"),
    (CARE_TYPE_CLINIC_VISIT, "Clinic Visit"),
    (CARE_TYPE_EMERGENCY_ROOM, "Emergency Room"),
    (CARE_TYPE_HOSPITALIZATION, "Hospitalization"),
    (CARE_TYPE_SPECIALIST, "Specialist"),
    (CARE_TYPE_FOLLOW_UP, "Follow-up"),
]

MEDICAL_STATUS_DRAFT = "DRAFT"
MEDICAL_STATUS_OPEN = "OPEN"
MEDICAL_STATUS_MONITORING = "MONITORING"
MEDICAL_STATUS_RETURNED_TO_WORK = "RETURNED_TO_WORK"
MEDICAL_STATUS_CLOSED = "CLOSED"
MEDICAL_STATUS_CANCELLED = "CANCELLED"

MEDICAL_STATUS_CHOICES = [
    (MEDICAL_STATUS_DRAFT, "Draft"),
    (MEDICAL_STATUS_OPEN, "Open"),
    (MEDICAL_STATUS_MONITORING, "Monitoring"),
    (MEDICAL_STATUS_RETURNED_TO_WORK, "Returned to Work"),
    (MEDICAL_STATUS_CLOSED, "Closed"),
    (MEDICAL_STATUS_CANCELLED, "Cancelled"),
]

ENV_REPORT_TYPE_SPILL = "SPILL"
ENV_REPORT_TYPE_RELEASE = "RELEASE"
ENV_REPORT_TYPE_DISCHARGE = "DISCHARGE"
ENV_REPORT_TYPE_EMISSION = "EMISSION"
ENV_REPORT_TYPE_WASTE = "WASTE"
ENV_REPORT_TYPE_CONTAMINATION = "CONTAMINATION"
ENV_REPORT_TYPE_OTHER = "OTHER"

ENV_REPORT_TYPE_CHOICES = [
    (ENV_REPORT_TYPE_SPILL, "Spill"),
    (ENV_REPORT_TYPE_RELEASE, "Release"),
    (ENV_REPORT_TYPE_DISCHARGE, "Discharge"),
    (ENV_REPORT_TYPE_EMISSION, "Emission"),
    (ENV_REPORT_TYPE_WASTE, "Waste"),
    (ENV_REPORT_TYPE_CONTAMINATION, "Contamination"),
    (ENV_REPORT_TYPE_OTHER, "Other"),
]

ENV_REPORT_STATUS_DRAFT = "DRAFT"
ENV_REPORT_STATUS_REPORTED = "REPORTED"
ENV_REPORT_STATUS_UNDER_REVIEW = "UNDER_REVIEW"
ENV_REPORT_STATUS_ACTION_REQUIRED = "ACTION_REQUIRED"
ENV_REPORT_STATUS_CLOSED = "CLOSED"
ENV_REPORT_STATUS_CANCELLED = "CANCELLED"

ENV_REPORT_STATUS_CHOICES = [
    (ENV_REPORT_STATUS_DRAFT, "Draft"),
    (ENV_REPORT_STATUS_REPORTED, "Reported"),
    (ENV_REPORT_STATUS_UNDER_REVIEW, "Under Review"),
    (ENV_REPORT_STATUS_ACTION_REQUIRED, "Action Required"),
    (ENV_REPORT_STATUS_CLOSED, "Closed"),
    (ENV_REPORT_STATUS_CANCELLED, "Cancelled"),
]

CAPA_STATUS_DRAFT = "DRAFT"
CAPA_STATUS_OPEN = "OPEN"
CAPA_STATUS_IN_PROGRESS = "IN_PROGRESS"
CAPA_STATUS_PENDING_EFFECTIVENESS = "PENDING_EFFECTIVENESS"
CAPA_STATUS_EFFECTIVE = "EFFECTIVE"
CAPA_STATUS_INEFFECTIVE = "INEFFECTIVE"
CAPA_STATUS_CLOSED = "CLOSED"
CAPA_STATUS_CANCELLED = "CANCELLED"

CAPA_STATUS_CHOICES = [
    (CAPA_STATUS_DRAFT, "Draft"),
    (CAPA_STATUS_OPEN, "Open"),
    (CAPA_STATUS_IN_PROGRESS, "In Progress"),
    (CAPA_STATUS_PENDING_EFFECTIVENESS, "Pending Effectiveness"),
    (CAPA_STATUS_EFFECTIVE, "Effective"),
    (CAPA_STATUS_INEFFECTIVE, "Ineffective"),
    (CAPA_STATUS_CLOSED, "Closed"),
    (CAPA_STATUS_CANCELLED, "Cancelled"),
]

CAPA_SOURCE_TYPES = ["SAFETY_EVENT", "SAFETY_CHECK", "INJURY_CLAIM", "MEDICAL_CASE", "ENVIRONMENTAL_REPORT"]

# ── Severity ──
SEVERITY_LOW = "LOW"
SEVERITY_MEDIUM = "MEDIUM"
SEVERITY_HIGH = "HIGH"
SEVERITY_CRITICAL = "CRITICAL"

SEVERITY_CHOICES = [
    (SEVERITY_LOW, "Low"),
    (SEVERITY_MEDIUM, "Medium"),
    (SEVERITY_HIGH, "High"),
    (SEVERITY_CRITICAL, "Critical"),
]
