"""Domain constants for the check app."""

APPROVED_TARGET_TYPES = ["PLANT", "PRODUCTION_LINE", "DEPARTMENT", "RESOURCE_GROUP", "RESOURCE"]

# ── Problem ──
PROBLEM_TYPE_PRODUCTION = "PRODUCTION"
PROBLEM_TYPE_QUALITY = "QUALITY"
PROBLEM_TYPE_SAFETY = "SAFETY"
PROBLEM_TYPE_MATERIAL = "MATERIAL"
PROBLEM_TYPE_GENERAL = "GENERAL"

PROBLEM_TYPE_CHOICES = [
    (PROBLEM_TYPE_PRODUCTION, "Production"),
    (PROBLEM_TYPE_QUALITY, "Quality"),
    (PROBLEM_TYPE_SAFETY, "Safety"),
    (PROBLEM_TYPE_MATERIAL, "Material"),
    (PROBLEM_TYPE_GENERAL, "General"),
]

PROBLEM_STATUS_OPEN = "OPEN"
PROBLEM_STATUS_IN_REVIEW = "IN_REVIEW"
PROBLEM_STATUS_CONTAINED = "CONTAINED"
PROBLEM_STATUS_CLOSED = "CLOSED"
PROBLEM_STATUS_CANCELLED = "CANCELLED"

PROBLEM_STATUS_CHOICES = [
    (PROBLEM_STATUS_OPEN, "Open"),
    (PROBLEM_STATUS_IN_REVIEW, "In Review"),
    (PROBLEM_STATUS_CONTAINED, "Contained"),
    (PROBLEM_STATUS_CLOSED, "Closed"),
    (PROBLEM_STATUS_CANCELLED, "Cancelled"),
]

# ── Action ──
ACTION_STATUS_OPEN = "OPEN"
ACTION_STATUS_IN_PROGRESS = "IN_PROGRESS"
ACTION_STATUS_DONE = "DONE"
ACTION_STATUS_CANCELLED = "CANCELLED"

ACTION_STATUS_CHOICES = [
    (ACTION_STATUS_OPEN, "Open"),
    (ACTION_STATUS_IN_PROGRESS, "In Progress"),
    (ACTION_STATUS_DONE, "Done"),
    (ACTION_STATUS_CANCELLED, "Cancelled"),
]

ACTION_PRIORITY_LOW = "LOW"
ACTION_PRIORITY_MEDIUM = "MEDIUM"
ACTION_PRIORITY_HIGH = "HIGH"
ACTION_PRIORITY_CRITICAL = "CRITICAL"

ACTION_PRIORITY_CHOICES = [
    (ACTION_PRIORITY_LOW, "Low"),
    (ACTION_PRIORITY_MEDIUM, "Medium"),
    (ACTION_PRIORITY_HIGH, "High"),
    (ACTION_PRIORITY_CRITICAL, "Critical"),
]

# ── Production Check ──
PRODUCTION_CHECK_TYPE_FIVE_S = "FIVE_S"
PRODUCTION_CHECK_TYPE_PROCESS_CHECK = "PROCESS_CHECK"
PRODUCTION_CHECK_TYPE_STANDARD_WORK_CHECK = "STANDARD_WORK_CHECK"
PRODUCTION_CHECK_TYPE_TOOL_CONDITION_CHECK = "TOOL_CONDITION_CHECK"
PRODUCTION_CHECK_TYPE_LINE_COMPLIANCE_CHECK = "LINE_COMPLIANCE_CHECK"

PRODUCTION_CHECK_TYPE_CHOICES = [
    (PRODUCTION_CHECK_TYPE_FIVE_S, "5S"),
    (PRODUCTION_CHECK_TYPE_PROCESS_CHECK, "Process Check"),
    (PRODUCTION_CHECK_TYPE_STANDARD_WORK_CHECK, "Standard Work Check"),
    (PRODUCTION_CHECK_TYPE_TOOL_CONDITION_CHECK, "Tool Condition Check"),
    (PRODUCTION_CHECK_TYPE_LINE_COMPLIANCE_CHECK, "Line Compliance Check"),
]

CHECK_STATUS_DRAFT = "DRAFT"
CHECK_STATUS_COMPLETED = "COMPLETED"

CHECK_STATUS_CHOICES = [
    (CHECK_STATUS_DRAFT, "Draft"),
    (CHECK_STATUS_COMPLETED, "Completed"),
]

CHECKLIST_RESULT_PASS = "PASS"
CHECKLIST_RESULT_FAIL = "FAIL"
CHECKLIST_RESULT_N_A = "N_A"

CHECKLIST_RESULT_CHOICES = [
    (CHECKLIST_RESULT_PASS, "Pass"),
    (CHECKLIST_RESULT_FAIL, "Fail"),
    (CHECKLIST_RESULT_N_A, "N/A"),
]

# ── Quality Check ──
QUALITY_CHECK_TYPE_QUALITY_AUDIT = "QUALITY_AUDIT"
QUALITY_CHECK_TYPE_INSPECTION = "INSPECTION"
QUALITY_CHECK_TYPE_DEFECT_CHECK = "DEFECT_CHECK"
QUALITY_CHECK_TYPE_NONCONFORMANCE_CHECK = "NONCONFORMANCE_CHECK"

QUALITY_CHECK_TYPE_CHOICES = [
    (QUALITY_CHECK_TYPE_QUALITY_AUDIT, "Quality Audit"),
    (QUALITY_CHECK_TYPE_INSPECTION, "Inspection"),
    (QUALITY_CHECK_TYPE_DEFECT_CHECK, "Defect Check"),
    (QUALITY_CHECK_TYPE_NONCONFORMANCE_CHECK, "Nonconformance Check"),
]

# ── DMR ──
DMR_STATUS_OPEN = "OPEN"
DMR_STATUS_UNDER_REVIEW = "UNDER_REVIEW"
DMR_STATUS_DISPOSITIONED = "DISPOSITIONED"
DMR_STATUS_CLOSED = "CLOSED"
DMR_STATUS_CANCELLED = "CANCELLED"

DMR_STATUS_CHOICES = [
    (DMR_STATUS_OPEN, "Open"),
    (DMR_STATUS_UNDER_REVIEW, "Under Review"),
    (DMR_STATUS_DISPOSITIONED, "Dispositioned"),
    (DMR_STATUS_CLOSED, "Closed"),
    (DMR_STATUS_CANCELLED, "Cancelled"),
]

DMR_DISPOSITION_USE_AS_IS = "USE_AS_IS"
DMR_DISPOSITION_REWORK = "REWORK"
DMR_DISPOSITION_SCRAP = "SCRAP"
DMR_DISPOSITION_RETURN_TO_VENDOR = "RETURN_TO_VENDOR"
DMR_DISPOSITION_HOLD = "HOLD"

DMR_DISPOSITION_CHOICES = [
    (DMR_DISPOSITION_USE_AS_IS, "Use As Is"),
    (DMR_DISPOSITION_REWORK, "Rework"),
    (DMR_DISPOSITION_SCRAP, "Scrap"),
    (DMR_DISPOSITION_RETURN_TO_VENDOR, "Return to Vendor"),
    (DMR_DISPOSITION_HOLD, "Hold"),
]

# ── RMA ──
RMA_STATUS_OPEN = "OPEN"
RMA_STATUS_RECEIVED = "RECEIVED"
RMA_STATUS_UNDER_REVIEW = "UNDER_REVIEW"
RMA_STATUS_DISPOSITIONED = "DISPOSITIONED"
RMA_STATUS_CLOSED = "CLOSED"
RMA_STATUS_CANCELLED = "CANCELLED"

RMA_STATUS_CHOICES = [
    (RMA_STATUS_OPEN, "Open"),
    (RMA_STATUS_RECEIVED, "Received"),
    (RMA_STATUS_UNDER_REVIEW, "Under Review"),
    (RMA_STATUS_DISPOSITIONED, "Dispositioned"),
    (RMA_STATUS_CLOSED, "Closed"),
    (RMA_STATUS_CANCELLED, "Cancelled"),
]

# ── Safety Check ──
SAFETY_CHECK_TYPE_SAFETY_AUDIT = "SAFETY_AUDIT"
SAFETY_CHECK_TYPE_SAFETY_OBSERVATION = "SAFETY_OBSERVATION"
SAFETY_CHECK_TYPE_PPE_CHECK = "PPE_CHECK"
SAFETY_CHECK_TYPE_UNSAFE_CONDITION_CHECK = "UNSAFE_CONDITION_CHECK"
SAFETY_CHECK_TYPE_NEAR_MISS_REVIEW = "NEAR_MISS_REVIEW"

SAFETY_CHECK_TYPE_CHOICES = [
    (SAFETY_CHECK_TYPE_SAFETY_AUDIT, "Safety Audit"),
    (SAFETY_CHECK_TYPE_SAFETY_OBSERVATION, "Safety Observation"),
    (SAFETY_CHECK_TYPE_PPE_CHECK, "PPE Check"),
    (SAFETY_CHECK_TYPE_UNSAFE_CONDITION_CHECK, "Unsafe Condition Check"),
    (SAFETY_CHECK_TYPE_NEAR_MISS_REVIEW, "Near Miss Review"),
]

# ── Safety Incident ──
INCIDENT_TYPE_UNSAFE_CONDITION = "UNSAFE_CONDITION"
INCIDENT_TYPE_NEAR_MISS = "NEAR_MISS"
INCIDENT_TYPE_INCIDENT = "INCIDENT"
INCIDENT_TYPE_PPE_VIOLATION = "PPE_VIOLATION"

INCIDENT_TYPE_CHOICES = [
    (INCIDENT_TYPE_UNSAFE_CONDITION, "Unsafe Condition"),
    (INCIDENT_TYPE_NEAR_MISS, "Near Miss"),
    (INCIDENT_TYPE_INCIDENT, "Incident"),
    (INCIDENT_TYPE_PPE_VIOLATION, "PPE Violation"),
]

INCIDENT_STATUS_OPEN = "OPEN"
INCIDENT_STATUS_CONTAINED = "CONTAINED"
INCIDENT_STATUS_UNDER_REVIEW = "UNDER_REVIEW"
INCIDENT_STATUS_CLOSED = "CLOSED"
INCIDENT_STATUS_CANCELLED = "CANCELLED"

INCIDENT_STATUS_CHOICES = [
    (INCIDENT_STATUS_OPEN, "Open"),
    (INCIDENT_STATUS_CONTAINED, "Contained"),
    (INCIDENT_STATUS_UNDER_REVIEW, "Under Review"),
    (INCIDENT_STATUS_CLOSED, "Closed"),
    (INCIDENT_STATUS_CANCELLED, "Cancelled"),
]

# ── Material Check ──
MATERIAL_CHECK_TYPE_MATERIAL_FLOW_CHECK = "MATERIAL_FLOW_CHECK"
MATERIAL_CHECK_TYPE_FIFO_CHECK = "FIFO_CHECK"
MATERIAL_CHECK_TYPE_BIN_CHECK = "BIN_CHECK"
MATERIAL_CHECK_TYPE_WIP_CHECK = "WIP_CHECK"
MATERIAL_CHECK_TYPE_SHORTAGE_CHECK = "SHORTAGE_CHECK"
MATERIAL_CHECK_TYPE_WRONG_MATERIAL_CHECK = "WRONG_MATERIAL_CHECK"
MATERIAL_CHECK_TYPE_SUPERMARKET_CHECK = "SUPERMARKET_CHECK"

MATERIAL_CHECK_TYPE_CHOICES = [
    (MATERIAL_CHECK_TYPE_MATERIAL_FLOW_CHECK, "Material Flow Check"),
    (MATERIAL_CHECK_TYPE_FIFO_CHECK, "FIFO Check"),
    (MATERIAL_CHECK_TYPE_BIN_CHECK, "Bin Check"),
    (MATERIAL_CHECK_TYPE_WIP_CHECK, "WIP Check"),
    (MATERIAL_CHECK_TYPE_SHORTAGE_CHECK, "Shortage Check"),
    (MATERIAL_CHECK_TYPE_WRONG_MATERIAL_CHECK, "Wrong Material Check"),
    (MATERIAL_CHECK_TYPE_SUPERMARKET_CHECK, "Supermarket Check"),
]

MATERIAL_ISSUE_TYPE_SHORTAGE = "SHORTAGE"
MATERIAL_ISSUE_TYPE_WRONG_MATERIAL = "WRONG_MATERIAL"
MATERIAL_ISSUE_TYPE_BIN_ERROR = "BIN_ERROR"
MATERIAL_ISSUE_TYPE_FIFO_VIOLATION = "FIFO_VIOLATION"
MATERIAL_ISSUE_TYPE_WIP_OVERFLOW = "WIP_OVERFLOW"
MATERIAL_ISSUE_TYPE_MATERIAL_DAMAGE = "MATERIAL_DAMAGE"
MATERIAL_ISSUE_TYPE_HANDLING_ISSUE = "HANDLING_ISSUE"

MATERIAL_ISSUE_TYPE_CHOICES = [
    (MATERIAL_ISSUE_TYPE_SHORTAGE, "Shortage"),
    (MATERIAL_ISSUE_TYPE_WRONG_MATERIAL, "Wrong Material"),
    (MATERIAL_ISSUE_TYPE_BIN_ERROR, "Bin Error"),
    (MATERIAL_ISSUE_TYPE_FIFO_VIOLATION, "FIFO Violation"),
    (MATERIAL_ISSUE_TYPE_WIP_OVERFLOW, "WIP Overflow"),
    (MATERIAL_ISSUE_TYPE_MATERIAL_DAMAGE, "Material Damage"),
    (MATERIAL_ISSUE_TYPE_HANDLING_ISSUE, "Handling Issue"),
]

MATERIAL_ISSUE_STATUS_OPEN = "OPEN"
MATERIAL_ISSUE_STATUS_CONTAINED = "CONTAINED"
MATERIAL_ISSUE_STATUS_RESOLVED = "RESOLVED"
MATERIAL_ISSUE_STATUS_CLOSED = "CLOSED"
MATERIAL_ISSUE_STATUS_CANCELLED = "CANCELLED"

MATERIAL_ISSUE_STATUS_CHOICES = [
    (MATERIAL_ISSUE_STATUS_OPEN, "Open"),
    (MATERIAL_ISSUE_STATUS_CONTAINED, "Contained"),
    (MATERIAL_ISSUE_STATUS_RESOLVED, "Resolved"),
    (MATERIAL_ISSUE_STATUS_CLOSED, "Closed"),
    (MATERIAL_ISSUE_STATUS_CANCELLED, "Cancelled"),
]

# ── Severity ──
SEVERITY_LOW = "LOW"
SEVERITY_MEDIUM = "MEDIUM"
SEVERITY_HIGH = "HIGH"
SEVERITY_CRITICAL = "CRITICAL"

SEVERITY_CHOICES = [
    (SEVERITY_LOW, "Low"),
    (SEVERITY_MEDIUM, "Medium"),
    (SEVERITY_HIGH, "High"),
    (SEVERITY_CRITICAL, "Critical"),
]
