# Generated by Django 6.0.4 on 2026-05-22 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='importsourceconfig',
            name='mapping_profile_path',
            field=models.CharField(blank=True, default='', help_text='Mapping profile path under erp_data/structure/', max_length=512),
        ),
        migrations.AddField(
            model_name='importsourceconfig',
            name='pattern_path',
            field=models.CharField(blank=True, default='', help_text='Optional template file path under erp_data/patterns/', max_length=512),
        ),
        migrations.AlterField(
            model_name='importsourceconfig',
            name='path',
            field=models.CharField(help_text='Relative path under erp_data/source/', max_length=512),
        ),
    ]
