# Generated by Django 6.0.5 on 2026-06-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='control_area',
            field=models.CharField(choices=[('PRODUCTION', 'Production'), ('QUALITY', 'Quality'), ('SAFETY', 'Safety'), ('MATERIAL', 'Material')], default='PRODUCTION', max_length=30),
        ),
        migrations.AddField(
            model_name='problem',
            name='control_area',
            field=models.CharField(choices=[('PRODUCTION', 'Production'), ('QUALITY', 'Quality'), ('SAFETY', 'Safety'), ('MATERIAL', 'Material')], default='PRODUCTION', max_length=30),
        ),
    ]
