# Generated by Django 6.0.5 on 2026-06-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0002_action_control_area_problem_control_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='rma',
            name='confirmed_cause',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rma',
            name='confirmed_defect',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rma',
            name='customer_response_status',
            field=models.CharField(choices=[('NOT_REQUIRED', 'Not Required'), ('PENDING', 'Pending'), ('SENT', 'Sent'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('CLOSED', 'Closed')], default='NOT_REQUIRED', max_length=30),
        ),
        migrations.AddField(
            model_name='rma',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rma',
            name='part_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='rma',
            name='receiving_inspection_result',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rma',
            name='serial_lot',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='rma',
            name='suspected_cause',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='rma',
            name='disposition',
            field=models.CharField(blank=True, choices=[('REPLACE', 'Replace'), ('REPAIR', 'Repair'), ('CREDIT', 'Credit'), ('REJECT_RETURN', 'Reject Return'), ('SCRAP', 'Scrap'), ('RETURN_TO_CUSTOMER', 'Return to Customer')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rma',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('RECEIVED', 'Received'), ('UNDER_REVIEW', 'Under Review'), ('DISPOSITION_PENDING', 'Disposition Pending'), ('CUSTOMER_RESPONSE_PENDING', 'Customer Response Pending'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=30),
        ),
    ]
