# Generated by Django 6.0.5 on 2026-06-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0003_add_rma_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmr',
            name='containment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dmr',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dmr',
            name='severity',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20),
        ),
        migrations.AlterField(
            model_name='dmr',
            name='disposition',
            field=models.CharField(blank=True, choices=[('HOLD', 'Hold / Quarantine'), ('USE_AS_IS', 'Use As Is'), ('REWORK', 'Rework'), ('SCRAP', 'Scrap'), ('RETURN_TO_SUPPLIER', 'Return to Supplier'), ('SORT_INSPECT', 'Sort / Inspect')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='dmr',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('QUARANTINED', 'Quarantined'), ('DISPOSITION_PENDING', 'Disposition Pending'), ('DISPOSITION_APPROVED', 'Disposition Approved'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=30),
        ),
    ]
