# Generated by Django 6.0.5 on 2026-06-07 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0004_add_dmr_severity_containment_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rma',
            name='customer_response',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='rma',
            name='disposition_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rma',
            name='disposition_owner',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
