# Generated by Django 6.0.5 on 2026-06-09 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0005_add_rma_disposition_owner_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='action_type',
            field=models.CharField(blank=True, default='CORRECTIVE', max_length=50),
        ),
        migrations.AddField(
            model_name='action',
            name='assigned_to',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='action',
            name='completed_by',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='action',
            name='completion_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='action',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='action',
            name='linked_issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to='check.problem'),
        ),
        migrations.AddField(
            model_name='action',
            name='plant',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='action',
            name='production_line',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='action',
            name='resource',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='action',
            name='resource_group',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='action',
            name='target_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='action',
            name='target_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='problem',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='containment_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='problem',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='owner',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='problem',
            name='plant',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='problem',
            name='production_line',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='problem',
            name='resolution_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='problem',
            name='resource',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='problem',
            name='resource_group',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='problem',
            name='root_cause',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='action',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=30),
        ),
        migrations.AlterField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('IN_REVIEW', 'In Review'), ('IN_PROGRESS', 'In Progress'), ('CONTAINED', 'Contained'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=30),
        ),
    ]
