# Generated by Django 6.0.5 on 2026-06-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0006_add_action_type_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('INCIDENT', 'Incident'), ('ACCIDENT', 'Accident'), ('NEAR_MISS', 'Near Miss'), ('HAZARD', 'Hazard'), ('OBSERVATION', 'Observation')], max_length=30)),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REPORTED', 'Reported'), ('UNDER_REVIEW', 'Under Review'), ('ACTION_REQUIRED', 'Action Required'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('target_type', models.CharField(max_length=100)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('reported_by', models.CharField(blank=True, default='', max_length=255)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('location_text', models.CharField(blank=True, default='', max_length=500)),
                ('immediate_action', models.TextField(blank=True, default='')),
                ('injury_involved', models.BooleanField(default=False)),
                ('property_damage', models.BooleanField(default=False)),
                ('environmental_impact', models.BooleanField(default=False)),
                ('owner', models.CharField(blank=True, default='', max_length=255)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Safety Event',
                'verbose_name_plural': 'Safety Events',
                'ordering': ['-created_at'],
            },
        ),
    ]
