# Generated by Django 6.0.5 on 2026-06-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0007_add_safetyevent_model'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='safetyevent',
            index=models.Index(fields=['event_type'], name='safety_evt_type_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyevent',
            index=models.Index(fields=['status'], name='safety_evt_status_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyevent',
            index=models.Index(fields=['severity'], name='safety_evt_severity_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyevent',
            index=models.Index(fields=['target_type', 'target_id'], name='safety_evt_target_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyevent',
            index=models.Index(fields=['occurred_at'], name='safety_evt_occurred_idx'),
        ),
    ]
