# Generated by Django 6.0.5 on 2026-06-20 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('check', '0008_add_safetyevent_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyCAPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_type', models.CharField(max_length=50)),
                ('source_id', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(max_length=255)),
                ('problem_statement', models.TextField(blank=True, default='')),
                ('root_cause', models.TextField(blank=True, default='')),
                ('containment_action', models.TextField(blank=True, default='')),
                ('corrective_action', models.TextField(blank=True, default='')),
                ('preventive_action', models.TextField(blank=True, default='')),
                ('owner', models.CharField(blank=True, default='', max_length=255)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('effectiveness_check_required', models.BooleanField(default=False)),
                ('effectiveness_result', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('PENDING_EFFECTIVENESS', 'Pending Effectiveness'), ('EFFECTIVE', 'Effective'), ('INEFFECTIVE', 'Ineffective'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'Safety CAPA',
                'verbose_name_plural': 'Safety CAPAs',
                'db_table': 'check_safety_capa',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='capa_status_idx'), models.Index(fields=['owner'], name='capa_owner_idx'), models.Index(fields=['due_date'], name='capa_due_idx'), models.Index(fields=['source_type', 'source_id'], name='capa_source_idx')],
            },
        ),
        migrations.CreateModel(
            name='SafetyInjuryClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim_number', models.CharField(blank=True, default='', max_length=100)),
                ('claimant_name', models.CharField(max_length=255)),
                ('claimant_employee_id', models.CharField(blank=True, default='', max_length=100)),
                ('claim_type', models.CharField(choices=[('FIRST_AID', 'First Aid'), ('MEDICAL_TREATMENT', 'Medical Treatment'), ('LOST_TIME', 'Lost Time'), ('RESTRICTED_WORK', 'Restricted Work'), ('FATALITY', 'Fatality'), ('OCCUPATIONAL_ILLNESS', 'Occupational Illness'), ('OTHER', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('WAITING_INFO', 'Waiting Info'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('injury_summary', models.TextField(blank=True, default='')),
                ('body_area', models.CharField(blank=True, default='', max_length=200)),
                ('lost_time', models.BooleanField(default=False)),
                ('restricted_work', models.BooleanField(default=False)),
                ('reported_to_insurer', models.BooleanField(default=False)),
                ('insurer_reference', models.CharField(blank=True, default='', max_length=200)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('safety_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='injury_claims', to='check.safetyevent')),
            ],
            options={
                'verbose_name': 'Safety Injury Claim',
                'verbose_name_plural': 'Safety Injury Claims',
                'db_table': 'check_safety_injury_claim',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyMedicalCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case_number', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('OPEN', 'Open'), ('MONITORING', 'Monitoring'), ('RETURNED_TO_WORK', 'Returned to Work'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('care_type', models.CharField(choices=[('FIRST_AID', 'First Aid'), ('ON_SITE', 'On-Site Treatment'), ('CLINIC_VISIT', 'Clinic Visit'), ('EMERGENCY_ROOM', 'Emergency Room'), ('HOSPITALIZATION', 'Hospitalization'), ('SPECIALIST', 'Specialist'), ('FOLLOW_UP', 'Follow-up')], max_length=50)),
                ('visit_required', models.BooleanField(default=False)),
                ('visit_date', models.DateTimeField(blank=True, null=True)),
                ('work_restriction', models.BooleanField(default=False)),
                ('restriction_summary', models.TextField(blank=True, default='')),
                ('return_to_work_date', models.DateTimeField(blank=True, null=True)),
                ('confidential_notes', models.TextField(blank=True, default='')),
                ('owner', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('injury_claim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_cases', to='check.safetyinjuryclaim')),
                ('safety_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_cases', to='check.safetyevent')),
            ],
            options={
                'verbose_name': 'Safety Medical Case',
                'verbose_name_plural': 'Safety Medical Cases',
                'db_table': 'check_safety_medical_case',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyEnvironmentalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report_type', models.CharField(choices=[('SPILL', 'Spill'), ('RELEASE', 'Release'), ('DISCHARGE', 'Discharge'), ('EMISSION', 'Emission'), ('WASTE', 'Waste'), ('CONTAMINATION', 'Contamination'), ('OTHER', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REPORTED', 'Reported'), ('UNDER_REVIEW', 'Under Review'), ('ACTION_REQUIRED', 'Action Required'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('material_involved', models.CharField(blank=True, default='', max_length=255)),
                ('estimated_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('unit', models.CharField(blank=True, default='', max_length=50)),
                ('containment_action', models.TextField(blank=True, default='')),
                ('cleanup_required', models.BooleanField(default=False)),
                ('reported_externally', models.BooleanField(default=False)),
                ('external_reference', models.CharField(blank=True, default='', max_length=200)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('target_type', models.CharField(blank=True, default='', max_length=100)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('location_text', models.CharField(blank=True, default='', max_length=500)),
                ('owner', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('safety_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='environmental_reports', to='check.safetyevent')),
            ],
            options={
                'verbose_name': 'Safety Environmental Report',
                'verbose_name_plural': 'Safety Environmental Reports',
                'db_table': 'check_safety_env_report',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='ser_status_idx'), models.Index(fields=['owner'], name='ser_owner_idx'), models.Index(fields=['safety_event'], name='ser_event_idx'), models.Index(fields=['report_type'], name='ser_type_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='safetyinjuryclaim',
            index=models.Index(fields=['status'], name='sic_status_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyinjuryclaim',
            index=models.Index(fields=['owner'], name='sic_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyinjuryclaim',
            index=models.Index(fields=['safety_event'], name='sic_event_idx'),
        ),
        migrations.AddIndex(
            model_name='safetyinjuryclaim',
            index=models.Index(fields=['claim_type'], name='sic_type_idx'),
        ),
        migrations.AddIndex(
            model_name='safetymedicalcase',
            index=models.Index(fields=['status'], name='smc_status_idx'),
        ),
        migrations.AddIndex(
            model_name='safetymedicalcase',
            index=models.Index(fields=['owner'], name='smc_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='safetymedicalcase',
            index=models.Index(fields=['safety_event'], name='smc_event_idx'),
        ),
        migrations.AddIndex(
            model_name='safetymedicalcase',
            index=models.Index(fields=['injury_claim'], name='smc_claim_idx'),
        ),
        migrations.AddIndex(
            model_name='safetymedicalcase',
            index=models.Index(fields=['care_type'], name='smc_care_type_idx'),
        ),
    ]
