# Generated by Django 6.0.5 on 2026-06-21 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_profileskill'),
        ('check', '0009_add_env_report_target_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='safetymedicalcase',
            name='affected_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_cases', to='administration.userprofile'),
        ),
        migrations.AddIndex(
            model_name='safetymedicalcase',
            index=models.Index(fields=['affected_person'], name='smc_person_idx'),
        ),
    ]
